import type { Metadata } from "next"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

export const metadata: Metadata = {
  title: "Privacy Policy — LegalLawDocs.com",
  description:
    "Learn how LegalLawDocs.com collects, uses, and protects your personal data. Covers GDPR and CCPA rights, payment processing, data retention, and contact information.",
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen">
      <Header />
      <main>
        <div className="mx-auto max-w-4xl px-4 py-16 lg:px-8 lg:py-24">
          {/* Header */}
          <div className="mb-10 border-b border-border/40 pb-8">
            <div className="mb-3 inline-flex items-center rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
              Legal
            </div>
            <h1 className="font-serif text-4xl font-bold text-foreground">Privacy Policy</h1>
            <p className="mt-3 text-muted-foreground">
              Last updated: <span className="text-foreground font-medium">August 29, 2026</span>
            </p>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              This Privacy Policy describes how LegalLawDocs.com (&ldquo;LegalLawDocs,&rdquo; &ldquo;we,&rdquo;
              &ldquo;us,&rdquo; or &ldquo;our&rdquo;) collects, uses, discloses, and protects your personal
              information when you use our website and services. Please read this policy carefully.
              By using our services, you agree to the practices described here.
            </p>
          </div>

          {/* Table of contents */}
          <nav className="mb-10 rounded-2xl border border-border/50 bg-card/60 p-5">
            <p className="text-sm font-semibold text-foreground mb-3">Contents</p>
            <ol className="space-y-1.5 text-sm text-primary">
              {[
                ["1. Information we collect", "#collect"],
                ["2. How we use your information", "#use"],
                ["3. Payment processing (Stripe)", "#stripe"],
                ["4. How we share your information", "#sharing"],
                ["5. Data retention", "#retention"],
                ["6. Security", "#security"],
                ["7. Your rights (GDPR & CCPA)", "#rights"],
                ["8. Cookies", "#cookies"],
                ["9. Children's privacy", "#children"],
                ["10. Changes to this policy", "#changes"],
                ["11. Contact us", "#contact"],
              ].map(([label, href]) => (
                <li key={href}>
                  <a href={href} className="underline underline-offset-4 hover:text-primary/80">
                    {label}
                  </a>
                </li>
              ))}
            </ol>
          </nav>

          <div className="space-y-10 text-muted-foreground">
            <section id="collect">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                1. Information we collect
              </h2>
              <p className="leading-relaxed">
                We collect information you provide directly, information generated by your use of
                our services, and limited technical information.
              </p>

              <h3 className="mt-5 font-semibold text-foreground">Information you provide</h3>
              <ul className="mt-3 space-y-2">
                {[
                  { field: "Name", desc: "Provided during account registration or document creation." },
                  { field: "Email address", desc: "Used to create your account, send receipts, and communicate with you." },
                  { field: "Payment information", desc: "Credit card and billing details processed by Stripe (we never store your raw card number)." },
                  { field: "Document content", desc: "Information you enter to generate legal documents (party names, addresses, contract terms, etc.)." },
                  { field: "Communications", desc: "Messages you send to our support team." },
                ].map(({ field, desc }) => (
                  <li key={field} className="flex gap-3">
                    <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                    <span>
                      <strong className="text-foreground">{field}:</strong> {desc}
                    </span>
                  </li>
                ))}
              </ul>

              <h3 className="mt-5 font-semibold text-foreground">Information processed automatically</h3>
              <ul className="mt-3 space-y-2">
                {[
                  "IP address and request metadata processed by hosting and security providers",
                  "Browser, device, and operating-system information included in operational logs",
                  "Requested routes, request timing, status codes, and application errors",
                  "Authentication, security, and disclaimer-acceptance cookie data",
                ].map((item) => (
                  <li key={item} className="flex gap-3">
                    <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </section>

            <section id="use">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                2. How we use your information
              </h2>
              <p className="leading-relaxed">We use the information we collect to:</p>
              <ul className="mt-3 space-y-2">
                {[
                  "Provide, maintain, and improve our document generation services",
                  "Process payments and send purchase confirmations and receipts",
                  "Create and manage your user account",
                  "Generate and store legal documents on your behalf",
                  "Respond to support inquiries and provide customer service",
                  "Send transactional emails (password resets, subscription notices)",
                  "Detect and prevent fraud, abuse, and security incidents",
                  "Comply with applicable laws and legal obligations",
                ].map((item) => (
                  <li key={item} className="flex gap-3">
                    <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </section>

            <section id="stripe">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                3. Payment processing (Stripe)
              </h2>
              <p className="leading-relaxed">
                All payment transactions are processed by{" "}
                <a
                  href="https://stripe.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline underline-offset-4 hover:text-primary/80"
                >
                  Stripe, Inc.
                </a>
                , a PCI-DSS Level 1 certified payment processor. When you make a payment on
                LegalLawDocs.com, your credit card details are entered directly into Stripe&apos;s
                secure interface and transmitted directly to Stripe&apos;s servers.
              </p>
              <p className="mt-3 leading-relaxed">
                We do not store your full credit card number, CVC, or expiration date on our
                servers. We receive only a tokenized reference from Stripe that allows us to
                process future charges (for subscriptions) or issue refunds. Stripe&apos;s handling
                of your payment data is governed by{" "}
                <a
                  href="https://stripe.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline underline-offset-4 hover:text-primary/80"
                >
                  Stripe&apos;s Privacy Policy
                </a>
                .
              </p>
            </section>

            <section id="sharing">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                4. How we share your information
              </h2>
              <p className="leading-relaxed">
                We do not sell your personal information. Information may be disclosed in the
                following circumstances:
              </p>
              <ul className="mt-3 space-y-3">
                {[
                  {
                    title: "Service providers",
                    desc: "Hosting, database, AI, email, and payment providers process data as needed to operate the features you use. Their handling is also governed by their applicable service and privacy terms.",
                  },
                  {
                    title: "Legal requirements",
                    desc: "We may disclose your information if required by law, court order, subpoena, or government request, or when we believe disclosure is necessary to protect our rights, your safety, or the safety of others.",
                  },
                  {
                    title: "Business transfers",
                    desc: "If LegalLawDocs.com is involved in a merger, acquisition, financing, reorganisation, bankruptcy, or sale of assets, information may be transferred subject to applicable law.",
                  },
                  {
                    title: "With your consent",
                    desc: "We may share your information with third parties when you have given us explicit consent to do so.",
                  },
                ].map(({ title, desc }) => (
                  <li key={title} className="flex gap-3">
                    <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                    <span>
                      <strong className="text-foreground">{title}:</strong> {desc}
                    </span>
                  </li>
                ))}
              </ul>
            </section>

            <section id="retention">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                5. Data retention
              </h2>
              <p className="leading-relaxed">
                Retention depends on the record type, account status, operational needs, and legal
                obligations. We do not currently promise an automatic deletion deadline:
              </p>
              <ul className="mt-3 space-y-2">
                <li className="flex gap-3">
                  <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                  <span>
                    <strong className="text-foreground">Account data:</strong> Retained while the
                    account is active and as reasonably needed for security, dispute, and legal purposes.
                    Send a deletion request to the privacy address below; requests may require manual processing.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                  <span>
                    <strong className="text-foreground">Generated documents:</strong> Stored in your
                    account until removed through available controls or a verified deletion request.
                    Removal from the dashboard may not immediately remove backups, logs, or records
                    that must be retained for security or legal reasons.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                  <span>
                    <strong className="text-foreground">Transaction records:</strong> Retained as
                    reasonably needed for payment, accounting, fraud prevention, disputes, and
                    applicable legal obligations.
                  </span>
                </li>
              </ul>
            </section>

            <section id="security">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                6. Security
              </h2>
              <p className="leading-relaxed">
                We use technical and organisational safeguards intended to reduce unauthorised
                access, disclosure, alteration, or loss. Safeguards include account access controls
                and protections supplied by our hosting, database, email, and payment providers.
                We do not claim a security certification or audit that we have not completed.
              </p>
              <p className="mt-3 leading-relaxed">
                While we take these measures seriously, no method of transmission over the internet
                or electronic storage is 100% secure. We cannot guarantee absolute security, and
                you use our services at your own risk.
              </p>
            </section>

            <section id="rights">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                7. Your rights (GDPR &amp; CCPA)
              </h2>
              <p className="leading-relaxed">
                Depending on your location, you may have the following rights regarding your
                personal information:
              </p>

              <h3 className="mt-5 font-semibold text-foreground">For EU/EEA residents (GDPR)</h3>
              <ul className="mt-3 space-y-2">
                {[
                  "Right to access — request a copy of your personal data",
                  "Right to rectification — request correction of inaccurate data",
                  "Right to erasure — request deletion of your personal data (\"right to be forgotten\")",
                  "Right to restrict processing — request that we limit how we use your data",
                  "Right to data portability — receive your data in a structured, machine-readable format",
                  "Right to object — object to processing based on legitimate interests",
                  "Right to withdraw consent — where processing is based on consent",
                ].map((item) => (
                  <li key={item} className="flex gap-3">
                    <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>

              <h3 className="mt-5 font-semibold text-foreground">For California residents (CCPA)</h3>
              <ul className="mt-3 space-y-2">
                {[
                  "Right to know what personal information we collect, use, disclose, and sell",
                  "Right to delete personal information (with certain exceptions)",
                  "Right to opt-out of the sale of personal information (we do not sell personal information)",
                  "Right to non-discrimination for exercising your privacy rights",
                ].map((item) => (
                  <li key={item} className="flex gap-3">
                    <span className="flex-shrink-0 h-2 w-2 rounded-full bg-primary/60 mt-2" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>

              <p className="mt-5 leading-relaxed">
                To exercise any of these rights, contact us at{" "}
                <a
                  href="mailto:privacy@legallawdocs.com"
                  className="text-primary underline underline-offset-4 hover:text-primary/80"
                >
                  privacy@legallawdocs.com
                </a>
                . We will respond within the period required by applicable law.
              </p>
            </section>

            <section id="cookies">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                8. Cookies
              </h2>
              <p className="leading-relaxed">
                We use cookies and similar technologies to operate our website and services. For
                full details on what cookies we use and how to control them, please see our{" "}
                <Link href="/cookies" className="text-primary underline underline-offset-4 hover:text-primary/80">
                  Cookie Policy
                </Link>
                .
              </p>
            </section>

            <section id="children">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                9. Children&apos;s privacy
              </h2>
              <p className="leading-relaxed">
                Our services are not directed to individuals under 18 years of age. We do not
                knowingly collect personal information from children under 18. If we become aware
                that we have collected personal information from a child under 18, we will take
                steps to delete that information as quickly as possible. If you believe we have
                inadvertently collected such information, please contact us immediately.
              </p>
            </section>

            <section id="changes">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                10. Changes to this policy
              </h2>
              <p className="leading-relaxed">
                We may update this Privacy Policy from time to time. When we make material changes,
                we will notify you by email (if you have an account with us) and/or by posting
                a prominent notice on our website. The &ldquo;Last updated&rdquo; date at the top of this
                page indicates when this policy was last revised. Continued use of our services
                after any changes constitutes acceptance of the updated policy.
              </p>
            </section>

            <section id="contact">
              <h2 className="font-serif text-2xl font-bold text-foreground mb-4">
                11. Contact us
              </h2>
              <p className="leading-relaxed">
                For questions, requests, or concerns about this Privacy Policy or our privacy
                practices, please contact us:
              </p>
              <div className="mt-4 rounded-2xl border border-border/50 bg-card/60 p-5 text-sm space-y-1.5">
                <p className="font-semibold text-foreground">LegalLawDocs.com — Privacy Team</p>
                <p>
                  Email:{" "}
                  <a
                    href="mailto:privacy@legallawdocs.com"
                    className="text-primary underline underline-offset-4 hover:text-primary/80"
                  >
                    privacy@legallawdocs.com
                  </a>
                </p>
                <p>
                  Help Center:{" "}
                  <Link href="/help" className="text-primary underline underline-offset-4 hover:text-primary/80">
                    legallawdocs.com/help
                  </Link>
                </p>
              </div>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
