import { Header } from "@/components/header"
import { HeroSection } from "@/components/hero-section"
import { LogoCloud } from "@/components/logo-cloud"
import { StatsSection } from "@/components/stats-section"
import { FeaturesSection } from "@/components/features-section"
import { ComplianceBanner } from "@/components/compliance-banner"
import { DocumentsSection } from "@/components/documents-section"
import { HowItWorksSection } from "@/components/how-it-works-section"
import { TestimonialsSection } from "@/components/testimonials-section"
import { PricingSection } from "@/components/pricing-section"
import { FaqSection } from "@/components/faq-section"
import { CtaSection } from "@/components/cta-section"
import { Footer } from "@/components/footer"

const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "LegalLawDocs.com",
  url: "https://www.legallawdocs.com",
  logo: "https://www.legallawdocs.com/og-image.png",
  description:
    "AI-powered legal document generation platform with state-specific compliance across all 50 US states.",
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer service",
    url: "https://www.legallawdocs.com/contact",
  },
  sameAs: [],
}

const webSiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "LegalLawDocs.com",
  url: "https://www.legallawdocs.com",
  description:
    "Generate professional, legally compliant documents using advanced AI technology.",
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate:
        "https://www.legallawdocs.com/documents?search={search_term_string}",
    },
    "query-input": "required name=search_term_string",
  },
}

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "Are the documents generated by LegalLawDocs legally binding?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. Our documents are designed to be legally binding when properly executed. Each document is generated using templates drafted by licensed attorneys and reviewed for state-specific compliance.",
      },
    },
    {
      "@type": "Question",
      name: "How does state-specific compliance work?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "When you select your state during the document creation process, our AI engine automatically applies the relevant state laws, regulations, and formatting requirements to your document.",
      },
    },
    {
      "@type": "Question",
      name: "Can I edit the documents after they are generated?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Absolutely. All documents are delivered in editable formats (Word and PDF). You can make modifications as needed.",
      },
    },
    {
      "@type": "Question",
      name: "What types of documents can I create?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "We offer 50+ document templates spanning business, real estate, employment, and personal categories including NDAs, LLC agreements, lease agreements, employment contracts, wills, and more.",
      },
    },
    {
      "@type": "Question",
      name: "How is my data protected?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "We use 256-bit AES encryption for all data in transit and at rest. Our platform is SOC 2 Type II compliant, and we never share or sell your personal information.",
      },
    },
    {
      "@type": "Question",
      name: "Do you offer refunds?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. We offer a full refund within 7 days of purchase for Starter plan documents. Professional and Enterprise plans include a 14-day money-back guarantee.",
      },
    },
  ],
}

const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  serviceType: "Legal Document Generation",
  provider: {
    "@type": "Organization",
    name: "LegalLawDocs.com",
  },
  areaServed: {
    "@type": "Country",
    name: "United States",
  },
  description:
    "AI-powered legal document generation with state-specific compliance. Generate NDAs, LLC agreements, employment contracts, leases, and 50+ more document types.",
  offers: [
    {
      "@type": "Offer",
      name: "Starter",
      price: "9.00",
      priceCurrency: "USD",
      description:
        "Single document generation with state-specific compliance",
    },
    {
      "@type": "Offer",
      name: "Professional",
      price: "49.00",
      priceCurrency: "USD",
      description: "Unlimited document generation with all 50+ templates",
      priceSpecification: {
        "@type": "UnitPriceSpecification",
        price: "49.00",
        priceCurrency: "USD",
        billingDuration: "P1M",
      },
    },
  ],
}

export default function Page() {
  return (
    <div className="min-h-screen">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webSiteSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }}
      />
      <Header />
      <main>
        <HeroSection />
        <LogoCloud />
        <StatsSection />
        <FeaturesSection />
        <ComplianceBanner />
        <DocumentsSection />
        <HowItWorksSection />
        <TestimonialsSection />
        <PricingSection />
        <FaqSection />
        <CtaSection />
      </main>
      <Footer />
    </div>
  )
}
