import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const faqs = [
  {
    question: "Are the documents generated by LegalLawDocs legally binding?",
    answer:
      "Yes. Our documents are designed to be legally binding when properly executed. Each document is generated using templates drafted by licensed attorneys and reviewed for state-specific compliance. However, we always recommend consulting with a local attorney for complex or high-stakes legal matters.",
  },
  {
    question: "How does state-specific compliance work?",
    answer:
      "When you select your state during the document creation process, our AI engine automatically applies the relevant state laws, regulations, and formatting requirements to your document. Our legal database is continuously updated to reflect the latest legislative changes across all 50 states.",
  },
  {
    question: "Can I edit the documents after they are generated?",
    answer:
      "Absolutely. All documents are delivered in editable formats (Word and PDF). You can make modifications as needed. Professional and Enterprise plan users also have access to our built-in document editor with guided legal suggestions.",
  },
  {
    question: "What types of documents can I create?",
    answer:
      "We offer 50+ document templates spanning business (NDAs, LLC agreements, partnership agreements), real estate (lease agreements, purchase contracts), employment (contracts, offer letters, non-competes), and personal (wills, power of attorney, living trusts) categories.",
  },
  {
    question: "How is my data protected?",
    answer:
      "We use 256-bit AES encryption for all data in transit and at rest. Our platform is SOC 2 Type II compliant, and we never share or sell your personal information. All document data can be permanently deleted at your request.",
  },
  {
    question: "Do you offer refunds?",
    answer:
      "Yes. If you're not satisfied with a generated document, we offer a full refund within 7 days of purchase for Starter plan documents. Professional and Enterprise plans include a 14-day money-back guarantee.",
  },
]

export function FaqSection() {
  return (
    <section id="faq" className="relative py-24 lg:py-32">
      {/* Background */}
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute left-1/2 top-0 h-[400px] w-[600px] -translate-x-1/2 rounded-full bg-accent/3 blur-[120px]" />
      </div>

      <div className="relative mx-auto max-w-3xl px-4 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <p className="text-sm font-semibold uppercase tracking-widest text-primary">
            FAQ
          </p>
          <h2 className="mt-3 text-balance font-serif text-3xl font-bold text-foreground md:text-4xl lg:text-5xl">
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
          <p className="mt-5 text-pretty text-lg leading-relaxed text-muted-foreground">
            Everything you need to know about using LegalLawDocs for your legal
            document needs.
          </p>
        </div>

        <Accordion type="single" collapsible className="mt-14">
          {faqs.map((faq, index) => (
            <AccordionItem
              key={`faq-${index}`}
              value={`faq-${index}`}
              className="border-border/40 py-1"
            >
              <AccordionTrigger className="text-left font-semibold text-foreground transition-colors hover:text-primary hover:no-underline [&[data-state=open]]:text-primary">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="leading-relaxed text-muted-foreground">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  )
}
