import {
  FileText,
  Building2,
  Users,
  Briefcase,
  Home,
  Handshake,
  ScrollText,
  Scale,
  Mail,
  DollarSign,
  User,
  AlertCircle,
  Receipt,
  Car,
  FileSignature,
} from "lucide-react"

export type CategoryId =
  | "business"
  | "employment"
  | "real-estate"
  | "estate-planning"
  | "legal-letters"
  | "financial"
  | "personal"

export type MonetizationTier = "basic" | "high-value" | "premium"

export interface CatalogDocument {
  title: string
  /** New hyphenated slug — used in URL: /documents/[category]/[slug] */
  slug: string
  /** Old underscore slug — used as key in legacy libs during migration */
  legacySlug: string
  category: CategoryId
  icon: typeof FileText
  description: string
  longDescription: string
  popular: boolean
  color: "primary" | "accent"
  price: number
  subscriptionPrice: number
  keywords: string[]

  // ── Sprint 2: SEO enrichment fields ──────────────────────────────────────
  /** Slugs of related documents (same or cross-category) */
  relatedDocuments: string[]
  /** Slugs of related blog posts — populated as blog content is created */
  relatedBlogs: string[]
  /** Whether state-specific variants will be generated (e.g. california-nda) */
  stateEligible: boolean
  /** Whether city-specific variants make sense for this document type */
  cityEligible: boolean
  /** Whether international variants are planned */
  internationalEligible: boolean
  /** Practice areas for lawyer marketplace matching */
  practiceAreas: string[]
  /** Whether this page should show the lawyer listing block */
  lawyerListingEnabled: boolean
  /** Determines ad pricing tier in the lawyer marketplace */
  monetizationTier: MonetizationTier
  /** Suggested monthly listing price (USD) for lawyer advertisers */
  suggestedListingPrice: number
  /**
   * If this document is a standalone intent variant of another document,
   * set this to the parent document's slug (e.g. "non-disclosure-agreement").
   * Used to group variants on the parent page and for cross-linking.
   */
  parentSlug?: string
}

export const documentCatalog: CatalogDocument[] = [
  // ── BUSINESS ─────────────────────────────────────────────────────────────
  {
    title: "Non-Disclosure Agreement",
    slug: "non-disclosure-agreement",
    legacySlug: "nda",
    category: "business",
    icon: FileText,
    description: "Protect confidential information shared between parties.",
    longDescription:
      "A Non-Disclosure Agreement (NDA) legally binds parties to keep shared information confidential. Our AI tailors the agreement to mutual or one-way disclosure, specific industries, and your state's trade-secret statutes.",
    popular: true,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["nda", "non disclosure agreement", "confidentiality agreement", "nda template"],
    relatedDocuments: [
      "independent-contractor-agreement",
      "service-agreement",
      "employment-contract",
      "non-compete-agreement",
      "partnership-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["business-contracts", "intellectual-property", "startups"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 249,
  },
  {
    title: "LLC Operating Agreement",
    slug: "llc-operating-agreement",
    legacySlug: "llc_operating_agreement",
    category: "business",
    icon: Building2,
    description: "Define ownership structure and operating procedures for your LLC.",
    longDescription:
      "An LLC Operating Agreement establishes how your limited liability company is managed, how profits are split, and what happens when members join or leave. Required or strongly recommended in most states.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["llc operating agreement", "operating agreement", "llc agreement", "single member llc"],
    relatedDocuments: [
      "partnership-agreement",
      "non-disclosure-agreement",
      "service-agreement",
      "purchase-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-formation", "startups", "corporate-law"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 349,
  },
  {
    title: "Partnership Agreement",
    slug: "partnership-agreement",
    legacySlug: "partnership_agreement",
    category: "business",
    icon: Handshake,
    description: "Establish clear terms for business partnerships and profit sharing.",
    longDescription:
      "A Partnership Agreement defines each partner's contributions, rights, profit/loss allocation, and exit provisions. Prevent future disputes by getting the terms in writing from day one.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["partnership agreement", "business partnership contract", "partner agreement", "profit sharing agreement"],
    relatedDocuments: [
      "llc-operating-agreement",
      "non-disclosure-agreement",
      "service-agreement",
      "purchase-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["business-formation", "business-contracts", "corporate-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 299,
  },
  {
    title: "Service Agreement",
    slug: "service-agreement",
    legacySlug: "service_agreement",
    category: "business",
    icon: FileText,
    description: "Define terms for professional services and deliverables.",
    longDescription:
      "A Service Agreement sets the scope of work, fees, timelines, IP ownership, confidentiality, and termination terms between a service provider and their client. Works for fixed-fee or retainer engagements.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["service agreement", "professional services contract", "service contract", "retainer agreement"],
    relatedDocuments: [
      "non-disclosure-agreement",
      "independent-contractor-agreement",
      "purchase-agreement",
      "non-compete-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["business-contracts", "intellectual-property"],
    lawyerListingEnabled: true,
    monetizationTier: "basic",
    suggestedListingPrice: 149,
  },
  {
    title: "Purchase Agreement",
    slug: "purchase-agreement",
    legacySlug: "purchase_agreement",
    category: "business",
    icon: Handshake,
    description: "Structured purchase agreement drafts for goods and services.",
    longDescription:
      "A Purchase Agreement documents the sale of goods, assets, or services — including price, payment schedule, closing conditions, representations, and warranties. Essential for any significant transaction.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["purchase agreement", "sales agreement", "asset purchase agreement", "purchase contract"],
    relatedDocuments: [
      "service-agreement",
      "bill-of-sale",
      "payment-plan-agreement",
      "non-disclosure-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["business-contracts", "real-estate", "corporate-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 249,
  },

  {
    title: "Mutual Non-Disclosure Agreement",
    slug: "mutual-non-disclosure-agreement",
    legacySlug: "mutual_nda",
    category: "business",
    icon: FileText,
    description: "Protect confidential information shared in both directions between two parties.",
    longDescription:
      "A Mutual Non-Disclosure Agreement binds both parties to confidentiality obligations simultaneously — ideal for negotiations, joint ventures, and partnerships where each side is sharing sensitive information. Our AI tailors the agreement to your industry and state trade-secret statutes.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["mutual nda", "mutual non-disclosure agreement", "bilateral nda", "two-way nda", "mutual confidentiality agreement"],
    relatedDocuments: [
      "non-disclosure-agreement",
      "unilateral-non-disclosure-agreement",
      "independent-contractor-agreement",
      "service-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-contracts", "intellectual-property", "startups"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 249,
    parentSlug: "non-disclosure-agreement",
  },
  {
    title: "Unilateral Non-Disclosure Agreement",
    slug: "unilateral-non-disclosure-agreement",
    legacySlug: "unilateral_nda",
    category: "business",
    icon: FileText,
    description: "Protect confidential information flowing in one direction from discloser to recipient.",
    longDescription:
      "A Unilateral Non-Disclosure Agreement (one-way NDA) creates confidentiality obligations for only the receiving party. This is the appropriate choice when only one party is sharing sensitive business, technical, or financial information. Our AI handles industry-specific language and state compliance.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["unilateral nda", "one-way nda", "unilateral non-disclosure agreement", "one-sided nda", "unilateral confidentiality agreement"],
    relatedDocuments: [
      "non-disclosure-agreement",
      "mutual-non-disclosure-agreement",
      "service-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-contracts", "intellectual-property"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 199,
    parentSlug: "non-disclosure-agreement",
  },
  {
    title: "Single-Member LLC Operating Agreement",
    slug: "single-member-llc-operating-agreement",
    legacySlug: "single_member_llc",
    category: "business",
    icon: Building2,
    description: "Establish the operating rules for your one-owner LLC.",
    longDescription:
      "A Single-Member LLC Operating Agreement defines ownership, management authority, profit distributions, and dissolution procedures for a single-owner limited liability company. Essential for maintaining the liability shield and meeting banking, lending, and IRS requirements.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["single member llc operating agreement", "single member llc", "sole member llc", "one member llc agreement", "smllc operating agreement"],
    relatedDocuments: [
      "llc-operating-agreement",
      "multi-member-llc-operating-agreement",
      "partnership-agreement",
      "non-disclosure-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-contracts", "startups", "corporate-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 299,
    parentSlug: "llc-operating-agreement",
  },
  {
    title: "Multi-Member LLC Operating Agreement",
    slug: "multi-member-llc-operating-agreement",
    legacySlug: "multi_member_llc",
    category: "business",
    icon: Users,
    description: "Govern ownership, voting, and distributions for a multi-owner LLC.",
    longDescription:
      "A Multi-Member LLC Operating Agreement sets the rules for an LLC with two or more members — covering capital contributions, profit splits, voting rights, manager authority, and what happens when a member exits. Our AI customizes the agreement for member-managed or manager-managed structures.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["multi member llc operating agreement", "multi-member llc", "multiple member llc", "llc partnership agreement", "member managed llc agreement"],
    relatedDocuments: [
      "llc-operating-agreement",
      "single-member-llc-operating-agreement",
      "partnership-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-contracts", "corporate-law", "startups"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 349,
    parentSlug: "llc-operating-agreement",
  },

  // ── EMPLOYMENT ────────────────────────────────────────────────────────────
  {
    title: "At-Will Employment Contract",
    slug: "at-will-employment-contract",
    legacySlug: "at_will_employment_contract",
    category: "employment",
    icon: Briefcase,
    description: "Formalize at-will employment with clear compensation and policy terms.",
    longDescription:
      "An At-Will Employment Contract defines the at-will employment relationship along with role, compensation, benefits, and company policies — without creating a fixed term. Our AI tailors the agreement to your state's at-will exceptions and labor law requirements.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["at will employment contract", "at-will employment agreement", "at will employment letter", "at will job offer letter", "at will contract template"],
    relatedDocuments: [
      "employment-contract",
      "non-compete-agreement",
      "non-disclosure-agreement",
      "independent-contractor-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["employment-law", "business-contracts"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 249,
    parentSlug: "employment-contract",
  },
  {
    title: "Employment Contract",
    slug: "employment-contract",
    legacySlug: "employment_contract",
    category: "employment",
    icon: Briefcase,
    description: "Comprehensive employment agreements with state-specific provisions.",
    longDescription:
      "An Employment Contract clearly defines the role, compensation, benefits, start date, termination terms, and post-employment obligations. Our AI adjusts for at-will vs. fixed-term arrangements and your state's labor laws.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["employment contract", "employment agreement", "job contract", "at will employment"],
    relatedDocuments: [
      "non-disclosure-agreement",
      "non-compete-agreement",
      "independent-contractor-agreement",
      "demand-letter",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["employment-law", "labor-law", "business-contracts"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 249,
  },
  {
    title: "Independent Contractor Agreement",
    slug: "independent-contractor-agreement",
    legacySlug: "independent_contractor_agreement",
    category: "employment",
    icon: Users,
    description: "Define the terms of engagement with freelancers and contractors.",
    longDescription:
      "An Independent Contractor Agreement establishes the working relationship, scope of services, payment terms, IP ownership, and contractor status. Helps businesses avoid misclassification risk.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["independent contractor agreement", "contractor contract", "freelance agreement", "1099 agreement"],
    relatedDocuments: [
      "non-disclosure-agreement",
      "service-agreement",
      "non-compete-agreement",
      "employment-contract",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["employment-law", "business-contracts"],
    lawyerListingEnabled: true,
    monetizationTier: "basic",
    suggestedListingPrice: 149,
  },
  {
    title: "Non-Compete Agreement",
    slug: "non-compete-agreement",
    legacySlug: "non_compete_agreement",
    category: "employment",
    icon: Briefcase,
    description: "Protect your business with enforceable non-compete clauses.",
    longDescription:
      "A Non-Compete Agreement prevents employees or contractors from working with competitors for a defined period after leaving. Our AI flags state-specific enforceability limitations (e.g., California's near-total ban) so you know exactly where the agreement stands.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["non compete agreement", "noncompete contract", "restrictive covenant", "non compete template"],
    relatedDocuments: [
      "employment-contract",
      "non-disclosure-agreement",
      "independent-contractor-agreement",
      "service-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["employment-law", "business-contracts", "intellectual-property"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 249,
  },

  // ── REAL ESTATE ───────────────────────────────────────────────────────────
  {
    title: "Residential Lease Agreement",
    slug: "residential-lease-agreement",
    legacySlug: "residential_lease_agreement",
    category: "real-estate",
    icon: Home,
    description: "Lease agreement drafts with local tenant-law review prompts.",
    longDescription:
      "A Residential Lease Agreement sets rent, lease term, security deposit, maintenance responsibilities, and tenant/landlord rights. Our AI incorporates your state's mandatory disclosures and habitability standards.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["residential lease agreement", "rental agreement", "lease template", "tenant landlord agreement"],
    relatedDocuments: [
      "commercial-lease-agreement",
      "demand-letter",
      "notice-of-breach",
      "payment-plan-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: true,
    internationalEligible: true,
    practiceAreas: ["real-estate", "landlord-tenant", "property-management"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 349,
  },
  {
    title: "Commercial Lease Agreement",
    slug: "commercial-lease-agreement",
    legacySlug: "commercial_lease_agreement",
    category: "real-estate",
    icon: Building2,
    description: "Professional commercial property lease with full legal protections.",
    longDescription:
      "A Commercial Lease Agreement covers permitted use, rent schedule, CAM charges, lease improvements, insurance requirements, and default remedies. Structured for gross, net, or triple-net configurations.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["commercial lease agreement", "commercial lease", "business lease", "cam charges"],
    relatedDocuments: [
      "residential-lease-agreement",
      "purchase-agreement",
      "service-agreement",
      "demand-letter",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: true,
    internationalEligible: false,
    practiceAreas: ["real-estate", "business-contracts", "landlord-tenant"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 349,
  },

  {
    title: "Month-to-Month Lease Agreement",
    slug: "month-to-month-lease-agreement",
    legacySlug: "month_to_month_lease",
    category: "real-estate",
    icon: Home,
    description: "Flexible rental agreement that renews monthly with proper notice provisions.",
    longDescription:
      "A Month-to-Month Lease Agreement provides a flexible rental arrangement that automatically renews each month until either party provides proper notice. Our AI incorporates your state's required notice periods, rent increase rules, and mandatory tenant disclosures.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["month to month lease", "month-to-month rental agreement", "month to month lease agreement", "rolling lease agreement", "flexible lease template"],
    relatedDocuments: [
      "residential-lease-agreement",
      "landlord-notice-to-vacate",
      "demand-letter",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: true,
    internationalEligible: false,
    practiceAreas: ["landlord-tenant", "real-estate"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 349,
    parentSlug: "residential-lease-agreement",
  },
  {
    title: "Triple Net Lease Agreement",
    slug: "triple-net-lease-agreement",
    legacySlug: "triple_net_lease",
    category: "real-estate",
    icon: Building2,
    description: "Commercial lease where the tenant pays rent plus taxes, insurance, and maintenance.",
    longDescription:
      "A Triple Net (NNN) Lease Agreement shifts property taxes, building insurance, and maintenance costs to the tenant in addition to base rent. Our AI generates a properly structured NNN lease covering CAM reconciliations, landlord reserve rights, and cap provisions.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["triple net lease", "nnn lease", "triple net lease agreement", "nnn lease template", "triple net commercial lease"],
    relatedDocuments: [
      "commercial-lease-agreement",
      "service-agreement",
      "demand-letter",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: true,
    internationalEligible: false,
    practiceAreas: ["real-estate", "landlord-tenant", "business-contracts"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 349,
    parentSlug: "commercial-lease-agreement",
  },

  // ── ESTATE PLANNING ───────────────────────────────────────────────────────
  {
    title: "Power of Attorney",
    slug: "power-of-attorney",
    legacySlug: "power_of_attorney",
    category: "estate-planning",
    icon: ScrollText,
    description: "Authorize someone to act on your behalf in legal or financial matters.",
    longDescription:
      "A Power of Attorney grants a trusted agent authority to make legal, financial, or healthcare decisions on your behalf. Our AI tailors the scope (general, limited, or durable) and meets your state's notarization and witness requirements.",
    popular: true,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["power of attorney", "poa form", "durable power of attorney", "medical power of attorney"],
    relatedDocuments: [
      "last-will-and-testament",
      "general-release-of-liability",
      "affidavit",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["estate-planning", "elder-law", "probate"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 349,
  },
  {
    title: "Last Will & Testament",
    slug: "last-will-and-testament",
    legacySlug: "last_will_testament",
    category: "estate-planning",
    icon: Scale,
    description: "Prepare a state-aware will draft for licensed attorney review.",
    longDescription:
      "A Last Will & Testament specifies how your assets are distributed, who serves as executor, and (if applicable) who cares for minor children. Our AI ensures state-specific witness and signature requirements are met.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["last will and testament", "make a will", "online will", "will template", "estate planning document"],
    relatedDocuments: [
      "power-of-attorney",
      "affidavit",
      "general-release-of-liability",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["estate-planning", "probate", "elder-law"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 399,
  },

  {
    title: "Durable Power of Attorney",
    slug: "durable-power-of-attorney",
    legacySlug: "durable_power_of_attorney",
    category: "estate-planning",
    icon: ScrollText,
    description: "Grant an agent authority that remains effective even if you become incapacitated.",
    longDescription:
      "A Durable Power of Attorney grants a trusted agent authority over your financial and legal affairs that persists if you become incapacitated — making it a critical elder-planning document. Our AI meets your state's specific durability language, notarization, and witness requirements.",
    popular: true,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["durable power of attorney", "durable poa", "financial power of attorney", "durable power of attorney form", "durable poa template"],
    relatedDocuments: [
      "power-of-attorney",
      "medical-power-of-attorney",
      "last-will-and-testament",
      "affidavit",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["estate-planning", "elder-law", "probate"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 399,
    parentSlug: "power-of-attorney",
  },
  {
    title: "Medical Power of Attorney",
    slug: "medical-power-of-attorney",
    legacySlug: "medical_power_of_attorney",
    category: "estate-planning",
    icon: ScrollText,
    description: "Authorize a trusted person to make healthcare decisions on your behalf.",
    longDescription:
      "A Medical Power of Attorney (Healthcare Proxy) designates an agent to make medical decisions for you if you cannot communicate them yourself. Our AI incorporates your state's required statutory language, HIPAA authorization, and witness or notarization requirements.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["medical power of attorney", "healthcare power of attorney", "healthcare proxy", "medical poa", "health care directive"],
    relatedDocuments: [
      "power-of-attorney",
      "durable-power-of-attorney",
      "last-will-and-testament",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["estate-planning", "elder-law", "healthcare-law"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 399,
    parentSlug: "power-of-attorney",
  },

  // ── LEGAL LETTERS ─────────────────────────────────────────────────────────
  {
    title: "Demand Letter",
    slug: "demand-letter",
    legacySlug: "demand_letter",
    category: "legal-letters",
    icon: Mail,
    description: "Formally demand payment or action before legal proceedings.",
    longDescription:
      "A Demand Letter puts the other party on notice that you intend to pursue legal remedies if they do not fulfill an obligation. Our AI drafts clear, professional demand language that establishes a paper trail and demonstrates good-faith effort before litigation.",
    popular: true,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["demand letter", "demand letter template", "payment demand letter", "legal demand letter"],
    relatedDocuments: [
      "cease-and-desist-letter",
      "notice-of-breach",
      "payment-plan-agreement",
      "debt-settlement-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["litigation", "collections", "business-contracts", "landlord-tenant"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 199,
  },
  {
    title: "Cease and Desist Letter",
    slug: "cease-and-desist-letter",
    legacySlug: "cease_and_desist_letter",
    category: "legal-letters",
    icon: AlertCircle,
    description: "Order someone to stop harmful, infringing, or unlawful activity.",
    longDescription:
      "A Cease and Desist Letter formally demands that a person or entity stop a specific behavior — whether it's copyright infringement, defamation, harassment, or contract violation. Our AI generates firm, legally accurate language appropriate to your situation.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: [
      "cease and desist letter",
      "cease and desist template",
      "copyright infringement letter",
      "harassment cease and desist",
    ],
    relatedDocuments: [
      "demand-letter",
      "notice-of-breach",
      "complaint-letter",
      "non-disclosure-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["intellectual-property", "litigation", "employment-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 249,
  },
  {
    title: "Notice of Breach of Contract",
    slug: "notice-of-breach",
    legacySlug: "notice_of_breach",
    category: "legal-letters",
    icon: FileSignature,
    description: "Formally notify a party of their failure to perform contractual obligations.",
    longDescription:
      "A Notice of Breach of Contract formally informs the breaching party of the specific contractual obligations they have failed to meet, the timeline for cure, and the consequences of inaction. Serves as a critical paper-trail document before termination or litigation.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["notice of breach", "breach of contract letter", "contract default notice", "breach notice template"],
    relatedDocuments: [
      "demand-letter",
      "cease-and-desist-letter",
      "complaint-letter",
      "service-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["business-contracts", "litigation", "landlord-tenant"],
    lawyerListingEnabled: true,
    monetizationTier: "basic",
    suggestedListingPrice: 149,
  },
  {
    title: "Complaint Letter",
    slug: "complaint-letter",
    legacySlug: "complaint_letter",
    category: "legal-letters",
    icon: Mail,
    description: "Draft a formal complaint to a business, agency, or individual.",
    longDescription:
      "A Complaint Letter communicates dissatisfaction and requests a specific remedy — refund, correction, or action — from a company, government body, or individual. Our AI ensures your complaint is clear, factual, and professionally worded to maximize your chances of resolution.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["complaint letter", "formal complaint letter", "consumer complaint letter", "complaint template"],
    relatedDocuments: [
      "demand-letter",
      "cease-and-desist-letter",
      "notice-of-breach",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["consumer-protection", "litigation", "employment-law"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
  },
  {
    title: "Final Notice Before Legal Action",
    slug: "final-notice-before-legal-action",
    legacySlug: "final_notice_before_legal_action",
    category: "legal-letters",
    icon: AlertCircle,
    description: "Last written warning before filing a claim or lawsuit.",
    longDescription:
      "A Final Notice Before Legal Action is your last formal communication before escalating to court or a collection agency. It clearly states the amount owed or action required, the deadline to comply, and the specific legal remedies you intend to pursue.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["final notice letter", "pre-legal action notice", "last chance letter", "final demand letter"],
    relatedDocuments: [
      "demand-letter",
      "notice-of-breach",
      "debt-settlement-agreement",
      "payment-plan-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["collections", "litigation", "landlord-tenant"],
    lawyerListingEnabled: true,
    monetizationTier: "basic",
    suggestedListingPrice: 149,
  },
  {
    title: "Debt Settlement Letter",
    slug: "debt-settlement-letter",
    legacySlug: "debt_settlement_letter",
    category: "legal-letters",
    icon: DollarSign,
    description: "Negotiate and document a partial debt settlement agreement.",
    longDescription:
      "A Debt Settlement Letter proposes or confirms a reduced payoff amount to settle an outstanding debt in full. Our AI ensures the language protects you from future claims once the agreed amount is paid.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["debt settlement letter", "debt negotiation letter", "settle debt letter", "debt payoff letter"],
    relatedDocuments: [
      "demand-letter",
      "final-notice-before-legal-action",
      "debt-settlement-agreement",
      "payment-plan-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["collections", "consumer-protection", "banking-finance"],
    lawyerListingEnabled: true,
    monetizationTier: "basic",
    suggestedListingPrice: 149,
  },
  {
    title: "Landlord Notice to Vacate",
    slug: "landlord-notice-to-vacate",
    legacySlug: "landlord_notice_to_vacate",
    category: "legal-letters",
    icon: Home,
    description: "Formally notify a tenant to vacate the property by a specific date.",
    longDescription:
      "A Landlord Notice to Vacate formally informs a tenant that they must leave the property, whether due to lease expiration, non-payment, or lease violations. The AI assembles state-aware notice drafts with prompts to review notice periods and statutory language.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["notice to vacate", "eviction notice", "landlord notice", "tenant eviction letter"],
    relatedDocuments: [
      "residential-lease-agreement",
      "demand-letter",
      "notice-of-breach",
      "final-notice-before-legal-action",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: true,
    internationalEligible: false,
    practiceAreas: ["landlord-tenant", "real-estate", "litigation"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 199,
  },

  // ── FINANCIAL ─────────────────────────────────────────────────────────────
  {
    title: "Promissory Note",
    slug: "promissory-note",
    legacySlug: "promissory_note",
    category: "financial",
    icon: Receipt,
    description: "Document a loan with structured repayment terms for attorney review.",
    longDescription:
      "A Promissory Note is a written promise to repay a specific amount by a certain date or on demand. Our AI includes all required terms: principal, interest rate, payment schedule, late fees, and default provisions.",
    popular: true,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["promissory note", "promissory note template", "loan note", "ious legal document"],
    relatedDocuments: [
      "loan-agreement",
      "payment-plan-agreement",
      "debt-settlement-agreement",
      "bill-of-sale",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["banking-finance", "collections", "business-contracts"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 199,
  },
  {
    title: "Loan Agreement",
    slug: "loan-agreement",
    legacySlug: "loan_agreement",
    category: "financial",
    icon: DollarSign,
    description: "Formal agreement between lender and borrower with repayment terms.",
    longDescription:
      "A Loan Agreement is a comprehensive contract that specifies loan amount, interest rate, repayment schedule, collateral (if any), and consequences of default. More detailed than a promissory note and appropriate for larger loans.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["loan agreement", "personal loan agreement", "loan contract template", "private loan agreement"],
    relatedDocuments: [
      "promissory-note",
      "payment-plan-agreement",
      "debt-settlement-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["banking-finance", "business-contracts", "collections"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 249,
  },
  {
    title: "Payment Plan Agreement",
    slug: "payment-plan-agreement",
    legacySlug: "payment_plan_agreement",
    category: "financial",
    icon: Receipt,
    description: "Structure an installment payment schedule for a debt or purchase.",
    longDescription:
      "A Payment Plan Agreement allows a debtor and creditor to agree on a structured schedule for repaying a debt in installments. Includes payment dates, amounts, interest (if applicable), and default consequences.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["payment plan agreement", "installment agreement", "payment schedule template", "debt payment plan"],
    relatedDocuments: [
      "promissory-note",
      "loan-agreement",
      "debt-settlement-agreement",
      "demand-letter",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["collections", "consumer-protection", "banking-finance"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
  },
  {
    title: "Bill of Sale",
    slug: "bill-of-sale",
    legacySlug: "bill_of_sale",
    category: "financial",
    icon: FileText,
    description: "Transfer ownership of personal property with a legal record.",
    longDescription:
      "A Bill of Sale is a legal document that records the transfer of ownership of personal property — vehicles, equipment, goods — from seller to buyer. Includes item description, sale price, condition, and as-is clauses where applicable.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["bill of sale", "bill of sale template", "vehicle bill of sale", "personal property bill of sale"],
    relatedDocuments: [
      "purchase-agreement",
      "vehicle-bill-of-sale",
      "promissory-note",
      "payment-plan-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-contracts", "real-estate"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
  },
  {
    title: "Debt Settlement Agreement",
    slug: "debt-settlement-agreement",
    legacySlug: "debt_settlement_agreement",
    category: "financial",
    icon: DollarSign,
    description: "Formally settle a debt for less than the full amount owed.",
    longDescription:
      "A Debt Settlement Agreement is a binding contract between debtor and creditor that settles an outstanding debt for an agreed reduced sum. Protects both parties — the debtor from future claims, the creditor from a total loss.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: [
      "debt settlement agreement",
      "settle debt contract",
      "debt forgiveness agreement",
      "debt payoff agreement",
    ],
    relatedDocuments: [
      "promissory-note",
      "payment-plan-agreement",
      "debt-settlement-letter",
      "demand-letter",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["collections", "banking-finance", "consumer-protection"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 199,
  },

  // ── PERSONAL ──────────────────────────────────────────────────────────────
  {
    title: "Affidavit",
    slug: "affidavit",
    legacySlug: "affidavit",
    category: "personal",
    icon: FileSignature,
    description: "Sworn written statement of facts for legal proceedings.",
    longDescription:
      "An Affidavit is a sworn written statement used as evidence in legal proceedings, government applications, or business transactions. Our AI guides you through the required components: declarant identity, statement of facts, oath, and notarization block.",
    popular: true,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["affidavit", "affidavit template", "sworn statement", "affidavit of fact"],
    relatedDocuments: [
      "power-of-attorney",
      "general-release-of-liability",
      "last-will-and-testament",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["litigation", "estate-planning", "immigration"],
    lawyerListingEnabled: true,
    monetizationTier: "basic",
    suggestedListingPrice: 149,
  },
  {
    title: "General Release of Liability",
    slug: "general-release-of-liability",
    legacySlug: "general_release_of_liability",
    category: "personal",
    icon: FileText,
    description: "Waive your right to make future claims against another party.",
    longDescription:
      "A General Release of Liability waives a party's right to bring future claims arising from a specific event or agreement. Commonly used after settlements, accidents, or service transactions where one party agrees not to sue.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["release of liability", "liability waiver", "general release", "hold harmless agreement"],
    relatedDocuments: [
      "affidavit",
      "demand-letter",
      "service-agreement",
      "power-of-attorney",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["litigation", "business-contracts", "personal-injury"],
    lawyerListingEnabled: true,
    monetizationTier: "basic",
    suggestedListingPrice: 149,
  },
  {
    title: "Vehicle Bill of Sale",
    slug: "vehicle-bill-of-sale",
    legacySlug: "vehicle_bill_of_sale",
    category: "financial",
    icon: Car,
    description: "Transfer ownership of a vehicle with a legally valid sales record.",
    longDescription:
      "A Vehicle Bill of Sale records the private-party sale of a car, truck, motorcycle, or other vehicle. Our AI includes the required DMV-ready fields: VIN, odometer disclosure, sale price, condition acknowledgment, and as-is clause.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["vehicle bill of sale", "car bill of sale", "auto bill of sale", "dmv bill of sale"],
    relatedDocuments: [
      "bill-of-sale",
      "promissory-note",
      "general-release-of-liability",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["consumer-protection", "business-contracts"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
  },
  {
    title: "Personal Property Agreement",
    slug: "personal-property-agreement",
    legacySlug: "personal_property_agreement",
    category: "personal",
    icon: User,
    description: "Define ownership, use, or transfer terms for personal property.",
    longDescription:
      "A Personal Property Agreement documents the agreed terms between two parties regarding the use, custody, sharing, or transfer of personal property — furniture, electronics, valuables — without a formal sale. Useful for cohabitation, separation, or informal loans.",
    popular: false,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["personal property agreement", "property sharing agreement", "personal property contract"],
    relatedDocuments: [
      "bill-of-sale",
      "vehicle-bill-of-sale",
      "general-release-of-liability",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["consumer-protection", "family-law"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
  },

  // ── Business (4 new) ──────────────────────────────────────────────────────
  {
    title: "Employee Non-Disclosure Agreement",
    slug: "employee-non-disclosure-agreement",
    legacySlug: "employee_nda",
    category: "business",
    icon: FileText,
    description: "Protect company secrets when onboarding employees.",
    longDescription:
      "An Employee NDA (also called a confidentiality agreement) is signed by employees to prevent them from disclosing trade secrets, client lists, proprietary processes, and other confidential business information during and after employment. It is one of the most widely used business protection tools.",
    popular: true,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["employee nda", "employee confidentiality agreement", "employee non-disclosure agreement"],
    relatedDocuments: [
      "non-disclosure-agreement",
      "employment-contract",
      "non-compete-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["employment-law", "business-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
    parentSlug: "non-disclosure-agreement",
  },
  {
    title: "Asset Purchase Agreement",
    slug: "asset-purchase-agreement",
    legacySlug: "asset_purchase_agreement",
    category: "business",
    icon: Briefcase,
    description: "Document the sale of specific business assets between parties.",
    longDescription:
      "An Asset Purchase Agreement governs the sale of specific business assets — equipment, inventory, intellectual property, client lists, or goodwill — rather than the entire business entity. It clearly identifies what is being sold, the purchase price, representations by the seller, and any assumed liabilities.",
    popular: false,
    color: "primary",
    price: 29,
    subscriptionPrice: 14,
    keywords: ["asset purchase agreement", "business asset sale", "asset acquisition agreement"],
    relatedDocuments: [
      "purchase-agreement",
      "bill-of-sale",
      "non-disclosure-agreement",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-law", "mergers-acquisitions"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 249,
  },
  {
    title: "Master Service Agreement",
    slug: "master-service-agreement",
    legacySlug: "master_service_agreement",
    category: "business",
    icon: ScrollText,
    description: "Set standard terms for an ongoing business relationship.",
    longDescription:
      "A Master Service Agreement (MSA) establishes the overarching terms and conditions governing a long-term relationship between a service provider and a client. Individual project work orders or statements of work reference the MSA, avoiding the need to renegotiate core terms each engagement.",
    popular: false,
    color: "primary",
    price: 29,
    subscriptionPrice: 14,
    keywords: ["master service agreement", "msa contract", "master services agreement"],
    relatedDocuments: [
      "service-agreement",
      "independent-contractor-agreement",
      "non-disclosure-agreement",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: true,
    practiceAreas: ["business-law", "contract-law"],
    lawyerListingEnabled: true,
    monetizationTier: "premium",
    suggestedListingPrice: 249,
  },
  {
    title: "General Partnership Agreement",
    slug: "general-partnership-agreement",
    legacySlug: "general_partnership_agreement",
    category: "business",
    icon: Handshake,
    description: "Formalize a general partnership with equal management rights.",
    longDescription:
      "A General Partnership Agreement establishes the terms of a business partnership where all partners share management authority, profits, losses, and liability equally (or as specified). It covers capital contributions, profit/loss allocation, decision-making, partner withdrawal, and dissolution.",
    popular: false,
    color: "primary",
    price: 24,
    subscriptionPrice: 12,
    keywords: ["general partnership agreement", "partnership contract", "business partnership agreement"],
    relatedDocuments: [
      "partnership-agreement",
      "llc-operating-agreement",
      "non-disclosure-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-law", "contract-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
    parentSlug: "partnership-agreement",
  },

  // ── Employment (2 new) ────────────────────────────────────────────────────
  {
    title: "Fixed-Term Employment Contract",
    slug: "fixed-term-employment-contract",
    legacySlug: "fixed_term_employment_contract",
    category: "employment",
    icon: Briefcase,
    description: "Hire an employee for a defined period with a set end date.",
    longDescription:
      "A Fixed-Term Employment Contract defines a clear start and end date for an employment relationship. Common for seasonal workers, project-based roles, and contract positions, it sets compensation, duties, termination conditions, and what happens at the contract's expiration.",
    popular: false,
    color: "accent",
    price: 24,
    subscriptionPrice: 12,
    keywords: ["fixed term employment contract", "temporary employment contract", "term employment agreement"],
    relatedDocuments: [
      "employment-contract",
      "independent-contractor-agreement",
      "non-disclosure-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["employment-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
    parentSlug: "employment-contract",
  },
  {
    title: "1099 Contractor Agreement",
    slug: "1099-contractor-agreement",
    legacySlug: "1099_contractor_agreement",
    category: "employment",
    icon: FileSignature,
    description: "Engage independent contractors while protecting your IP and trade secrets.",
    longDescription:
      "A 1099 Contractor Agreement (also called an independent contractor agreement) documents the working relationship between a business and a self-employed contractor. It establishes contractor status (not employee), scope of services, payment terms, IP ownership, confidentiality, and termination rights — minimizing misclassification risk.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["1099 contractor agreement", "contractor agreement", "independent contractor contract"],
    relatedDocuments: [
      "independent-contractor-agreement",
      "non-disclosure-agreement",
      "service-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["employment-law", "business-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
    parentSlug: "independent-contractor-agreement",
  },

  // ── Real Estate (2 new) ───────────────────────────────────────────────────
  {
    title: "Room Rental Agreement",
    slug: "room-rental-agreement",
    legacySlug: "room_rental_agreement",
    category: "real-estate",
    icon: Home,
    description: "Rent a single room within a shared home or apartment.",
    longDescription:
      "A Room Rental Agreement documents the arrangement when a landlord or primary tenant rents a single room — rather than an entire unit — to a tenant. It covers rent, shared space rules, utilities, access, house rules, and termination notice requirements.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["room rental agreement", "room lease agreement", "room rental contract"],
    relatedDocuments: [
      "residential-lease-agreement",
      "month-to-month-lease-agreement",
      "sublease-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: true,
    internationalEligible: false,
    practiceAreas: ["real-estate-law", "landlord-tenant"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
    parentSlug: "residential-lease-agreement",
  },
  {
    title: "Sublease Agreement",
    slug: "sublease-agreement",
    legacySlug: "sublease_agreement",
    category: "real-estate",
    icon: Home,
    description: "Sublet all or part of a leased property to a subtenant.",
    longDescription:
      "A Sublease Agreement allows a current tenant (the sublessor) to rent their leased property — or a portion of it — to a new tenant (the sublessee) for a defined period. It outlines rent, the relationship between all parties, original lease obligations, and what happens if the sublessee defaults.",
    popular: false,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["sublease agreement", "sublet agreement", "subletting contract"],
    relatedDocuments: [
      "residential-lease-agreement",
      "room-rental-agreement",
      "month-to-month-lease-agreement",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: true,
    internationalEligible: false,
    practiceAreas: ["real-estate-law", "landlord-tenant"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
  },

  // ── Estate Planning (2 new) ───────────────────────────────────────────────
  {
    title: "Living Will",
    slug: "living-will",
    legacySlug: "living_will",
    category: "estate-planning",
    icon: ScrollText,
    description: "Specify your medical treatment wishes if you become incapacitated.",
    longDescription:
      "A Living Will (also called an advance directive or directive to physicians) is a legal document that records your wishes regarding life-sustaining medical treatment if you become unable to communicate. It provides guidance on resuscitation, artificial nutrition, ventilators, and organ donation.",
    popular: true,
    color: "accent",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["living will", "advance directive", "advance healthcare directive"],
    relatedDocuments: [
      "medical-power-of-attorney",
      "durable-power-of-attorney",
      "last-will-and-testament",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["estate-planning", "elder-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
  },
  {
    title: "Simple Will",
    slug: "simple-will",
    legacySlug: "simple_will",
    category: "estate-planning",
    icon: ScrollText,
    description: "Leave your assets to loved ones with a straightforward last will.",
    longDescription:
      "A Simple Will is a streamlined last will and testament suited for individuals with uncomplicated estates. It appoints an executor, names beneficiaries for property and assets, designates guardians for minor children if needed, and provides instructions for debt and tax payments.",
    popular: true,
    color: "accent",
    price: 24,
    subscriptionPrice: 12,
    keywords: ["simple will", "simple last will and testament", "basic will"],
    relatedDocuments: [
      "last-will-and-testament",
      "living-will",
      "durable-power-of-attorney",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["estate-planning"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
    parentSlug: "last-will-and-testament",
  },

  // ── Legal Letters (2 new) ─────────────────────────────────────────────────
  {
    title: "Demand Letter for Unpaid Invoice",
    slug: "demand-letter-for-unpaid-invoice",
    legacySlug: "demand_letter_unpaid_invoice",
    category: "legal-letters",
    icon: Mail,
    description: "Formally demand payment from a client or customer for an outstanding invoice.",
    longDescription:
      "A Demand Letter for Unpaid Invoice is a formal written notice sent to a debtor who has failed to pay an invoice. It states the amount owed, invoice reference, due date, a final payment deadline, and consequences of non-payment including potential legal action. It often prompts immediate payment without court involvement.",
    popular: true,
    color: "accent",
    price: 14,
    subscriptionPrice: 7,
    keywords: ["demand letter for unpaid invoice", "invoice demand letter", "unpaid invoice letter"],
    relatedDocuments: [
      "demand-letter",
      "final-notice-before-legal-action",
      "payment-plan-agreement",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["business-law", "collections"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
    parentSlug: "demand-letter",
  },
  {
    title: "Small Claims Demand Letter",
    slug: "small-claims-demand-letter",
    legacySlug: "small_claims_demand_letter",
    category: "legal-letters",
    icon: Scale,
    description: "Send a formal demand before filing in small claims court.",
    longDescription:
      "A Small Claims Demand Letter is sent before initiating a small claims court case. Many states require evidence that the plaintiff attempted to resolve the dispute before filing. This letter states the claim, the amount demanded, a resolution deadline, and notice of intent to file in small claims court.",
    popular: false,
    color: "accent",
    price: 14,
    subscriptionPrice: 7,
    keywords: ["small claims demand letter", "small claims letter", "pre-litigation demand letter"],
    relatedDocuments: [
      "demand-letter",
      "final-notice-before-legal-action",
      "complaint-letter",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["civil-litigation"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
    parentSlug: "demand-letter",
  },

  // ── Financial (2 new) ─────────────────────────────────────────────────────
  {
    title: "Secured Promissory Note",
    slug: "secured-promissory-note",
    legacySlug: "secured_promissory_note",
    category: "financial",
    icon: DollarSign,
    description: "Document a loan backed by collateral such as property or a vehicle.",
    longDescription:
      "A Secured Promissory Note is a written promise to repay a loan that is backed by specific collateral. If the borrower defaults, the lender has the right to seize the collateral. This note includes the principal, interest rate, repayment schedule, collateral description, and default remedies.",
    popular: false,
    color: "primary",
    price: 24,
    subscriptionPrice: 12,
    keywords: ["secured promissory note", "collateral promissory note", "secured loan note"],
    relatedDocuments: [
      "promissory-note",
      "loan-agreement",
      "bill-of-sale",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["banking-finance", "contract-law"],
    lawyerListingEnabled: true,
    monetizationTier: "high-value",
    suggestedListingPrice: 149,
    parentSlug: "promissory-note",
  },
  {
    title: "Personal Loan Agreement",
    slug: "personal-loan-agreement",
    legacySlug: "personal_loan_agreement",
    category: "financial",
    icon: Receipt,
    description: "Document a personal loan between friends, family, or individuals.",
    longDescription:
      "A Personal Loan Agreement formalizes a loan between two individuals — such as friends or family members. It records the loan amount, interest rate (if any), repayment schedule, and consequences of default, protecting both the lender and borrower and preventing disputes.",
    popular: true,
    color: "primary",
    price: 19,
    subscriptionPrice: 9,
    keywords: ["personal loan agreement", "family loan agreement", "friend loan agreement"],
    relatedDocuments: [
      "loan-agreement",
      "promissory-note",
      "payment-plan-agreement",
    ],
    relatedBlogs: [],
    stateEligible: false,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["banking-finance", "contract-law"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
    parentSlug: "loan-agreement",
  },

  // ── Personal (1 new) ──────────────────────────────────────────────────────
  {
    title: "General Affidavit",
    slug: "general-affidavit",
    legacySlug: "general_affidavit",
    category: "personal",
    icon: FileText,
    description: "Make a sworn statement of facts for legal or official purposes.",
    longDescription:
      "A General Affidavit is a sworn written statement of facts made under oath and signed before a notary public. It can be used for a wide variety of legal, financial, and personal purposes — including verifying identity, confirming a fact, or supporting a legal proceeding.",
    popular: false,
    color: "accent",
    price: 14,
    subscriptionPrice: 7,
    keywords: ["general affidavit", "sworn statement", "affidavit of fact"],
    relatedDocuments: [
      "affidavit",
      "general-release-of-liability",
      "power-of-attorney",
    ],
    relatedBlogs: [],
    stateEligible: true,
    cityEligible: false,
    internationalEligible: false,
    practiceAreas: ["civil-litigation", "family-law"],
    lawyerListingEnabled: false,
    monetizationTier: "basic",
    suggestedListingPrice: 99,
    parentSlug: "affidavit",
  },
]

// ── Lookup helpers ────────────────────────────────────────────────────────────

/** Look up by new hyphenated slug */
export function getDocumentBySlug(slug: string): CatalogDocument | undefined {
  return documentCatalog.find((doc) => doc.slug === slug)
}

/** Look up by legacy underscore slug (used by existing generate/prompt APIs) */
export function getDocumentByLegacySlug(legacySlug: string): CatalogDocument | undefined {
  return documentCatalog.find((doc) => doc.legacySlug === legacySlug)
}

/** All documents in a given category */
export function getDocumentsByCategory(category: CategoryId): CatalogDocument[] {
  return documentCatalog.filter((doc) => doc.category === category)
}

/** Resolve related documents from slug list */
export function getRelatedDocuments(slugs: string[]): CatalogDocument[] {
  return slugs
    .map((s) => getDocumentBySlug(s))
    .filter((d): d is CatalogDocument => d !== undefined)
}

/** The canonical URL path for a document: /documents/[category]/[slug] */
export function getDocumentPath(doc: CatalogDocument): string {
  return `/documents/${doc.category}/${doc.slug}`
}

/** Canonical absolute URL */
export function getDocumentCanonicalUrl(doc: CatalogDocument): string {
  return `https://legallawdocs.com/documents/${doc.category}/${doc.slug}`
}

/**
 * Returns all catalog documents whose parentSlug matches the given slug.
 * Used to render "standalone intent variant" links on a parent document page.
 */
export function getVariantDocuments(parentSlug: string): CatalogDocument[] {
  return documentCatalog.filter((d) => d.parentSlug === parentSlug)
}
