/**
 * Document-specific content helpers
 * Provides dynamic content based on document type
 */

export interface DocumentContent {
  included: string[]
  description: string
}

export const DOCUMENT_CONTENT: Record<string, DocumentContent> = {
  nda: {
    included: [
      "Definition of Confidential Information",
      "Obligations of Receiving Party",
      "Term & Duration Clauses",
      "Exclusions from Confidential Information",
      "Return of Materials Provision",
      "Remedies & Injunctive Relief",
      "Non-Compete / Non-Solicitation (where legal)",
      "Governing Law & Jurisdiction",
      "Digital Signature Block",
      "State-Aware Drafting Addendum",
    ],
    description: "Prepare a confidentiality agreement draft for the parties to review.",
  },
  employment_contract: {
    included: [
      "Job Title & Description",
      "Compensation & Benefits",
      "Employment Terms (at-will or fixed-term)",
      "Work Schedule & Location",
      "Non-Compete & Non-Solicitation Clauses",
      "Intellectual Property Assignment",
      "Termination Provisions",
      "Confidentiality Obligations",
      "Dispute Resolution",
      "State-Specific Employment Laws",
    ],
    description: "Comprehensive employment agreements with state-specific provisions and clear terms.",
  },
  residential_lease_agreement: {
    included: [
      "Property Description & Address",
      "Lease Term & Renewal Options",
      "Rent Amount & Payment Terms",
      "Security Deposit Provisions",
      "Tenant & Landlord Responsibilities",
      "Maintenance & Repair Clauses",
      "Pet & Smoking Policies",
      "Early Termination Terms",
      "State Tenant Protection Laws",
      "Move-in/Move-out Inspection",
    ],
    description: "Lease agreement drafts with local tenant-law questions and review notes.",
  },
  llc_operating_agreement: {
    included: [
      "Member Information & Ownership",
      "Capital Contributions",
      "Profit & Loss Distribution",
      "Management Structure",
      "Voting Rights & Procedures",
      "Transfer of Membership Interests",
      "Dissolution Procedures",
      "Dispute Resolution",
      "State LLC Compliance",
      "Tax Treatment Provisions",
    ],
    description: "Define ownership structure and operating procedures for your LLC.",
  },
  independent_contractor_agreement: {
    included: [
      "Services & Deliverables",
      "Payment Terms & Schedule",
      "Independent Contractor Status",
      "Intellectual Property Rights",
      "Confidentiality Provisions",
      "Term & Termination",
      "Non-Compete Clauses (if applicable)",
      "Dispute Resolution",
      "Tax Obligations",
      "State Contractor Laws",
    ],
    description: "Define the terms of engagement with freelancers and contractors.",
  },
  partnership_agreement: {
    included: [
      "Partnership Structure",
      "Capital Contributions",
      "Profit & Loss Sharing",
      "Management & Decision Making",
      "Partner Roles & Responsibilities",
      "Dispute Resolution",
      "Admission & Withdrawal of Partners",
      "Dissolution Procedures",
      "State Partnership Laws",
      "Tax Considerations",
    ],
    description: "Establish clear terms for business partnerships and profit sharing.",
  },
  power_of_attorney: {
    included: [
      "Principal & Agent Information",
      "Scope of Authority",
      "Financial Powers",
      "Healthcare Powers (if applicable)",
      "Durable vs Non-Durable",
      "Limitations & Restrictions",
      "Successor Agent Provisions",
      "State-Specific Requirements",
      "Witness & Notarization",
      "Revocation Procedures",
    ],
    description: "Authorize someone to act on your behalf in legal or financial matters.",
  },
  last_will_testament: {
    included: [
      "Testator Information",
      "Asset Distribution",
      "Beneficiary Designations",
      "Executor Appointment",
      "Guardianship Provisions (if applicable)",
      "Debt & Tax Handling",
      "Contingency Plans",
      "State Probate Laws",
      "Witness Requirements",
      "Revocation Clauses",
    ],
    description: "Prepare a state-aware will draft for licensed attorney review.",
  },
  commercial_lease_agreement: {
    included: [
      "Property Description & Use",
      "Lease Term & Options",
      "Base Rent & Additional Charges",
      "Common Area Maintenance (CAM)",
      "Tenant Improvements",
      "Assignment & Subletting",
      "Default & Remedies",
      "Insurance Requirements",
      "State Commercial Lease Laws",
      "Renewal & Termination",
    ],
    description: "Professional commercial property lease with full legal protections.",
  },
  service_agreement: {
    included: [
      "Service Description & Scope",
      "Payment Terms & Schedule",
      "Performance Standards",
      "Intellectual Property Rights",
      "Confidentiality Provisions",
      "Term & Termination",
      "Liability & Indemnification",
      "Dispute Resolution",
      "State Service Laws",
      "Force Majeure Clauses",
    ],
    description: "Define terms for professional services and deliverables.",
  },
  purchase_agreement: {
    included: [
      "Parties & Property Description",
      "Purchase Price & Payment Terms",
      "Closing Date & Conditions",
      "Inspection & Due Diligence",
      "Title & Title Insurance",
      "Default & Remedies",
      "Contingencies",
      "State Purchase Laws",
      "Warranties & Representations",
      "Closing Procedures",
    ],
    description: "Structured purchase agreement drafts for goods and services.",
  },
  non_compete_agreement: {
    included: [
      "Parties & Effective Date",
      "Geographic Restrictions",
      "Time Limitations",
      "Prohibited Activities",
      "Consideration Provisions",
      "Enforceability Clauses",
      "State-Aware Drafting Notes",
      "Remedies for Breach",
      "Severability Provisions",
      "Governing Law",
    ],
    description: "Protect your business with enforceable non-compete clauses.",
  },

  // ── Legal Letters ─────────────────────────────────────────────────────────
  demand_letter: {
    included: [
      "Sender & Recipient Identification",
      "Factual Background Statement",
      "Specific Obligation or Debt Claimed",
      "Demand for Action or Payment",
      "Response Deadline (10–30 days)",
      "Consequences of Non-Compliance",
      "Reference to Prior Communications",
      "Professional Tone & Formatting",
      "Digital Signature Block",
      "State-Aware Drafting Notes",
    ],
    description: "Formally demand payment or action before pursuing legal proceedings.",
  },
  cease_and_desist_letter: {
    included: [
      "Identification of Harmful Conduct",
      "Legal Basis for the Demand",
      "Specific Action Required to Cease",
      "Cure Deadline",
      "Damages & Remedies Statement",
      "Threat of Litigation if Ignored",
      "IP / Trademark Citations (if applicable)",
      "Professional Firm Language",
      "Digital Signature Block",
      "State Jurisdiction Reference",
    ],
    description: "Order someone to stop infringing, harmful, or unlawful conduct.",
  },
  notice_of_breach: {
    included: [
      "Contract Identification & Date",
      "Parties to the Agreement",
      "Specific Clause(s) Breached",
      "Description of the Breach",
      "Cure Period & Deadline",
      "Consequences of Failure to Cure",
      "Reservation of Rights",
      "Professional Tone & Formatting",
      "Digital Signature Block",
      "Governing Law Reference",
    ],
    description: "Formally notify a party of their failure to perform contractual obligations.",
  },
  complaint_letter: {
    included: [
      "Complainant & Respondent Details",
      "Factual Timeline of Events",
      "Description of Issue or Harm",
      "Specific Remedy Requested",
      "Supporting Evidence Summary",
      "Response Deadline",
      "Escalation Path Statement",
      "Professional Tone & Formatting",
      "Signature Block",
      "Contact Information",
    ],
    description: "Draft a formal complaint that maximizes your chance of a satisfactory resolution.",
  },
  final_notice_before_legal_action: {
    included: [
      "Full Amount Owed or Action Required",
      "Reference to All Prior Notices",
      "Clear Final Deadline",
      "Specific Legal Action to Be Filed",
      "Statement of No Further Notice",
      "Court or Agency to Be Approached",
      "Costs & Fees Warning",
      "Professional Tone & Formatting",
      "Digital Signature Block",
      "State Jurisdiction Reference",
    ],
    description: "Send a decisive last warning before escalating to court or collections.",
  },
  debt_settlement_letter: {
    included: [
      "Original Debt Amount & Account Reference",
      "Proposed Settlement Amount",
      "Acceptance Deadline",
      "Payment Instructions",
      "Full & Final Satisfaction Statement",
      "Tax Implication Notice (1099-C)",
      "Confidentiality Clause (optional)",
      "Professional Tone & Formatting",
      "Signature Block",
      "Governing Law Reference",
    ],
    description: "Negotiate and confirm a reduced debt payoff with clear legal protections.",
  },
  landlord_notice_to_vacate: {
    included: [
      "Property Address & Unit",
      "Tenant Name(s)",
      "Reason for Notice",
      "State-Required Notice Period",
      "Vacate-By Date",
      "Key Return Instructions",
      "Security Deposit Process",
      "State Statutory Language",
      "Grace Period Provisions (if applicable)",
      "Landlord Signature Block",
    ],
    description: "State-aware notice-to-vacate draft with notice-period and statutory-language review prompts.",
  },

  // ── Financial ─────────────────────────────────────────────────────────────
  promissory_note: {
    included: [
      "Lender & Borrower Names",
      "Principal Loan Amount",
      "Annual Interest Rate",
      "Payment Schedule & Due Dates",
      "Late Fee Provisions",
      "Default Definition & Remedies",
      "Secured or Unsecured Statement",
      "Prepayment Rights",
      "Governing Law",
      "Signature Block",
    ],
    description: "Document a loan with structured repayment terms for attorney review.",
  },
  loan_agreement: {
    included: [
      "Lender & Borrower Details",
      "Loan Amount & Disbursement Date",
      "Interest Rate (Fixed or Variable)",
      "Amortization Schedule",
      "Collateral Description (if secured)",
      "Representations & Warranties",
      "Events of Default",
      "Acceleration Clause",
      "Prepayment & Late Payment Terms",
      "Governing Law & Jurisdiction",
    ],
    description: "Comprehensive loan contract with full repayment terms and default provisions.",
  },
  payment_plan_agreement: {
    included: [
      "Creditor & Debtor Identification",
      "Total Amount Owed",
      "Installment Payment Amounts",
      "Payment Due Dates",
      "Accepted Payment Methods",
      "Interest or Service Fees (if any)",
      "Default & Acceleration Clause",
      "Final Balloon Payment (if applicable)",
      "Timely Payment Release Clause",
      "Governing Law",
    ],
    description: "Structure an installment payment schedule with clear terms and default consequences.",
  },
  bill_of_sale: {
    included: [
      "Seller & Buyer Details",
      "Complete Property Description",
      "Sale Price & Payment Method",
      "Date of Sale & Transfer",
      "Condition Disclosure (As-Is or Warranted)",
      "Title Transfer Statement",
      "Serial or VIN Number (if applicable)",
      "Warranty or Disclaimer",
      "Signatures of Both Parties",
      "State Registration Note",
    ],
    description: "Transfer ownership of personal property with a legally valid sales record.",
  },
  debt_settlement_agreement: {
    included: [
      "Creditor & Debtor Identification",
      "Original Debt Amount & Account Reference",
      "Agreed Settlement Amount",
      "Payment Date or Schedule",
      "Full & Final Release Clause",
      "No Further Claims Provision",
      "Tax Implications Notice (IRS 1099-C)",
      "Confidentiality Clause",
      "Default Consequences",
      "Governing Law & Jurisdiction",
    ],
    description: "Formally settle a debt for less than the full amount owed with mutual release of claims.",
  },

  // ── Personal ─────────────────────────────────────────────────────────────
  affidavit: {
    included: [
      "Declarant Identity & Address",
      "Jurisdiction & Case Caption (if applicable)",
      "Numbered Factual Statements",
      "Personal Knowledge Affirmation",
      "Oath & Affirmation Clause",
      "Truth Under Penalty of Perjury",
      "Signature Block",
      "Notarization Block",
      "Witness Signature Lines (if required)",
      "Date of Execution",
    ],
    description: "Sworn written statement of facts for use in legal proceedings or official applications.",
  },
  general_release_of_liability: {
    included: [
      "Releasor & Releasee Identification",
      "Scope of Events or Transactions Covered",
      "Claims Released (Known & Unknown)",
      "Section 1542 Waiver (California)",
      "Consideration Paid",
      "Voluntary Execution Statement",
      "Indemnification Clause",
      "Severability Provision",
      "Governing Law",
      "Signature Block",
    ],
    description: "Waive your right to future claims with a comprehensive liability release.",
  },
  vehicle_bill_of_sale: {
    included: [
      "Seller & Buyer Details",
      "Vehicle Year, Make, Model, VIN",
      "Odometer Reading & Disclosure",
      "License Plate Number",
      "Sale Price & Payment Method",
      "As-Is Condition Statement",
      "Federal MVIC Odometer Compliance",
      "Title Transfer Statement",
      "State DMV Registration Notes",
      "Signatures of Both Parties",
    ],
    description: "DMV-ready vehicle sale record with VIN, odometer disclosure, and all required fields.",
  },
  personal_property_agreement: {
    included: [
      "Both Parties' Identification",
      "Detailed Property Description",
      "Nature of Arrangement (Use, Custody, or Transfer)",
      "Duration & Return Terms",
      "Maintenance & Damage Responsibilities",
      "Compensation (if any)",
      "Default & Breach Consequences",
      "Dispute Resolution",
      "Modification & Termination",
      "Signature Block",
    ],
    description: "Define ownership, use, or transfer terms for personal property between two parties.",
  },

  // ── Tier 1 Standalone Intent Documents ────────────────────────────────────
  mutual_nda: {
    included: [
      "Mutual Confidentiality Obligations (Both Directions)",
      "Definition of Confidential Information",
      "Permitted Use Restrictions",
      "Exclusions from Confidential Information",
      "Return or Destruction of Materials",
      "Term & Duration Clauses",
      "Remedies & Injunctive Relief",
      "Non-Solicitation Clause (optional)",
      "Governing Law & Jurisdiction",
      "Digital Signature Block for Both Parties",
    ],
    description: "Protect confidential information flowing in both directions with a bilateral NDA.",
  },
  unilateral_nda: {
    included: [
      "Disclosing & Receiving Party Identification",
      "Definition of Confidential Information",
      "One-Way Confidentiality Obligation",
      "Permitted Use Restrictions",
      "Exclusions from Confidential Information",
      "Return or Destruction of Materials",
      "Term & Duration Clauses",
      "Remedies & Injunctive Relief",
      "Governing Law & Jurisdiction",
      "Digital Signature Block",
    ],
    description: "Protect information you share with vendors, partners, or employees under a one-way NDA.",
  },
  single_member_llc: {
    included: [
      "Sole Member Identification",
      "LLC Name, State, and Registered Agent",
      "Capital Contribution & Ownership",
      "Management Authority & Powers",
      "Profit & Distribution Rules",
      "Bank Account & Tax Treatment",
      "Succession & Transfer Restrictions",
      "Dissolution Procedures",
      "State LLC Compliance Provisions",
      "Effective Date & Signature Block",
    ],
    description: "Establish governance, liability protection, and operating rules for your one-owner LLC.",
  },
  multi_member_llc: {
    included: [
      "All Member Names, Addresses & Ownership %",
      "Capital Contributions Table",
      "Profit & Loss Allocation",
      "Management Structure (Member vs. Manager-Managed)",
      "Voting Rights & Quorum Requirements",
      "Transfer & Right of First Refusal",
      "Member Withdrawal & Buyout Provisions",
      "Admission of New Members",
      "Dissolution & Winding Up",
      "State LLC Compliance Provisions",
    ],
    description: "Define ownership, governance, and distribution rules for a multi-owner LLC.",
  },
  durable_power_of_attorney: {
    included: [
      "Principal & Agent Identification",
      "Durability Language (Survives Incapacity)",
      "Financial & Property Powers",
      "Banking & Investment Authority",
      "Real Estate Transaction Authority",
      "Gifting & Estate Planning Powers (optional)",
      "Limitations & Restrictions",
      "Successor Agent Designation",
      "State-Specific Durability Clause",
      "Witness & Notarization Block",
    ],
    description: "Grant an agent comprehensive financial authority that remains effective even if you become incapacitated.",
  },
  medical_power_of_attorney: {
    included: [
      "Principal & Healthcare Agent Identification",
      "Scope of Healthcare Decision Authority",
      "HIPAA Authorization Clause",
      "Treatment Preferences & Limitations",
      "Life-Sustaining Treatment Instructions",
      "Organ Donation Preferences",
      "Mental Health Treatment Authority (if applicable)",
      "Successor Agent Designation",
      "State Statutory Language & Requirements",
      "Witness & Notarization Block",
    ],
    description: "Designate a trusted person to make medical decisions on your behalf if you cannot.",
  },
  month_to_month_lease: {
    included: [
      "Landlord & Tenant Identification",
      "Property Address & Unit Description",
      "Monthly Rent Amount & Due Date",
      "Security Deposit Terms",
      "Notice Period Requirements (Confirm Current Law)",
      "Rent Increase Notification Requirements",
      "Tenant Maintenance Responsibilities",
      "Pet, Smoking & Guest Policies",
      "State Tenant Protection Provisions",
      "Signature Block & Effective Date",
    ],
    description: "Flexible month-to-month rental agreement with proper notice provisions and state compliance.",
  },
  at_will_employment_contract: {
    included: [
      "At-Will Employment Statement",
      "Job Title, Duties & Reporting Structure",
      "Compensation, Salary & Pay Schedule",
      "Benefits & PTO Summary",
      "Start Date & Work Location",
      "Confidentiality & IP Assignment",
      "Non-Compete / Non-Solicitation (if applicable)",
      "Termination Procedures",
      "State-Specific At-Will Exceptions",
      "Digital Signature Block",
    ],
    description: "Prepare an at-will employment draft with clear compensation, policies, and state-aware review notes.",
  },
  triple_net_lease: {
    included: [
      "Landlord & Tenant Identification",
      "Property Description & Permitted Use",
      "Base Rent & Escalation Schedule",
      "Tenant NNN Obligations (Taxes, Insurance, Maintenance)",
      "CAM Charge Reconciliation",
      "Landlord Expense Cap Provisions",
      "Tenant Improvement Allowance",
      "Assignment & Subletting Rights",
      "Default & Remedies",
      "Renewal Options & Right of First Refusal",
    ],
    description: "Professional triple net commercial lease transferring taxes, insurance, and maintenance to the tenant.",
  },

  // ── New catalog documents ─────────────────────────────────────────────────
  employee_nda: {
    included: [
      "Employee & Employer Identification",
      "Broad Definition of Confidential Information",
      "Confidentiality Obligations During & After Employment",
      "Trade Secret Protections",
      "IP Assignment Clause",
      "Non-Disparagement Provision",
      "Return of Company Materials",
      "Remedies Including Injunctive Relief",
      "Governing Law & Jurisdiction",
    ],
    description: "Protect your business secrets and IP when onboarding new employees.",
  },
  asset_purchase_agreement: {
    included: [
      "Seller & Buyer Identification",
      "Complete Asset Schedule (Equipment, IP, Inventory)",
      "Purchase Price & Payment Terms",
      "Asset Allocation Statement (IRS Form 8594)",
      "Representations & Warranties by Seller",
      "Assumed vs. Excluded Liabilities",
      "Closing Conditions & Date",
      "Bill of Sale Provisions",
      "Transition Assistance Terms",
      "Indemnification Clause",
    ],
    description: "Document a business asset sale with clear allocation, warranties, and liability protections.",
  },
  master_service_agreement: {
    included: [
      "Party Identification & Relationship",
      "Services Framework (SOW/Work Order References)",
      "Fees, Invoicing & Payment Terms",
      "IP Ownership & License Grants",
      "Confidentiality Obligations",
      "Limitation of Liability",
      "Indemnification",
      "Insurance Requirements",
      "Term, Termination & Survival",
      "Governing Law & Integration Clause",
    ],
    description: "Establish overarching commercial terms for an ongoing service relationship.",
  },
  general_partnership_agreement: {
    included: [
      "Partnership Name & Purpose",
      "List of General Partners",
      "Capital Contributions",
      "Profit & Loss Sharing",
      "Management & Voting Rights",
      "Partner Drawing Accounts",
      "Admission of New Partners",
      "Partner Withdrawal & Buyout",
      "Non-Compete During Partnership",
      "Dissolution Procedures",
    ],
    description: "Formalize a general partnership with equal management rights and shared liability.",
  },
  fixed_term_employment_contract: {
    included: [
      "Fixed Start & End Date",
      "Job Title & Duties",
      "Compensation & Benefits",
      "Work Location (Remote/In-Person/Hybrid)",
      "PTO & Leave Policy",
      "Early Termination Provisions",
      "Renewal or Extension Options",
      "Confidentiality & IP Assignment",
      "Dispute Resolution",
      "Governing Law",
    ],
    description: "Hire for a defined period with clear term dates, compensation, and termination rights.",
  },
  "1099_contractor_agreement": {
    included: [
      "Independent Contractor Status Clause",
      "Scope of Services Description",
      "Hourly Rate or Project Fee",
      "Invoicing & Payment Schedule",
      "IP Work-for-Hire Assignment",
      "Confidentiality Obligations",
      "Non-Solicitation Provision",
      "No Benefits or Tax Withholding Statement",
      "Termination Rights",
      "Insurance Requirements",
    ],
    description: "Engage 1099 contractors with clear IP assignment, confidentiality, and status protections.",
  },
  room_rental_agreement: {
    included: [
      "Property Address & Room Description",
      "Landlord & Tenant Identification",
      "Monthly Rent & Due Date",
      "Security Deposit Terms",
      "Shared Space Rules",
      "Utility Allocation",
      "Noise, Guest & Pet Policies",
      "Entry Notice Requirements",
      "Termination Notice Period",
      "State-Required Disclosures",
    ],
    description: "Rent a single room in a shared home with clear rules for shared spaces and termination.",
  },
  sublease_agreement: {
    included: [
      "Sublessor & Sublessee Identification",
      "Property Address & Subleased Portion",
      "Sublease Term & Rent",
      "Landlord Consent Acknowledgment",
      "Original Lease Compliance Obligations",
      "Security Deposit Terms",
      "Sublessee Rules & Restrictions",
      "Sublessor's Residual Liability",
      "Termination Provisions",
      "Default & Remedies",
    ],
    description: "Sublet your leased property while protecting your obligations to the original landlord.",
  },
  living_will: {
    included: [
      "Declarant Identification & Statement of Capacity",
      "CPR & Resuscitation Directives",
      "Mechanical Ventilation Preferences",
      "Artificial Nutrition & Hydration Wishes",
      "Dialysis & Other Life-Sustaining Treatment",
      "Comfort Care & Pain Management Instructions",
      "Organ & Tissue Donation Preferences",
      "HIPAA Authorization",
      "State-Required Statutory Language",
      "Notarization & Witness Block",
    ],
    description: "Record your medical treatment wishes in advance so loved ones and doctors know your preferences.",
  },
  simple_will: {
    included: [
      "Testator Identification & Domicile",
      "Revocation of Prior Wills",
      "Executor & Alternate Executor Appointment",
      "Specific Asset Distributions",
      "Residuary Beneficiary Designation",
      "Guardian for Minor Children (if applicable)",
      "Debt & Tax Payment Instructions",
      "No-Contest Clause",
      "Attestation Clause",
      "Witness Signature Block",
    ],
    description: "Leave your assets to loved ones with a clear, straightforward will for uncomplicated estates.",
  },
  demand_letter_unpaid_invoice: {
    included: [
      "Sender & Recipient Identification",
      "Invoice Number(s) & Date(s)",
      "Amount Owed & Original Due Date",
      "Reference to Prior Payment Requests",
      "Final Payment Deadline",
      "Accepted Payment Methods",
      "Consequences of Non-Payment",
      "Legal Action Warning",
      "Attorney's Fees Notice",
      "Professional Closing",
    ],
    description: "Send a firm, professional demand for payment of an outstanding invoice before taking legal action.",
  },
  small_claims_demand_letter: {
    included: [
      "Claimant & Respondent Identification",
      "Factual Description of Dispute",
      "Dollar Amount Claimed",
      "Legal or Contractual Basis",
      "Final Resolution Deadline",
      "Small Claims Court Notice",
      "State Court Filing Reference",
      "Prior Communication References",
      "No Further Notice Statement",
      "Professional Closing",
    ],
    description: "Document your pre-litigation demand before filing in small claims court.",
  },
  secured_promissory_note: {
    included: [
      "Lender & Borrower Identification",
      "Principal Loan Amount",
      "Interest Rate (Fixed or Variable)",
      "Repayment Schedule & Maturity Date",
      "Collateral Description & Security Interest Grant",
      "UCC or Real Property Security Reference",
      "Late Fee Provisions",
      "Default Definition & Cure Period",
      "Lender's Right to Seize Collateral",
      "Governing Law",
    ],
    description: "Document a secured loan with clear collateral terms and lender rights upon default.",
  },
  personal_loan_agreement: {
    included: [
      "Lender & Borrower Identification",
      "Loan Amount & Disbursement Date",
      "Interest Rate (or 0% Interest Statement)",
      "Repayment Schedule",
      "Late Payment Provisions",
      "Default Consequences",
      "Death of Lender Provisions",
      "Consideration Clause",
      "Entire Agreement Statement",
      "Signature Block",
    ],
    description: "Protect both parties when lending money to friends or family with a clear written agreement.",
  },
  general_affidavit: {
    included: [
      "Affiant Full Name & Address",
      "State & County Caption",
      "Numbered Factual Statements",
      "First-Person, Personal-Knowledge Statements",
      "Oath / Affirmation Clause",
      "Penalty of Perjury Statement",
      "Affiant Signature Block",
      "Notary Public Acknowledgment",
      "Notary Seal Space",
      "Date of Execution",
    ],
    description: "Make a sworn statement of facts under oath for legal, financial, or personal purposes.",
  },
}

/**
 * Get content for a document by slug
 */
export function getDocumentContent(slug: string): DocumentContent {
  return DOCUMENT_CONTENT[slug] || {
    included: [
      "State-specific legal compliance",
      "Professional formatting",
      "All required legal sections",
      "Customized clauses based on your needs",
      "Digital signature ready",
      "PDF & DOCX formats",
    ],
    description: "Generate a structured document draft from your answers for professional review.",
  }
}
