/**
 * Document-specific content helpers
 * Provides dynamic content based on document type
 */

export interface DocumentContent {
  included: string[]
  description: string
}

export const DOCUMENT_CONTENT: Record<string, DocumentContent> = {
  nda: {
    included: [
      "Definition of Confidential Information",
      "Obligations of Receiving Party",
      "Term & Duration Clauses",
      "Exclusions from Confidential Information",
      "Return of Materials Provision",
      "Remedies & Injunctive Relief",
      "Non-Compete / Non-Solicitation (where legal)",
      "Governing Law & Jurisdiction",
      "Digital Signature Block",
      "State-Specific Compliance Addendum",
    ],
    description: "Protect confidential information shared between parties with a legally binding agreement.",
  },
  employment_contract: {
    included: [
      "Job Title & Description",
      "Compensation & Benefits",
      "Employment Terms (at-will or fixed-term)",
      "Work Schedule & Location",
      "Non-Compete & Non-Solicitation Clauses",
      "Intellectual Property Assignment",
      "Termination Provisions",
      "Confidentiality Obligations",
      "Dispute Resolution",
      "State-Specific Employment Laws",
    ],
    description: "Comprehensive employment agreements with state-specific provisions and clear terms.",
  },
  residential_lease_agreement: {
    included: [
      "Property Description & Address",
      "Lease Term & Renewal Options",
      "Rent Amount & Payment Terms",
      "Security Deposit Provisions",
      "Tenant & Landlord Responsibilities",
      "Maintenance & Repair Clauses",
      "Pet & Smoking Policies",
      "Early Termination Terms",
      "State Tenant Protection Laws",
      "Move-in/Move-out Inspection",
    ],
    description: "Legally binding lease agreements compliant with local tenant laws and regulations.",
  },
  llc_operating_agreement: {
    included: [
      "Member Information & Ownership",
      "Capital Contributions",
      "Profit & Loss Distribution",
      "Management Structure",
      "Voting Rights & Procedures",
      "Transfer of Membership Interests",
      "Dissolution Procedures",
      "Dispute Resolution",
      "State LLC Compliance",
      "Tax Treatment Provisions",
    ],
    description: "Define ownership structure and operating procedures for your LLC.",
  },
  independent_contractor_agreement: {
    included: [
      "Services & Deliverables",
      "Payment Terms & Schedule",
      "Independent Contractor Status",
      "Intellectual Property Rights",
      "Confidentiality Provisions",
      "Term & Termination",
      "Non-Compete Clauses (if applicable)",
      "Dispute Resolution",
      "Tax Obligations",
      "State Contractor Laws",
    ],
    description: "Define the terms of engagement with freelancers and contractors.",
  },
  partnership_agreement: {
    included: [
      "Partnership Structure",
      "Capital Contributions",
      "Profit & Loss Sharing",
      "Management & Decision Making",
      "Partner Roles & Responsibilities",
      "Dispute Resolution",
      "Admission & Withdrawal of Partners",
      "Dissolution Procedures",
      "State Partnership Laws",
      "Tax Considerations",
    ],
    description: "Establish clear terms for business partnerships and profit sharing.",
  },
  power_of_attorney: {
    included: [
      "Principal & Agent Information",
      "Scope of Authority",
      "Financial Powers",
      "Healthcare Powers (if applicable)",
      "Durable vs Non-Durable",
      "Limitations & Restrictions",
      "Successor Agent Provisions",
      "State-Specific Requirements",
      "Witness & Notarization",
      "Revocation Procedures",
    ],
    description: "Authorize someone to act on your behalf in legal or financial matters.",
  },
  last_will_testament: {
    included: [
      "Testator Information",
      "Asset Distribution",
      "Beneficiary Designations",
      "Executor Appointment",
      "Guardianship Provisions (if applicable)",
      "Debt & Tax Handling",
      "Contingency Plans",
      "State Probate Laws",
      "Witness Requirements",
      "Revocation Clauses",
    ],
    description: "Protect your legacy with a state-compliant will document.",
  },
  commercial_lease_agreement: {
    included: [
      "Property Description & Use",
      "Lease Term & Options",
      "Base Rent & Additional Charges",
      "Common Area Maintenance (CAM)",
      "Tenant Improvements",
      "Assignment & Subletting",
      "Default & Remedies",
      "Insurance Requirements",
      "State Commercial Lease Laws",
      "Renewal & Termination",
    ],
    description: "Professional commercial property lease with full legal protections.",
  },
  service_agreement: {
    included: [
      "Service Description & Scope",
      "Payment Terms & Schedule",
      "Performance Standards",
      "Intellectual Property Rights",
      "Confidentiality Provisions",
      "Term & Termination",
      "Liability & Indemnification",
      "Dispute Resolution",
      "State Service Laws",
      "Force Majeure Clauses",
    ],
    description: "Define terms for professional services and deliverables.",
  },
  purchase_agreement: {
    included: [
      "Parties & Property Description",
      "Purchase Price & Payment Terms",
      "Closing Date & Conditions",
      "Inspection & Due Diligence",
      "Title & Title Insurance",
      "Default & Remedies",
      "Contingencies",
      "State Purchase Laws",
      "Warranties & Representations",
      "Closing Procedures",
    ],
    description: "Legally binding purchase agreements for goods and services.",
  },
  non_compete_agreement: {
    included: [
      "Parties & Effective Date",
      "Geographic Restrictions",
      "Time Limitations",
      "Prohibited Activities",
      "Consideration Provisions",
      "Enforceability Clauses",
      "State-Specific Compliance",
      "Remedies for Breach",
      "Severability Provisions",
      "Governing Law",
    ],
    description: "Protect your business with enforceable non-compete clauses.",
  },

  // ── Legal Letters ─────────────────────────────────────────────────────────
  demand_letter: {
    included: [
      "Sender & Recipient Identification",
      "Factual Background Statement",
      "Specific Obligation or Debt Claimed",
      "Demand for Action or Payment",
      "Response Deadline (10–30 days)",
      "Consequences of Non-Compliance",
      "Reference to Prior Communications",
      "Professional Tone & Formatting",
      "Digital Signature Block",
      "State-Specific Compliance",
    ],
    description: "Formally demand payment or action before pursuing legal proceedings.",
  },
  cease_and_desist_letter: {
    included: [
      "Identification of Harmful Conduct",
      "Legal Basis for the Demand",
      "Specific Action Required to Cease",
      "Cure Deadline",
      "Damages & Remedies Statement",
      "Threat of Litigation if Ignored",
      "IP / Trademark Citations (if applicable)",
      "Professional Firm Language",
      "Digital Signature Block",
      "State Jurisdiction Reference",
    ],
    description: "Order someone to stop infringing, harmful, or unlawful conduct.",
  },
  notice_of_breach: {
    included: [
      "Contract Identification & Date",
      "Parties to the Agreement",
      "Specific Clause(s) Breached",
      "Description of the Breach",
      "Cure Period & Deadline",
      "Consequences of Failure to Cure",
      "Reservation of Rights",
      "Professional Tone & Formatting",
      "Digital Signature Block",
      "Governing Law Reference",
    ],
    description: "Formally notify a party of their failure to perform contractual obligations.",
  },
  complaint_letter: {
    included: [
      "Complainant & Respondent Details",
      "Factual Timeline of Events",
      "Description of Issue or Harm",
      "Specific Remedy Requested",
      "Supporting Evidence Summary",
      "Response Deadline",
      "Escalation Path Statement",
      "Professional Tone & Formatting",
      "Signature Block",
      "Contact Information",
    ],
    description: "Draft a formal complaint that maximizes your chance of a satisfactory resolution.",
  },
  final_notice_before_legal_action: {
    included: [
      "Full Amount Owed or Action Required",
      "Reference to All Prior Notices",
      "Clear Final Deadline",
      "Specific Legal Action to Be Filed",
      "Statement of No Further Notice",
      "Court or Agency to Be Approached",
      "Costs & Fees Warning",
      "Professional Tone & Formatting",
      "Digital Signature Block",
      "State Jurisdiction Reference",
    ],
    description: "Send a decisive last warning before escalating to court or collections.",
  },
  debt_settlement_letter: {
    included: [
      "Original Debt Amount & Account Reference",
      "Proposed Settlement Amount",
      "Acceptance Deadline",
      "Payment Instructions",
      "Full & Final Satisfaction Statement",
      "Tax Implication Notice (1099-C)",
      "Confidentiality Clause (optional)",
      "Professional Tone & Formatting",
      "Signature Block",
      "Governing Law Reference",
    ],
    description: "Negotiate and confirm a reduced debt payoff with clear legal protections.",
  },
  landlord_notice_to_vacate: {
    included: [
      "Property Address & Unit",
      "Tenant Name(s)",
      "Reason for Notice",
      "State-Required Notice Period",
      "Vacate-By Date",
      "Key Return Instructions",
      "Security Deposit Process",
      "State Statutory Language",
      "Grace Period Provisions (if applicable)",
      "Landlord Signature Block",
    ],
    description: "State-compliant notice to vacate with correct notice periods and statutory language.",
  },

  // ── Financial ─────────────────────────────────────────────────────────────
  promissory_note: {
    included: [
      "Lender & Borrower Names",
      "Principal Loan Amount",
      "Annual Interest Rate",
      "Payment Schedule & Due Dates",
      "Late Fee Provisions",
      "Default Definition & Remedies",
      "Secured or Unsecured Statement",
      "Prepayment Rights",
      "Governing Law",
      "Signature Block",
    ],
    description: "Document a loan with a legally binding promise to repay.",
  },
  loan_agreement: {
    included: [
      "Lender & Borrower Details",
      "Loan Amount & Disbursement Date",
      "Interest Rate (Fixed or Variable)",
      "Amortization Schedule",
      "Collateral Description (if secured)",
      "Representations & Warranties",
      "Events of Default",
      "Acceleration Clause",
      "Prepayment & Late Payment Terms",
      "Governing Law & Jurisdiction",
    ],
    description: "Comprehensive loan contract with full repayment terms and default provisions.",
  },
  payment_plan_agreement: {
    included: [
      "Creditor & Debtor Identification",
      "Total Amount Owed",
      "Installment Payment Amounts",
      "Payment Due Dates",
      "Accepted Payment Methods",
      "Interest or Service Fees (if any)",
      "Default & Acceleration Clause",
      "Final Balloon Payment (if applicable)",
      "Timely Payment Release Clause",
      "Governing Law",
    ],
    description: "Structure an installment payment schedule with clear terms and default consequences.",
  },
  bill_of_sale: {
    included: [
      "Seller & Buyer Details",
      "Complete Property Description",
      "Sale Price & Payment Method",
      "Date of Sale & Transfer",
      "Condition Disclosure (As-Is or Warranted)",
      "Title Transfer Statement",
      "Serial or VIN Number (if applicable)",
      "Warranty or Disclaimer",
      "Signatures of Both Parties",
      "State Registration Note",
    ],
    description: "Transfer ownership of personal property with a legally valid sales record.",
  },
  debt_settlement_agreement: {
    included: [
      "Creditor & Debtor Identification",
      "Original Debt Amount & Account Reference",
      "Agreed Settlement Amount",
      "Payment Date or Schedule",
      "Full & Final Release Clause",
      "No Further Claims Provision",
      "Tax Implications Notice (IRS 1099-C)",
      "Confidentiality Clause",
      "Default Consequences",
      "Governing Law & Jurisdiction",
    ],
    description: "Formally settle a debt for less than the full amount owed with mutual release of claims.",
  },

  // ── Personal ─────────────────────────────────────────────────────────────
  affidavit: {
    included: [
      "Declarant Identity & Address",
      "Jurisdiction & Case Caption (if applicable)",
      "Numbered Factual Statements",
      "Personal Knowledge Affirmation",
      "Oath & Affirmation Clause",
      "Truth Under Penalty of Perjury",
      "Signature Block",
      "Notarization Block",
      "Witness Signature Lines (if required)",
      "Date of Execution",
    ],
    description: "Sworn written statement of facts for use in legal proceedings or official applications.",
  },
  general_release_of_liability: {
    included: [
      "Releasor & Releasee Identification",
      "Scope of Events or Transactions Covered",
      "Claims Released (Known & Unknown)",
      "Section 1542 Waiver (California)",
      "Consideration Paid",
      "Voluntary Execution Statement",
      "Indemnification Clause",
      "Severability Provision",
      "Governing Law",
      "Signature Block",
    ],
    description: "Waive your right to future claims with a comprehensive liability release.",
  },
  vehicle_bill_of_sale: {
    included: [
      "Seller & Buyer Details",
      "Vehicle Year, Make, Model, VIN",
      "Odometer Reading & Disclosure",
      "License Plate Number",
      "Sale Price & Payment Method",
      "As-Is Condition Statement",
      "Federal MVIC Odometer Compliance",
      "Title Transfer Statement",
      "State DMV Registration Notes",
      "Signatures of Both Parties",
    ],
    description: "DMV-ready vehicle sale record with VIN, odometer disclosure, and all required fields.",
  },
  personal_property_agreement: {
    included: [
      "Both Parties' Identification",
      "Detailed Property Description",
      "Nature of Arrangement (Use, Custody, or Transfer)",
      "Duration & Return Terms",
      "Maintenance & Damage Responsibilities",
      "Compensation (if any)",
      "Default & Breach Consequences",
      "Dispute Resolution",
      "Modification & Termination",
      "Signature Block",
    ],
    description: "Define ownership, use, or transfer terms for personal property between two parties.",
  },
}

/**
 * Get content for a document by slug
 */
export function getDocumentContent(slug: string): DocumentContent {
  return DOCUMENT_CONTENT[slug] || {
    included: [
      "State-specific legal compliance",
      "Professional formatting",
      "All required legal sections",
      "Customized clauses based on your needs",
      "Digital signature ready",
      "PDF & DOCX formats",
    ],
    description: "Generate a professional, legally binding document tailored to your specific needs.",
  }
}
