import { IntentBodyContent } from "./intent-body-content"

export const GROUP_A3: Record<string, IntentBodyContent> = {

  service_agreement_fixed_fee: {
    overview: [
      "A fixed-fee service agreement establishes a predetermined total price for a defined scope of services, giving both the client and service provider cost certainty before work begins. Unlike hourly or time-and-materials arrangements, fixed-fee contracts shift the pricing risk to the service provider—if the work takes longer or costs more than anticipated, the provider absorbs the difference. This risk allocation makes accurate scope definition the most critical element of a fixed-fee agreement: the more precisely the scope is defined at the outset, the more reliably the provider can price the engagement and the fewer disputes arise over what is included.",
      "Fixed-fee contracts appeal to clients because they eliminate billing uncertainty and allow budget planning with confidence. For service providers, fixed fees offer the opportunity to profit from efficiency—completing the work faster than estimated means the effective hourly rate increases. However, scope creep is the fixed-fee provider's primary financial risk: clients who incrementally expand the scope beyond the original agreement while continuing to expect the original price can quickly erode or eliminate the provider's margin. Effective fixed-fee agreements address this risk through precise scope language, explicit exclusions, and a formal written change order process that prices additional work separately.",
      "The payment structure in a fixed-fee service agreement typically follows one of two models. The first is a simple two-payment structure: a deposit paid at contract execution (commonly twenty-five to fifty percent) and the balance due upon completion. The second is a milestone payment structure, particularly useful for longer engagements, where defined percentages of the total fee are paid upon completion of specific project phases. Milestone payments reduce cash flow risk for both parties—the provider receives compensation for completed work even if the engagement is terminated before full completion, and the client has natural review points at which to assess progress before releasing the next payment.",
      "Liability limitation is a standard and legally significant element of fixed-fee service agreements. Service providers typically limit their total liability for claims arising from the engagement to the amount of fees paid under the agreement. Without this limitation, a service provider who makes a mistake on a relatively small engagement could face liability vastly disproportionate to the economic value of the contract. Clients sometimes resist liability caps, arguing they need meaningful recourse for consequential losses. The negotiated outcome often involves a cap set at total fees plus the provider's insurance coverage limit, with carve-outs for gross negligence, willful misconduct, and indemnification obligations.",
    ],
    howItWorks: [
      { step: "Define the Scope of Services with Precision", description: "Draft the scope as a list of specific services, deliverables, and activities included in the fixed fee. Attach any relevant specifications, plans, or functional requirements as exhibits. Include an explicit exclusions section listing services that are not covered—travel expenses, third-party licensing fees, regulatory filings, after-hours work—to prevent disputes about what the fee covers." },
      { step: "Set the Fixed Fee and Payment Terms", description: "State the total fixed fee amount, the deposit due at execution, and the remaining payment schedule. Specify the invoice submission timing, payment due dates after invoice receipt, and the late payment interest rate. For milestone-based payments, attach a payment schedule exhibit showing the percentage due at each milestone and the milestone completion criteria." },
      { step: "Establish the Change Order Process", description: "Require all scope changes to be documented in a written change order executed by both parties before any out-of-scope work begins. The change order must specify the additional services, the additional fee, and any timeline impact. Prohibit verbal authorizations for out-of-scope work and state that the service provider is not obligated to perform changes until a signed change order is in place." },
      { step: "Define the Acceptance and Completion Criteria", description: "Specify what constitutes completion of the services—delivery of defined outputs, passage of defined tests, or sign-off by a designated client representative. Establish a client review period after delivery during which objections must be submitted in writing. Define the remedy for non-conforming deliverables: the provider will cure identified deficiencies within a specified period at no additional charge." },
      { step: "Include Standard Protective Clauses", description: "Add confidentiality obligations covering all client information accessed during the engagement, intellectual property assignment or license terms appropriate to the service type, limitation of liability capped at fees paid, and mutual indemnification for claims arising from each party's own negligence or breach. Include governing law, venue, and dispute resolution provisions appropriate to the parties' locations." },
    ],
    legalConsiderations: [
      { title: "Scope Definition as Legal Protection", body: "A vague scope of services is not merely a business problem—it is a legal vulnerability. Courts resolving fixed-fee contract disputes look at the contract language to determine what was promised and whether the provider delivered. Scope language that relies on general descriptions ('a comprehensive marketing plan' or 'a fully functional website') without specifics invites the court to infer what 'comprehensive' or 'fully functional' means, often in the client's favor." },
      { title: "Deposit Enforceability", body: "Fixed-fee contracts typically include a non-refundable deposit that compensates the provider for reserved capacity and preparation work. Deposit enforceability depends on the deposit being a reasonable pre-estimate of damages (a genuine liquidated damages clause) rather than an unenforceable penalty. Document the business rationale for the deposit amount—turning down other work, purchasing materials, allocating team time—to support enforceability if the client disputes the non-refundable nature." },
      { title: "Consequential Damages Waiver", body: "Service providers routinely include waivers of consequential, indirect, and punitive damages in fixed-fee service agreements. These waivers prevent clients from claiming business interruption losses, lost profits, or reputational harm as damages from a service breach. Courts generally enforce mutual consequential damages waivers in commercial contracts, but they must be conspicuous in the agreement (often in capitalized bold text) to be enforceable in some states." },
      { title: "Delivery Deadline vs. Time Is of the Essence", body: "Including a 'time is of the essence' clause means that failure to deliver by the specified date is a material breach permitting the client to terminate the contract immediately without providing a cure period. For most fixed-fee service agreements, a milder provision requiring the provider to use commercially reasonable efforts to meet the timeline—with cure rights for delays—is more appropriate and less risky for the provider." },
    ],
    commonMistakes: [
      { mistake: "Pricing Without a Full Scope Definition", fix: "Providing a fixed-fee quote before the scope is fully defined almost always results in under-pricing. Take the time to develop a detailed scope document before committing to a price. If the scope is genuinely uncertain, perform a paid scoping phase first, then quote the implementation phase based on the scoping document." },
      { mistake: "Not Including a Change Order Multiplier", fix: "Out-of-scope work performed under a change order should be priced at a higher rate than the implicit rate embedded in the fixed fee, because change orders are typically smaller, less efficient engagements than planned work. Build a change order rate schedule into the agreement—commonly ten to fifteen percent above standard rates—to compensate for the planning and context-switching cost of out-of-scope work." },
      { mistake: "Failing to Get Client Sign-Off on Deliverables", fix: "Without documented client acceptance, the provider cannot definitively establish that the work was completed and approved. Require written acceptance—email acknowledgment or signed acceptance form—for each significant deliverable, particularly those that trigger a milestone payment. Specify that silence after the review period constitutes acceptance to prevent clients from withholding acceptance indefinitely." },
      { mistake: "Setting Payment Due on 'Project Completion' Without Defining Completion", fix: "If final payment is due on 'completion' and completion is undefined, clients can withhold final payment by claiming the project is not 'complete' despite meeting all specified criteria. Define completion with objective criteria tied to specific deliverables, test passage, or client sign-off with a defined review period after which acceptance is implied." },
      { mistake: "Using Generic Templates Without Service-Specific Terms", fix: "Generic fixed-fee contracts miss the specific risks of the service type—a construction agreement needs mechanics lien and insurance provisions; a marketing agreement needs FTC compliance and ad account ownership terms; a software agreement needs IP assignment and dependency disclosure terms. Start with a service-specific template rather than adapting a generic service contract." },
    ],
    extendedFaq: [
      { question: "What happens if my fixed-fee project takes longer than expected?", answer: "In a properly structured fixed-fee contract, the provider absorbs the cost of overruns caused by their own under-estimation or inefficiency. If the overrun is caused by the client—late feedback, expanded requirements, failure to provide agreed inputs—the provider can assert that the client's conduct constitutes a change to the scope and price the additional time as a change order. Document all client-caused delays carefully to support this position." },
      { question: "Can I get a refund on my deposit if I cancel the project early?", answer: "Whether a deposit is refundable depends on the contract language. Non-refundable deposit clauses are generally enforceable in commercial contracts when the deposit represents a reasonable estimate of the provider's damages for early cancellation—including reserved capacity, materials purchased, and work completed. If the provider has done no work at all and the deposit is disproportionate to actual damages, some courts may limit the amount the provider can retain." },
      { question: "How is a fixed-fee contract different from a not-to-exceed contract?", answer: "A fixed-fee contract means the price is exactly what is stated—no more, no less—regardless of actual time and materials. A not-to-exceed (NTE) contract means the price will not exceed a defined maximum, but may be less if the work requires less time or fewer materials (typically used with time-and-materials billing). Fixed-fee contracts are appropriate when the scope is well-defined; NTE contracts work better for engagements where the scope may vary but the client needs a budget ceiling." },
      { question: "What should I do if the service provider refuses to complete the project without additional payment?", answer: "A refusal to complete agreed fixed-fee work without additional payment is a breach of contract. You should first review the agreement to confirm the disputed work is within the original scope (not a legitimate change order item). Then send a written notice of breach identifying the specific unfulfilled obligations and providing a reasonable cure period. If the provider does not cure within the specified period, you may be entitled to terminate the contract and engage a replacement provider, with the original provider potentially liable for the cost difference." },
    ],
  },

  service_agreement_freelance: {
    overview: [
      "A freelance service agreement governs an independent working relationship between a self-employed creative, technical, or professional service provider and a client who engages them for defined deliverables or ongoing services. The term 'freelance' encompasses an enormous range of engagements—from a one-time graphic design project to a recurring content writing arrangement—and the agreement must be tailored to the specific nature of the work. What all freelance agreements share is the need to clearly establish deliverables, compensation terms, intellectual property ownership, and the independent nature of the relationship in a way that protects both the freelancer's right to get paid and the client's right to receive what they contracted for.",
      "Freelancers occupy a distinctive position in the labor market that creates specific legal vulnerabilities. Unlike employees who benefit from wage payment protections, workers' compensation, and employer-provided benefits, freelancers must negotiate their own payment terms, manage their own tax obligations, and bear the cost of professional liability insurance. Non-payment and late payment are the most common problems freelancers face, and the agreement must address these realities directly: a clear payment schedule, late payment penalties, and the right to suspend work for non-payment all protect the freelancer from the most common financial risks of the working relationship.",
      "The scope of work in a freelance agreement must be specific enough to define what the freelancer is obligated to deliver and what the client is entitled to receive. Vague scope descriptions—'web content as needed' or 'design support for the brand'—create ongoing disputes about what falls within the engagement and how much work constitutes adequate performance for the agreed compensation. Effective freelance agreements define deliverables with sufficient specificity to let both parties recognize when the scope is complete, while including a mechanism for expanding or adjusting the scope through a formal amendment or change order process rather than informal verbal requests.",
      "Freelancer rights legislation has emerged in several jurisdictions as a significant new dimension of freelance service agreements. New York City's Freelance Isn't Free Act and similar laws in other jurisdictions require clients to provide freelancers with written contracts for engagements above a defined dollar threshold, mandate payment within specified timeframes, and impose significant civil penalties for non-payment. California's AB5 and related statutes impose strict worker classification tests that affect how freelance relationships must be structured to avoid reclassification as employment. Freelancers and clients operating in jurisdictions with freelancer protection laws must ensure their agreements comply with applicable requirements, including mandatory payment timing and required contract elements.",
    ],
    howItWorks: [
      { step: "Define Services and Deliverables", description: "List each service or deliverable specifically, including format, quantity, turnaround time, and quality standards. For recurring arrangements, describe the deliverable cadence—weekly articles of 1,000 words, monthly social media calendars—and the submission process. Avoid open-ended descriptions that imply unlimited revisions or undefined scope." },
      { step: "Set Rates, Payment Terms, and Late Fees", description: "State the fee per deliverable, hourly rate, or monthly retainer clearly. Specify the invoicing schedule—upon delivery, monthly, or bi-weekly—and the payment due period (net seven, net fifteen, net thirty). Include a late payment interest clause (typically one to one-and-a-half percent per month) and the right to suspend services for non-payment after a defined grace period." },
      { step: "Establish Revision and Feedback Terms", description: "Define the number of revision rounds included in the quoted fee and the process for requesting them. Specify the turnaround time for client feedback and whether delayed feedback extends the freelancer's deadline proportionally. Describe the additional rate for revisions beyond the included rounds or for work outside the original scope." },
      { step: "Address Intellectual Property Ownership", description: "Specify who owns deliverables after payment—typically the client receives an assignment upon full payment. If the freelancer uses pre-existing creative elements, tools, or templates, carve those out from the assignment and grant the client a license to use them as incorporated in the deliverables. Include portfolio display rights if the freelancer wants to showcase the work." },
      { step: "Include Termination and Kill Fee Provisions", description: "Give both parties a right to terminate with reasonable written notice (typically fourteen to thirty days). If the client terminates mid-project after work has begun, include a kill fee provision—a percentage of the remaining contract value the client pays for the disruption and reserved capacity that goes unused. Specify what work product the client receives upon early termination." },
    ],
    legalConsiderations: [
      { title: "Freelance Isn't Free Act Compliance", body: "New York City's Freelance Isn't Free Act requires written contracts for freelance engagements of $800 or more (in a single contract or series of contracts within 120 days), mandates payment within thirty days of completion or by the contract date, and allows freelancers to recover double damages plus attorney fees for non-payment. Similar laws have been enacted in other cities and states. Verify whether your jurisdiction's freelancer protection law applies to your engagement and ensure the contract meets all required elements." },
      { title: "Worker Classification Under the ABC Test", body: "California's ABC test presumes all workers are employees unless the hiring party can demonstrate that the worker is free from control, performs work outside the ordinary course of the client's business, and is customarily engaged in an independently established trade or occupation. Freelancers who work exclusively for one client on work central to that client's business may be reclassified as employees under this test, with significant consequences for both parties." },
      { title: "1099-NEC Reporting Obligations", body: "Clients who pay a freelancer $600 or more in a calendar year must issue a Form 1099-NEC by January 31 of the following year. The freelance service agreement should include the freelancer's taxpayer identification number, a representation that they are operating as a self-employed individual responsible for their own taxes, and a backup withholding provision for clients who fail to provide a TIN. Failure to issue required 1099s subjects clients to IRS penalties." },
      { title: "Governing Law and Jurisdiction for Cross-Jurisdictional Freelance", body: "Remote freelance relationships often span multiple states or countries. The governing law clause designates which jurisdiction's law applies to the contract, and the venue clause specifies where disputes will be litigated. For freelancers, a venue clause requiring disputes to be resolved in the client's jurisdiction imposes significant travel and cost burdens. Negotiate for the freelancer's jurisdiction or a neutral dispute resolution method such as online arbitration." },
    ],
    commonMistakes: [
      { mistake: "Starting Work Without a Signed Contract", fix: "Beginning work based on an email exchange or verbal agreement leaves the freelancer with no documented protection if payment is withheld. Require a signed agreement and, for new clients, a deposit before any work begins. Many freelancers send a professional contract and request a deposit as a standard onboarding step that sets the tone for a professional relationship." },
      { mistake: "Not Specifying a Kill Fee", fix: "Clients who cancel mid-project after work has begun deprive the freelancer of the expected revenue and the opportunity to take other work during the reserved period. A kill fee—typically twenty-five to fifty percent of remaining contract value—compensates the freelancer for this disruption and discourages casual cancellation. Ensure the kill fee is framed as a genuine pre-estimate of damages, not a penalty." },
      { mistake: "Including Unlimited Revision Rounds", fix: "Agreeing to revisions 'until the client is satisfied' eliminates the freelancer's ability to set a completion boundary. Cap revision rounds at two or three, require written feedback, and specify that revision requests delivered more than thirty days after delivery are treated as new work orders rather than revisions within the original scope." },
      { mistake: "Failing to Include a Work Suspension Right", fix: "Without the right to pause services for non-payment, the freelancer must either continue working without compensation or unilaterally breach the contract. Include an explicit right to suspend services after payment is more than a defined number of days overdue, with work resuming only upon payment of overdue amounts plus a resumption fee." },
      { mistake: "Using Client-Provided Templates Without Review", fix: "Clients sometimes send their own service agreement template that is heavily one-sided in the client's favor—broad IP assignment, unlimited revisions, no kill fee, venue in the client's jurisdiction. Review any client-provided agreement carefully against your standard terms before signing, and negotiate changes to provisions that disproportionately burden the freelancer." },
    ],
    extendedFaq: [
      { question: "What is a kill fee and how much should I charge?", answer: "A kill fee is compensation paid by the client to the freelancer when the client cancels the project after work has begun. It covers the freelancer's lost opportunity cost—the other work they turned down or could not pursue because capacity was reserved for the canceled project. Common kill fee structures are a percentage of the remaining unpaid contract value: twenty-five percent for early cancellation, fifty percent for late-stage cancellation. The specific percentage should reflect the nature of the work and how much notice the client provides." },
      { question: "Does the client own the work I create as a freelancer?", answer: "Not automatically. Under copyright law, work created by an independent contractor is owned by the creator unless there is a written agreement assigning ownership to the client. If your freelance agreement includes an IP assignment clause, the client acquires ownership upon your receipt of full payment. If there is no assignment clause—or if you have not been paid—you technically retain ownership. Be sure your agreement clearly states whether you are assigning ownership or granting a license, and what the triggering event is (typically full payment)." },
      { question: "How should I handle a client who refuses to pay?", answer: "Start by sending a formal written payment demand referencing the invoice, payment due date, and contract payment terms. If that fails, send a breach of contract notice with a final cure period. For amounts within small claims court thresholds (typically five thousand to ten thousand dollars depending on the state), file in small claims court without an attorney. For larger amounts, consult an attorney about demand letter, collections, or arbitration options. If your jurisdiction has a freelancer protection law, file a complaint with the relevant enforcement agency." },
      { question: "Can a client use my work before paying me in full?", answer: "Your contract should specify when the client acquires the right to use the deliverables. If ownership transfers upon full payment, the client technically does not have the right to use the work before final payment is made. In practice, you can allow preliminary use under a conditional license that becomes a full ownership assignment upon payment, or you can provide final files only after payment is received. For large projects, some freelancers use a watermarking or low-resolution preview approach to allow client review without enabling full use before payment." },
    ],
  },

  service_agreement_software_development: {
    overview: [
      "A software development service agreement governs the delivery of custom software applications, platforms, integrations, or technology solutions on a contract basis. Whether the engagement is a fixed-price build, a time-and-materials sprint-based arrangement, or a managed service retainer, the software development agreement must address a set of concerns that distinguish technology contracts from other professional service agreements: source code ownership and licensing, open-source dependency management, performance and security standards, warranty obligations for functional conformance, and limitation of liability for downstream failures caused by defective code.",
      "The technical requirements documentation that accompanies a software development agreement is as legally significant as the contract itself. Courts resolving software development disputes look to the functional specifications, user stories, or technical requirements documents to determine what the developer promised and whether the delivered software meets that standard. Requirements that are vague, inconsistent, or silent on critical system behaviors create gaps that parties fill in their own favor when disputes arise. Investing time in developing precise, testable requirements before contract execution—and incorporating those requirements as contract exhibits—is the most effective legal risk management strategy in software development engagements.",
      "Agile and sprint-based development methodologies create unique contractual challenges because they resist the fixed scope and deliverable model that works well in waterfall projects. Agile contracts typically define a backlog of user stories prioritized by the product owner, with the development team delivering a working software increment at the end of each sprint rather than a single final deliverable. The service agreement must accommodate this iterative model by defining the sprint duration, the story pointing or estimation process, the velocity expectations, the sprint review and acceptance process, and the mechanism for adjusting the backlog based on evolving business requirements. Fixed-price agile engagements require particular care because sprint velocity is inherently variable.",
      "Post-delivery obligations are a critical component of software development agreements that are frequently under-negotiated. Clients often discover that delivered software requires ongoing maintenance—security patches, dependency updates, compatibility fixes for new operating system releases, and performance tuning—shortly after the initial delivery period ends. The development agreement should address the warranty period during which the developer fixes functional defects at no charge, the support tier that applies after warranty expiration, the response time commitments for critical versus non-critical issues, and the pricing for ongoing maintenance and enhancement work. Leaving these terms to negotiation after delivery creates leverage problems for both parties.",
    ],
    howItWorks: [
      { step: "Define the Technical Scope and Requirements", description: "Attach functional specifications, user stories, technical architecture documents, and API specifications as contract exhibits. Define the technology stack, hosting environment, and integration requirements. Specify which requirements are in scope for the initial engagement and which are deferred to future phases. Include a requirements change process that allows the backlog to evolve without destabilizing the contract framework." },
      { step: "Structure the Development Engagement Model", description: "Select and document the delivery model: fixed-price waterfall, time-and-materials sprints, or managed service retainer. For fixed-price engagements, tie payments to milestone deliverables and acceptance. For sprint-based engagements, specify the sprint duration, velocity expectations, sprint review process, and payment timing. For retainers, define the monthly capacity commitment and the process for allocating that capacity across development tasks." },
      { step: "Define Testing and Acceptance Criteria", description: "Specify the testing requirements the software must meet before acceptance—unit test coverage percentage, integration test pass rates, performance benchmarks (response time, throughput, error rate), and security scan results. Define who is responsible for user acceptance testing (client) versus functional testing (developer) and the timeline for each. Specify that payment is conditioned on acceptance, not merely delivery." },
      { step: "Address Source Code and IP Assignment", description: "Confirm that all custom-written source code, documentation, test suites, database schemas, and technical specifications are assigned to the client upon full payment. Carve out pre-existing developer tools, frameworks, and libraries from the assignment. Require delivery of all code via an agreed repository with full commit history, and require the developer to revoke all system and repository access at project close." },
      { step: "Set Warranty and Support Terms", description: "Define a warranty period (sixty to ninety days post-acceptance) during which the developer fixes functional defects at no additional charge. Specify the defect severity classification (critical, major, minor) and response time commitments for each. Describe the support arrangement after warranty expiration, including the hourly rate for post-warranty fixes and the process for submitting and prioritizing support requests." },
    ],
    legalConsiderations: [
      { title: "Software Defect Liability and Limitation", body: "Software defects can cause significant downstream harm—service outages, data loss, security breaches, financial losses. Without a liability limitation clause, a development firm could face claims vastly exceeding the project fees. Standard software development agreements cap liability at the total fees paid under the agreement, with exceptions for confidentiality breaches, IP infringement indemnification obligations, and gross negligence. Clients in regulated industries may push for higher caps; negotiate based on the risk profile of the specific application." },
      { title: "Data Protection and Security Obligations", body: "Software development contractors who access client data or build systems that process personal information may be subject to data protection obligations under GDPR, CCPA, HIPAA, or other applicable laws. The development agreement should specify whether the contractor qualifies as a data processor under applicable law, require the contractor to implement appropriate technical safeguards, and obligate the contractor to notify the client of any data security incidents affecting client data during the engagement." },
      { title: "Escrow Arrangements for SaaS Platforms", body: "Clients who depend on custom software maintained by a third-party developer face the risk that the developer becomes unavailable—through insolvency, acquisition, or relationship termination. A source code escrow arrangement with a neutral third-party escrow agent provides the client access to the source code if the developer fails to maintain the software. Escrow is particularly relevant for mission-critical applications and SaaS platforms where the client lacks technical capability to maintain the code independently." },
      { title: "Offshore Development Considerations", body: "Software development engagements with contractors located outside the United States raise additional legal considerations: applicable law and enforcement of contract terms across international borders, data transfer restrictions under GDPR and other privacy laws when the offshore developer accesses personal data, intellectual property protection in jurisdictions with weaker enforcement regimes, and withholding tax obligations for payments to foreign contractors. International software development agreements require input from counsel familiar with cross-border technology transactions." },
    ],
    commonMistakes: [
      { mistake: "Accepting Delivery Without Formal Acceptance Testing", fix: "Accepting software delivery without formal acceptance testing—and documenting that acceptance—creates disputes about whether defects discovered later are warranty items or new bugs. Conduct structured acceptance testing against written test cases derived from the functional requirements, document the results, and provide formal written acceptance or rejection with specific defect descriptions." },
      { mistake: "Not Requiring Source Code Delivery Throughout the Project", fix: "Some developers deliver source code only at project completion, leaving the client with no code if the relationship deteriorates mid-project. Require incremental source code delivery via a shared repository throughout the engagement. This also facilitates client code review and enables a faster handoff if the developer relationship ends unexpectedly." },
      { mistake: "Omitting a Performance Requirements Definition", fix: "Delivering software that technically meets functional requirements but runs unacceptably slowly is a common source of post-delivery disputes. Define specific performance requirements in the contract exhibits: page load times, API response times, concurrent user capacity, and uptime expectations. Include performance benchmarks as acceptance criteria that must be met before final payment is released." },
      { mistake: "Vague 'Bug Fix' Warranty Without Severity Classification", fix: "A warranty that simply promises to 'fix bugs' leaves open how quickly bugs must be fixed and which bugs fall within the warranty scope. Define bug severity levels—critical (system unusable), major (core feature broken), minor (cosmetic or edge case)—with specific response and resolution time commitments for each severity level. Reserve the warranty for issues that cause non-conformance with functional specifications, not for new feature requests." },
      { mistake: "Failing to Address Third-Party API Dependency Risk", fix: "Software built on third-party APIs—payment processors, mapping services, social platform APIs—is vulnerable to changes in those APIs that break functionality. The development agreement should acknowledge third-party API dependencies, allocate responsibility for monitoring API change announcements, and describe the change order process for adaptations required by upstream API changes." },
    ],
    extendedFaq: [
      { question: "What is the difference between a fixed-price software development contract and a time-and-materials contract?", answer: "A fixed-price contract specifies a total price for a defined scope of work, with the developer absorbing cost overruns. A time-and-materials contract bills for actual hours worked at agreed rates plus materials costs, with the client absorbing the risk of scope and time expansion. Fixed-price works best when requirements are stable and well-defined at the outset. Time-and-materials works best for exploratory, research-intensive, or agile engagements where the final scope is expected to evolve based on development learnings." },
      { question: "What should I do if the software delivered doesn't work as expected?", answer: "Start by documenting the specific defects with steps to reproduce each issue and comparing the behavior to the functional specifications in the contract. Send a formal written notice of the defects to the developer, referencing the warranty period and requesting correction within the defined cure period. If the developer disputes whether the issue is a defect or a new feature request, refer to the functional specifications to determine which characterization is accurate. If the warranty period has expired, the issue will likely be billable at post-warranty support rates." },
      { question: "Can a developer reuse code they wrote for my project in other client projects?", answer: "Whether the developer can reuse code depends on the IP assignment clause in your contract. If the contract assigns all custom code to you upon payment, the developer cannot reuse that code in other projects without your permission. However, developers often carve out pre-existing tools, frameworks, and utility libraries they developed before the engagement and use across multiple client projects. These carve-outs are typically described as background IP that is licensed to you (not assigned) for use in your application." },
      { question: "What is a software escrow and do I need one?", answer: "A software escrow arrangement involves depositing the application's source code with a neutral third-party escrow agent who releases it to you if the developer becomes unable to maintain the software—due to insolvency, dissolution, or failure to maintain the application under the agreement. Escrow is most valuable when you depend on a third-party developer to maintain business-critical software and you lack the technical capacity to maintain it yourself. For projects where you receive the source code directly, escrow is less critical, but it is worthwhile for any mission-critical platform where developer continuity is essential." },
    ],
  },

  service_agreement_cleaning: {
    overview: [
      "A cleaning service agreement establishes the terms under which a cleaning company or independent cleaning professional provides residential or commercial cleaning services to a client. Unlike many service agreements where deliverables are intangible, cleaning contracts deal with a physical, recurring service performed inside the client's home or business premises—creating distinct considerations around access and security, property liability, health and safety compliance, and the consistent quality standards that recurring service clients expect. A well-structured cleaning service agreement protects both the cleaning provider's right to receive payment for reliable service and the client's right to access their property safely and receive the agreed quality of cleaning.",
      "Access and security arrangements are a foundational concern in cleaning service agreements, particularly for residential clients and commercial premises with sensitive areas. The agreement must address how the cleaner will access the property—key, key code, security card, or client must be present—and who is responsible for changing access codes or retrieving keys if the service relationship ends. The cleaner's obligation to maintain access credentials confidentially, to restrict access to only areas within the cleaning scope, and to report any security issues or property damage discovered during cleaning should be documented in writing. These provisions protect the client from security risks while clarifying the cleaner's obligations and limiting their liability for pre-existing conditions.",
      "Commercial cleaning agreements involve an additional layer of complexity because of employment and subcontracting arrangements common in the industry. Many commercial cleaning companies employ crews rather than performing the work themselves, and the agreement must address supervisory responsibility, employee background checks, and liability for employee conduct while on the client's premises. The agreement should also address OSHA compliance for the use of cleaning chemicals and equipment, workers' compensation insurance for employees who may be injured on the client's property, and the client's responsibility for maintaining a safe working environment, including identifying hazardous materials and providing adequate ventilation for chemical cleaning products.",
      "Quality and complaint resolution mechanisms are essential for cleaning service agreements because the standard of 'clean' is inherently subjective and the service is recurring—dissatisfaction that is not addressed promptly tends to compound over time. The agreement should define the specific tasks included in each cleaning visit (vacuuming, mopping, bathroom sanitization, kitchen cleaning, dusting), tasks that are explicitly excluded (deep cleaning, laundry, dishes, organization), and the process for requesting add-on tasks at additional cost. Quality complaints should be directed to a specific point of contact within a defined timeframe, with the provider committed to returning to address identified deficiencies within a specified period at no additional charge.",
    ],
    howItWorks: [
      { step: "Define the Cleaning Scope and Frequency", description: "List each room or area to be cleaned, the tasks performed in each area, and any tasks explicitly excluded from the standard service. Specify the cleaning frequency—weekly, bi-weekly, monthly—and the approximate duration of each visit. Attach a cleaning checklist as an exhibit to create an objective reference for quality assessment." },
      { step: "Set the Service Rate and Payment Terms", description: "State the per-visit rate or monthly service fee, the payment due date (before service, on service day, or monthly billing), and acceptable payment methods. For commercial clients, specify the invoicing schedule and net payment period. Include a late payment interest provision and the right to suspend service for non-payment after a defined grace period." },
      { step: "Address Access, Keys, and Security", description: "Specify the access method (key, code, in-person), who is authorized to provide access, and how access credentials are stored and secured. Require the cleaner to immediately report any access-related security incidents, lost credentials, or property damage discovered during cleaning. Specify the return or destruction of access credentials within a defined period after service termination." },
      { step: "Include Insurance and Liability Terms", description: "Require the cleaner to maintain general liability insurance covering property damage and bodily injury caused by the cleaning service, with a minimum coverage limit specified. Address liability for pre-existing damage versus damage caused during cleaning, and the claims reporting and resolution process. Limit the cleaner's liability for incidental damage to a reasonable cap, typically the cost of the specific cleaning session in which the damage occurred." },
      { step: "Define Cancellation and Rescheduling Policies", description: "Specify the notice period required to cancel or reschedule a cleaning visit without penalty (typically twenty-four to forty-eight hours). Describe the cancellation fee that applies for late cancellations or lockouts when the cleaner cannot gain access. Address the policy for recurring service skips—whether they are rescheduled, credited, or simply missed—and the notice required to permanently discontinue service." },
    ],
    legalConsiderations: [
      { title: "Property Damage Liability and Valuation", body: "Cleaning companies routinely encounter claims for damage to client property—broken items, scratched surfaces, discolored fabrics. The agreement should establish the claims reporting process, the documentation required (photographs, original purchase receipts), and the liability standard (negligence, not strict liability). A liability cap tied to the value of damaged items or a session-based cap limits exposure for incidental damage while preserving the client's ability to seek recourse for significant losses." },
      { title: "Cleaning Chemical Compliance", body: "Commercial cleaning operations must comply with OSHA's Hazard Communication Standard, which requires Safety Data Sheets for all hazardous cleaning chemicals, employee training on chemical hazards, and proper labeling of chemical containers. The service agreement should confirm the cleaner's OSHA compliance obligation and address who is responsible for ensuring adequate ventilation, chemical storage, and disposal on the client's premises." },
      { title: "Background Check Representations", body: "Clients who grant cleaning crews access to their home or business with sensitive areas or valuables have legitimate security interests. Including a clause in which the cleaning company represents that all personnel assigned to the client's property have passed criminal background checks—and agreeing to notify the client promptly if a background check issue arises for an assigned employee—provides a contractual basis for seeking recourse if an undisclosed issue causes harm." },
      { title: "Independent Contractor vs. Employee Classification", body: "Cleaning companies that use independent contractor cleaners rather than employees must ensure the relationship meets the applicable classification test in their state. California's ABC test applies particularly strictly to cleaning services, as cleaning is often considered within the ordinary course of a cleaning company's business. Misclassification of cleaning workers as independent contractors is a significant enforcement target for state labor agencies." },
    ],
    commonMistakes: [
      { mistake: "Not Defining What Is and Is Not Included in the Service", fix: "Clients often assume cleaning services include tasks like washing dishes, doing laundry, or organizing cluttered spaces. If these tasks are not included in the standard service, they must be explicitly excluded in the agreement to prevent disputes about why they were not performed. A detailed cleaning checklist as an exhibit prevents this ambiguity." },
      { mistake: "Omitting a Cancellation Fee", fix: "A cleaner who drives to a location, cannot gain access because the client forgot about the appointment, and returns without performing any work has wasted travel time and foregone another booking. A lockout fee or cancellation fee that compensates for this wasted time is standard and enforceable when clearly disclosed in the agreement." },
      { mistake: "Not Requiring Proof of Insurance Before Service Begins", fix: "A cleaning company that damages property and has no insurance—or insufficient insurance—leaves the client with only a breach of contract claim against an entity that may lack assets to satisfy a judgment. Require a certificate of insurance before service begins and verify that coverage limits are adequate for the value of property at risk." },
      { mistake: "Failing to Inspect the Property at Onboarding", fix: "Without a baseline inspection documenting pre-existing damage, the cleaner cannot effectively contest claims that damage was caused by their service. Conduct a walk-through inspection with the client before the first cleaning visit, document pre-existing damage with photographs, and have the client acknowledge the condition record. This prevents cleaning services from being blamed for pre-existing conditions." },
      { mistake: "Allowing Indefinite Service Continuation Without Written Notice to Terminate", fix: "Cleaning service agreements sometimes continue indefinitely until one party orally indicates a desire to stop. Require written notice to terminate the ongoing service—typically seven to fourteen days in advance—so both parties have a clear termination record and the cleaner can plan for the schedule change." },
    ],
    extendedFaq: [
      { question: "Who is responsible if the cleaner breaks something in my home?", answer: "A professional cleaning service's general liability insurance covers accidental damage to client property caused by the cleaner's negligence during the service. The process for claiming coverage typically requires immediate notification to the cleaning company (before the next scheduled service), photographs of the damage, and documentation of the item's value. Pre-existing damage that was not documented at onboarding may generate disputes about whether the cleaner caused the damage. Always conduct a move-in walk-through with your cleaner and document the property's initial condition." },
      { question: "Can a cleaning service bring different employees each visit, or can I request the same person?", answer: "This depends on the service company's policies. Some clients prefer consistency for security reasons—they are more comfortable with a familiar person in their home. You can request a preferred cleaner or cleaning team in the service agreement, but be aware that the company may not always be able to accommodate the request due to scheduling, staffing changes, or the preferred cleaner's availability. For security-sensitive clients, negotiating a small crew that is background-checked and approved by the client before assignment is a reasonable contractual request." },
      { question: "What should I do if the cleaning service is consistently not meeting my quality expectations?", answer: "Most cleaning service agreements include a complaint resolution process that gives the cleaner an opportunity to return and address specific deficiencies at no charge. Start by documenting the specific issues with photographs and submitting a written complaint through the contractual channel within the specified timeframe. If the same issues recur after multiple remediation visits, review the agreement's termination provision and provide written notice of termination in accordance with the specified notice period." },
      { question: "Do I need to provide cleaning supplies, or does the cleaner bring their own?", answer: "The agreement should specify whether the cleaner provides all supplies and equipment, the client provides them, or some combination applies. Professional cleaning companies typically bring their own commercial-grade supplies and equipment, which they know are effective and safe for their staff. If you have specific products you prefer (due to allergies, sensitivities, or eco-friendly preferences), disclose this before service begins and confirm whether the cleaner will accommodate the request or whether alternative products can be provided at additional cost." },
    ],
  },

  service_agreement_consulting: {
    overview: [
      "A consulting service agreement governs a professional engagement in which an expert advisor provides analysis, recommendations, strategy, and guidance to a client organization seeking to improve performance, solve complex problems, or navigate specialized challenges. Consulting engagements span every industry and functional area—management consulting, financial advisory, HR consulting, technology strategy, legal compliance, and operational improvement—and the agreement must be tailored to the specific nature of the advisory relationship. Because consulting deliverables often take the form of recommendations rather than finished products, and because the value of consulting advice depends heavily on the quality of client-provided information, the allocation of responsibility between consultant and client is a nuanced drafting challenge.",
      "The scope of work in a consulting agreement must distinguish clearly between what the consultant will analyze and recommend versus what the client is responsible for implementing. Consultants provide expertise and advice; clients make implementation decisions and bear responsibility for business outcomes. This distinction matters enormously for liability purposes—a consultant whose recommendations are not followed, are partially implemented, or are implemented in a manner inconsistent with the recommendation cannot fairly be held responsible for disappointing results. The consulting agreement should document this dynamic explicitly, stating that implementation decisions are the client's responsibility and that results depend on faithful implementation of agreed recommendations in conjunction with the client's own operational capabilities.",
      "Confidentiality in consulting engagements operates in both directions. The consultant necessarily accesses sensitive client information—financial data, strategic plans, personnel matters, operational weaknesses, and competitive positioning—and the client reasonably expects that information to be held in strict confidence. Conversely, the consultant brings proprietary methodologies, frameworks, and analytical tools that represent their competitive differentiation, and the client should not be entitled to replicate those tools for use in future engagements without retaining the consultant. A well-drafted consulting agreement protects both the client's business information and the consultant's intellectual property through carefully calibrated confidentiality and IP provisions.",
      "The compensation structure for consulting engagements commonly follows one of three models: a project-based fixed fee for a defined deliverable or analysis, a daily or hourly rate for time-and-materials engagements where scope is less certain, or a retainer for ongoing advisory relationships that include a defined number of hours or engagements per month. For retained advisory relationships, the agreement should specify exactly what the retainer covers—email response, scheduled calls, on-site visits, document review—and the rate that applies to activities outside the retainer scope. High-value consulting engagements sometimes include a performance-based fee component tied to measurable outcomes, but these arrangements require extremely precise success metric definition to avoid disputes.",
    ],
    howItWorks: [
      { step: "Define the Consulting Scope and Deliverables", description: "Specify the exact analyses, assessments, or deliverables the consultant will produce—market analysis report, organizational design recommendations, financial model, implementation roadmap. Define the assumptions underlying the engagement scope and the client-provided information the consultant requires to perform the analysis. Clarify what is explicitly excluded from the engagement." },
      { step: "Set Fees, Expenses, and Invoicing Terms", description: "State the consulting fee structure (project-based, daily rate, or monthly retainer), the payment schedule, and any applicable expense reimbursement policy (travel, accommodation, research costs). Specify the expense approval threshold and documentation requirements. Include a late payment interest clause and a work suspension right for significant invoice delinquency." },
      { step: "Establish the Engagement Process and Communication Protocol", description: "Define how the engagement will be structured—kick-off meeting, discovery phase, interim progress reviews, final presentation. Specify client responsibilities for providing access to data, personnel, and systems. Define the primary point of contact on each side and the communication channel for routine engagement management versus escalation of significant issues." },
      { step: "Address Intellectual Property and Methodology Rights", description: "Assign ownership of client-specific deliverables—reports, models, plans—to the client upon payment. Retain for the consultant all proprietary methodologies, frameworks, templates, and analytical tools used to produce the deliverables, granting the client only a limited license to use them as incorporated in the delivered work product. Include a confidentiality clause protecting both the client's information and the consultant's proprietary approaches." },
      { step: "Define the Limitation of Liability and Results Disclaimer", description: "Include a liability cap tied to fees paid under the agreement. Add a results disclaimer confirming that consulting recommendations do not guarantee specific business outcomes and that implementation results depend on client decisions and actions beyond the consultant's control. Include a mutual indemnification clause and a consequential damages waiver to limit both parties' exposure for indirect losses." },
    ],
    legalConsiderations: [
      { title: "Professional Liability and E&O Insurance", body: "Consultants who provide specialized professional advice should carry errors and omissions (E&O) insurance, which covers claims that the consultant's advice was negligent or incorrect and caused financial harm to the client. The consulting agreement should require the consultant to maintain E&O coverage throughout the engagement and for a defined period after completion, matching the potential lag between engagement conclusion and discovery of a claim." },
      { title: "Non-Solicitation of Client Personnel", body: "Consulting engagements give consultants significant exposure to client employees—their capabilities, compensation levels, and career aspirations. Including a mutual non-solicitation clause restricting both parties from recruiting or hiring each other's personnel during the engagement and for a defined post-engagement period (typically twelve to twenty-four months) protects both parties from talent raiding in the context of the consulting relationship." },
      { title: "Conflicts of Interest Disclosure", body: "Consultants who provide advice to multiple clients in the same industry may hold information or relationships that create conflicts of interest. The consulting agreement should require the consultant to disclose any potential conflicts before engagement commencement and throughout the engagement as new conflicts arise. It should also describe the consultant's ethical obligation to recuse themselves from matters where a conflict cannot be managed through disclosure and informed consent." },
      { title: "Work Product as Legal or Regulatory Advice Disclaimer", body: "Consulting deliverables—particularly in HR, compliance, financial, and operational areas—may touch on subjects that require licensed professional advice (legal, accounting, medical). The consulting agreement should include a clear disclaimer that the deliverables represent business consulting advice and do not constitute legal, accounting, or other licensed professional advice, and that the client should seek appropriate licensed professional counsel for matters requiring it." },
    ],
    commonMistakes: [
      { mistake: "Failing to Document the Client's Responsibilities", fix: "Consulting engagements depend on client-provided information, access, and decision-making. When client delays in providing data or approvals extend the engagement timeline, the consultant risks bearing the cost of the delay without a contract provision addressing it. Document the specific information, access, and decisions the client must provide by specified dates, and include a provision extending the engagement timeline and potentially the fees for client-caused delays." },
      { mistake: "Not Including a Results Disclaimer", fix: "Clients sometimes interpret consulting recommendations as guarantees of business outcomes. A clear results disclaimer in the agreement protects the consultant from claims that promised results were not achieved when the actual cause of disappointing outcomes is the client's implementation decisions, market conditions, or other factors outside the consultant's control." },
      { mistake: "Using Broad IP Assignment Language That Captures Proprietary Methodologies", fix: "Consulting agreements drafted by clients sometimes use broad IP assignment language that purports to assign all work product, including the methodologies, frameworks, and tools the consultant uses across multiple client engagements. Consultants should negotiate to retain ownership of their proprietary approaches and assign only the client-specific deliverables—reports, models, plans—that are produced using those approaches." },
      { mistake: "Providing Advice Outside the Defined Scope Without Adjusting the Fee", fix: "Clients often ask consulting questions outside the defined engagement scope during meetings and calls, treating informal advice as an extension of the retainer. Track and document scope expansion requests, address them through a formal scope amendment or change order process, and charge appropriately for additional advisory work rather than providing it as an implicit part of the existing engagement." },
      { mistake: "Omitting a Survival Clause for Post-Termination Obligations", fix: "Confidentiality, IP ownership, non-solicitation, and liability limitation provisions must remain in effect after the consulting agreement ends. Include a survival clause specifying which provisions survive termination and for how long. Without a survival clause, important protective provisions technically expire when the agreement terminates." },
    ],
    extendedFaq: [
      { question: "What happens if the consultant's recommendations don't achieve the expected results?", answer: "A consultant's liability for unachieved results depends on what was promised and whether the failure is attributable to negligent advice or to implementation factors. Consultants typically represent that advice will be provided with professional skill and care, not that specific business outcomes will be achieved. If a consultant's recommendation was based on incorrect analysis or materially flawed advice, an errors and omissions claim may be viable. If the recommendation was sound but the client's implementation was flawed or market conditions changed, the consultant bears no liability for the outcome." },
      { question: "Can a consultant work with my competitors while engaged with us?", answer: "A consulting agreement does not automatically prohibit the consultant from working with your competitors unless a specific exclusivity or non-compete clause is included. If simultaneous competitor engagements create a genuine conflict of interest or risk of confidential information misuse, negotiate an exclusivity provision covering your specific market segment, with appropriate compensation for the exclusivity restriction. For most consulting engagements, a comprehensive confidentiality clause combined with a conflict disclosure obligation is sufficient protection." },
      { question: "Who owns the reports and recommendations the consultant produces?", answer: "Ownership depends on the IP provisions of the consulting agreement. Client-commissioned reports and recommendations are typically assigned to the client upon payment, because they are specifically tailored to the client's situation and have limited value to the consultant. The consultant's underlying methodologies, frameworks, industry knowledge, and analytical tools remain the consultant's property. Ensure the agreement clearly distinguishes between the client-owned deliverables and the consultant's retained proprietary tools and approaches." },
      { question: "How should a consulting retainer be structured to ensure value?", answer: "A consulting retainer is most effective when it defines specific deliverables or activities included in the monthly fee—scheduled calls, document review, attendance at defined meetings—rather than vague 'availability.' Specify the monthly hour commitment, the response time for retainer-covered inquiries, the process for scheduling retained services, and the rate that applies to activities exceeding the retainer scope. Regular check-ins about retainer utilization help both parties assess whether the retainer scope and fee remain appropriate as the engagement evolves." },
    ],
  },

  non_compete_agreement_employee: {
    overview: [
      "A non-compete agreement for employees restricts a departing employee's ability to work for a competitor, start a competing business, or compete directly against their former employer in a defined geographic area for a defined period following the end of employment. Non-compete clauses serve a legitimate business interest in protecting confidential information, trade secrets, customer relationships, and specialized training that the employer has invested in developing. However, they also significantly restrict a person's ability to earn a living in their chosen field—which is why courts scrutinize non-competes for employees more carefully than almost any other type of commercial contract provision.",
      "Enforceability standards for employee non-competes vary dramatically by state. California, North Dakota, Oklahoma, and Minnesota have virtually abolished non-compete enforcement for employees, reflecting a policy judgment that non-competes harm workers and suppress wage competition. At the opposite end of the spectrum, states like Florida have strong legislative policies supporting non-compete enforcement, including a statutory presumption that a former employee's use of trade secrets constitutes irreparable harm warranting injunctive relief. Most states fall between these poles, enforcing non-competes that are supported by adequate consideration, reasonably limited in scope and duration, and narrowly tailored to protect a legitimate business interest without unduly burdening the employee.",
      "Adequate consideration is a threshold requirement for employee non-compete enforceability that is often overlooked in the urgency of onboarding or acquisition negotiations. When a non-compete is signed at the inception of employment, the job offer itself constitutes consideration. When an existing employee is asked to sign a non-compete mid-employment, many states require additional, independent consideration—a raise, promotion, bonus, or other tangible benefit—beyond mere continued employment. A non-compete signed by an existing employee in exchange only for continued employment (an illusory promise in at-will employment relationships) may be unenforceable in those states as a matter of contract law. Document the consideration supporting any mid-employment non-compete carefully.",
      "The geographic scope and duration of an employee non-compete must be calibrated to the actual competitive threat the employee poses to the employer's legitimate business interests. An executive with responsibility for global sales strategy may reasonably be restricted from competing nationally; a customer service representative with limited client contact and no access to trade secrets should not face the same restriction. Similarly, a two-year restriction may be appropriate for a research scientist who developed patented technology over a long tenure, while a six-month restriction may be all that is warranted for a salesperson in a fast-moving industry where customer relationships shift quickly. Courts applying a reasonableness test will reduce or eliminate restrictions that are broader than necessary to protect the employer's legitimate interests.",
    ],
    howItWorks: [
      { step: "Identify the Legitimate Business Interest Being Protected", description: "Document the specific business interest the non-compete is designed to protect—trade secrets, confidential business information, specialized training, or customer goodwill. Courts require non-competes to be supported by a legitimate protectable interest, not simply a desire to prevent competition. The more precisely the protectable interest is identified, the better positioned the employer is to enforce the restriction." },
      { step: "Define the Restricted Activity Precisely", description: "Specify what activities are prohibited—working for a competitor in the same functional role, starting a competing business, or soliciting the employer's customers. Avoid overbroad language that restricts any employment in a broadly defined industry. Narrow the restriction to the specific competitive activity that threatens the legitimate business interest identified in the previous step." },
      { step: "Set a Reasonable Duration", description: "Choose a restriction period supported by the nature of the protectable interest. Six to twelve months is appropriate for most employees; twelve to twenty-four months is appropriate for senior executives or employees with access to long-lived trade secrets. Periods exceeding two years face significant enforceability challenges in most states and are unenforceable in others regardless of duration." },
      { step: "Define the Geographic Scope", description: "Limit the restriction to the territory where the employee actually competed or had responsibility. For nationally remote roles or roles with global reach, a national or global restriction may be appropriate. For local or regional roles, restrict competition to the relevant market area. State specifically the geographic area rather than using vague terms like 'the company's market area.'" },
      { step: "Provide Independent Consideration for Mid-Employment Agreements", description: "If an existing employee is being asked to sign a non-compete for the first time, document the consideration being provided in exchange—a pay increase, a one-time bonus, a promotion, or access to equity awards. Obtain the employee's signature acknowledging receipt of the consideration and their understanding that the non-compete is a condition of receiving it." },
    ],
    legalConsiderations: [
      { title: "Blue Penciling and Judicial Modification", body: "Some states permit courts to 'blue pencil' an overbroad non-compete—modifying its geographic scope, duration, or restricted activities to make it enforceable rather than voiding it entirely. Other states follow an all-or-nothing rule, refusing to enforce any restriction that is broader than reasonable. When drafting in blue-pencil states, erring toward a broader restriction may be acceptable because the court can trim it. In all-or-nothing states, draft conservatively to ensure the restriction as written passes the reasonableness test." },
      { title: "Federal Trade Commission Non-Compete Rule", body: "The FTC issued a rule in 2024 that would have broadly prohibited employee non-compete agreements at the federal level, but the rule faced legal challenges and its ultimate fate is uncertain. Employers should monitor developments in federal non-compete policy and ensure their non-compete agreements comply with all applicable state law while the federal situation evolves. Even if a broad federal prohibition is ultimately enacted, trade secret protections and non-solicitation agreements will remain valid tools for protecting legitimate business interests." },
      { title: "Choice of Law and Non-Compete Enforceability", body: "Employers sometimes include choice-of-law clauses designating the law of a non-compete-friendly state (e.g., Florida) to govern employment agreements with employees who work in non-compete-restrictive states (e.g., California). Courts in restrictive states often refuse to apply the chosen law if it would violate a fundamental public policy of the employee's home state. Choice-of-law provisions are not a reliable workaround for state non-compete prohibitions." },
      { title: "Garden Leave as an Alternative", body: "Some employers use 'garden leave' clauses—requiring the employee to remain employed (and receive full compensation) during the notice or restricted period, during which they perform no active duties—as an alternative or supplement to traditional non-competes. Because the employee is compensated during the restriction period, garden leave is more likely to be viewed as reasonable and less likely to be challenged as an undue burden. Garden leave clauses are more common in financial services and technology sectors." },
    ],
    commonMistakes: [
      { mistake: "Requiring All Employees to Sign Identical Non-Competes Regardless of Role", fix: "Applying the same non-compete to a C-suite executive and a front-desk receptionist invites judicial skepticism about whether the restriction is genuinely tailored to protect legitimate interests. Tiered non-compete programs—with stronger restrictions for employees with trade secret access and no or minimal restrictions for lower-level employees—are more defensible and reflect the actual risk profile of each role." },
      { mistake: "Using Non-Competes Instead of Proper Trade Secret Protection", fix: "Non-competes are a blunt instrument. Trade secret protection—through confidentiality agreements, access controls, security protocols, and trade secret designation policies—is more targeted and enforceable in all states. An employee who takes trade secrets is liable under the Defend Trade Secrets Act regardless of whether a non-compete exists. Focus on trade secret protection as the primary protective mechanism and use non-competes only for roles with genuinely significant competitive risk." },
      { mistake: "Failing to Present the Non-Compete Before the Employee Accepts the Job Offer", fix: "An employee who accepts a job offer, gives notice to their current employer, and then receives a non-compete for the first time on their first day has limited practical ability to negotiate or refuse. Courts in some states refuse to enforce non-competes that are presented as a surprise after the offer is accepted. Disclose non-compete requirements before the candidate accepts, and provide the actual agreement for review with adequate time before execution." },
      { mistake: "Including Non-Competes in Arbitration Agreements Without Considering Confidentiality Implications", fix: "Arbitration of non-compete disputes is confidential, which prevents public judicial decisions that could create precedents limiting enforcement. However, some states prohibit mandatory arbitration of employment disputes, and including arbitration in a non-compete agreement for employees in those states may create enforceability issues for the entire agreement." },
      { mistake: "Not Maintaining a Database of Signed Non-Compete Agreements", fix: "When an employee's departure triggers a potential non-compete issue, the employer needs to locate the signed agreement quickly. Maintain a centralized record of which employees signed non-compete agreements, the agreement date, the version signed, and the restrictions applicable to each employee. This record is essential for quick assessment of post-departure competitive activities." },
    ],
    extendedFaq: [
      { question: "Can my employer enforce a non-compete if I was laid off?", answer: "Enforceability of a non-compete after an employer-initiated layoff depends on state law and the specific circumstances. Some courts refuse to enforce non-competes when the employee was laid off without cause, reasoning that enforcement would be inequitable—the employer ended the employment relationship and then seeks to restrict the employee's ability to earn a living elsewhere. California, for example, does not enforce non-competes regardless of the termination circumstances. In other states, enforceability after layoff turns on whether the employer continues to provide compensation during the restricted period." },
      { question: "How long can a non-compete restrict my ability to work in my field?", answer: "The maximum enforceable duration varies by state, the employee's role, and the nature of the protectable interest. Restrictions of six to twelve months are generally enforceable for most employees. Restrictions of twelve to twenty-four months are often enforceable for executives and employees with access to significant trade secrets. Restrictions exceeding two years face serious enforceability challenges in most states and are categorically unenforceable in several. Courts assess duration in light of how quickly the protectable information becomes stale and how long customer relationships persist." },
      { question: "If I move to a different state, does my non-compete still apply?", answer: "Geographic scope of the non-compete and the governing law of the agreement both matter. If the non-compete restricts activity in the states where you were employed but does not extend to your new state, relocating may effectively take you outside the restriction. If the restriction is national or global, relocation does not circumvent it. The applicable state law may also matter—if you move to California and work for a California employer, California courts may refuse to enforce a non-compete regardless of its choice-of-law clause, applying California's strong public policy against non-competes." },
      { question: "What is the difference between a non-compete and a non-solicitation agreement?", answer: "A non-compete broadly prohibits working for competitors or starting a competing business in a defined geography for a defined period. A non-solicitation agreement is narrower—it prohibits the former employee from soliciting the employer's clients or employees, without necessarily restricting competitive employment itself. Non-solicitation agreements are generally enforceable in states that refuse to enforce broad non-competes, making them a more reliable protective tool in restrictive jurisdictions. For most employers, a combination of non-solicitation and confidentiality obligations provides better practical protection than a broad non-compete." },
    ],
  },

  non_compete_agreement_contractor: {
    overview: [
      "Non-compete agreements for independent contractors occupy a more legally ambiguous space than employee non-competes. Because independent contractors are not employees, the rationale that courts apply to employee non-competes—protecting the employer's investment in training and confidential information shared during employment—applies with less force to contractor relationships. Contractors are inherently independent business operators who typically serve multiple clients; restricting their ability to serve clients in a particular industry or geographic area after the engagement ends directly undermines the business independence that defines the contractor relationship and may, paradoxically, support a worker classification argument that the 'contractor' was actually an employee.",
      "Courts evaluating contractor non-competes often apply the same reasonableness analysis used for employee non-competes but with heightened skepticism about the breadth of permissible restrictions. The legal justification for restricting a contractor's post-engagement competitive activity is narrower than for employees—typically limited to protecting confidential information, trade secrets, or proprietary methodologies actually shared during the engagement, and preventing the contractor from leveraging the client relationship to directly solicit the client's customers or employees. Broad restrictions that prevent the contractor from working in an entire industry or with any client in the client's market go beyond what courts are willing to enforce in most jurisdictions.",
      "The consideration requirement takes on a different character in contractor non-compete agreements. Because contractors are paid for services rendered rather than receiving an ongoing employment relationship with benefits, the exchange of consideration is more explicit: the client pays for services, and in exchange, the contractor agrees to post-engagement restrictions. However, if the non-compete is introduced after the contractor is already performing services without any new consideration—a new project, a bonus, or an extended term—the contractor can argue that the restriction lacks consideration. The safest approach is to include non-compete provisions in the original contractor agreement executed before work begins, so the initial engagement itself constitutes consideration.",
      "The interaction between contractor non-compete agreements and worker classification is a significant drafting consideration. A non-compete that closely tracks the structure of an employment non-compete—restricting all competitive employment, applying broadly across an industry, covering an extended duration—may be used as evidence in a worker classification audit to support the position that the 'contractor' is actually an employee. Structure contractor non-compete restrictions to reflect the genuinely independent nature of the relationship: limit restrictions to specific, identifiable confidential information and direct client solicitation rather than broad competitive employment restrictions.",
    ],
    howItWorks: [
      { step: "Identify What You Are Actually Protecting", description: "Before drafting a contractor non-compete, articulate specifically what the restriction is designed to protect. Is it the client list shared with the contractor? A proprietary process the contractor learned during the engagement? The contractor's use of the client's brand relationships to establish a competing business? The protection must be specific and legitimate—not simply a desire to prevent the contractor from competing generally." },
      { step: "Draft a Targeted Non-Solicitation Provision", description: "For most contractor engagements, a non-solicitation clause—prohibiting the contractor from directly soliciting the client's customers and employees with whom the contractor interacted during the engagement—provides adequate protection without the enforceability risks of a broad non-compete. Limit the restriction to specific clients and employees actually known to the contractor through the engagement, not the client's entire customer base." },
      { step: "Set a Proportionate Restriction Period", description: "Contractor non-compete restriction periods should generally be shorter than employee non-competes, reflecting the more limited relationship. Six to twelve months is typically the enforceable range for most contractor restrictions. Periods exceeding twelve months for contractors face significant enforceability challenges unless the restriction is limited to specifically identifiable confidential information with a long shelf life." },
      { step: "Include a Compensation Obligation During Restriction", description: "Some clients offer 'garden leave' style compensation—a percentage of the contractor's fees during the restriction period in exchange for the contractor's compliance with the non-compete. While not legally required in most jurisdictions, compensating the contractor during the restriction period significantly increases enforceability and reduces the practical burden of the restriction, making voluntary compliance more likely." },
      { step: "Pair With Strong Confidentiality and IP Assignment Terms", description: "A targeted confidentiality clause protecting specifically identified trade secrets and a comprehensive IP assignment covering all deliverables produced during the engagement often provide more practical protection than a broad non-compete. If the contractor cannot compete using the client's trade secrets (protected by confidentiality) or the deliverables created during the engagement (protected by IP assignment), the business risk of post-engagement competition is significantly reduced." },
    ],
    legalConsiderations: [
      { title: "Contractor Non-Competes as Misclassification Evidence", body: "The IRS, Department of Labor, and state labor agencies look at the totality of the working relationship when assessing worker classification. A contractor agreement that includes employee-style non-compete restrictions—broad industry exclusions, extended duration, geographic scope tracking the client's entire market—is inconsistent with the independence that characterizes a genuine contractor relationship. Non-compete provisions in contractor agreements should reflect the contractor's status as an independent business operator, not an economic dependent of the client." },
      { title: "Enforceability in California for Contractor Non-Competes", body: "California's non-compete prohibition extends to contractor agreements, not just employment agreements. Business & Professions Code Section 16600 prohibits agreements that restrain a person from engaging in a lawful profession, trade, or business, with very limited exceptions. Clients who engage California-based contractors cannot enforce traditional non-compete restrictions through California courts, regardless of any choice-of-law clause purporting to apply another state's law." },
      { title: "Trade Secret Protection as the Alternative Framework", body: "The Defend Trade Secrets Act provides federal civil remedies for misappropriation of trade secrets regardless of whether a non-compete exists. If a former contractor uses confidential client information—customer lists, pricing structures, proprietary methods—in a competitive business, the trade secret framework provides more reliable protection than an overbroad non-compete. Focus on information security practices, access controls, and targeted confidentiality obligations to create the factual foundation for a trade secret claim if misappropriation occurs." },
      { title: "Tortious Interference and Direct Competition", body: "Even without a non-compete, a contractor who uses confidential information obtained during the engagement to directly solicit the client's customers may be liable for tortious interference with business relationships. Courts are more willing to enjoin specific, targeted competitive conduct using the client's confidential information than to enforce broad non-compete restrictions. A confidentiality clause combined with a prohibition on using client-specific information in post-engagement competitive activity may provide more enforceable protection than a traditional non-compete." },
    ],
    commonMistakes: [
      { mistake: "Copying Employee Non-Compete Language into Contractor Agreements", fix: "Employee non-compete provisions are not appropriate for contractor agreements without substantial modification. The scope, duration, justification, and enforceability standards differ significantly between employee and contractor contexts. Use contractor-specific non-compete language that reflects the genuinely independent nature of the relationship and focuses on actual competitive threats rather than broad industry exclusions." },
      { mistake: "Attempting to Enforce Non-Competes Against Contractors Who Were Likely Employees", fix: "If a contractor relationship is subsequently reclassified as employment, the non-compete analysis shifts to the employee framework, which may include additional state-specific requirements (consideration, notice, mandatory waiting periods). If there is any ambiguity about worker classification, resolve it before attempting to enforce a non-compete and consult employment counsel about the appropriate legal framework." },
      { mistake: "Restricting the Contractor from Working in Their Entire Specialty", fix: "A non-compete that prevents a web developer from doing web development, a graphic designer from doing design work, or a consultant from consulting in their field is almost certainly overbroad and unenforceable. Restrict the contractor from working for specifically identified direct competitors or from soliciting specifically identified clients, not from practicing their profession." },
      { mistake: "Including Non-Competes Without Identifying the Specific Confidential Information at Stake", fix: "Courts are more willing to enforce contractor non-competes when the agreement identifies specific, legitimate confidential information that the restriction is designed to protect. A recital in the non-compete clause identifying the specific trade secrets or client relationships at stake—the proprietary pricing model, the customer database, the client's competitive roadmap—makes the restriction more defensible than a vague reference to 'confidential information.'" },
      { mistake: "Not Building In a Dispute Resolution Process for Alleged Violations", fix: "Before seeking injunctive relief in court for an alleged non-compete violation, the client should have a contractual obligation to give the contractor notice of the alleged violation and an opportunity to cure—particularly where the violation is ambiguous or the contractor disputes that the conduct falls within the restriction. A notice-and-cure process can resolve alleged violations more quickly and cheaply than court proceedings." },
    ],
    extendedFaq: [
      { question: "Can a client enforce a non-compete against a contractor in California?", answer: "Generally no. California's Business & Professions Code Section 16600 prohibits agreements that restrain a person from engaging in a lawful profession, trade, or business, with only narrow statutory exceptions (sale of a business, dissolution of a partnership). This prohibition applies to contractor agreements as well as employment agreements, and California courts will typically refuse to enforce non-compete restrictions against California-based contractors regardless of any out-of-state choice-of-law clause in the agreement." },
      { question: "Is a non-solicitation clause different from a non-compete, and is it easier to enforce against contractors?", answer: "A non-solicitation clause specifically prohibits the contractor from soliciting the client's customers or employees, without necessarily restricting competitive employment generally. Non-solicitation clauses are generally viewed as less restrictive than non-competes and are enforceable in most states—including some that refuse to enforce broad non-competes. For contractor agreements, a non-solicitation clause focused on specifically identified client relationships and employees is typically the most reliable post-engagement protection available." },
      { question: "If I sign a non-compete as a contractor, can I still serve other clients in the same industry?", answer: "It depends on the scope of the restriction. If the non-compete restricts you from working for 'direct competitors' of the client, the key question is how 'direct competitor' is defined. If the restriction covers anyone in the same industry, it is likely overbroad and may not be enforceable. If it covers a list of specifically named competitors or is limited to clients with substantially similar business models operating in the same market, the restriction is narrower and more likely to be enforced. Review the specific language carefully." },
      { question: "What should a contractor do when asked to sign a non-compete mid-engagement?", answer: "Before signing, determine what new consideration is being offered in exchange for the restriction—an extended engagement, a bonus, improved payment terms. If no additional consideration is offered beyond the existing engagement, the contractor should either decline to sign or negotiate for something in return. Consult an attorney in the relevant jurisdiction to evaluate the restriction's likely enforceability and consider negotiating narrower geographic scope, shorter duration, or a compensation arrangement during the restricted period." },
    ],
  },

}
