import { IntentBodyContent } from "./intent-body-content"

export const GROUP_A7: Record<string, IntentBodyContent> = {

  purchase_agreement_asset: {
    overview: [
      "An asset purchase agreement governs the acquisition of specific business assets—equipment, inventory, intellectual property, customer lists, contracts, and other defined property—without the buyer assuming the seller's corporate entity or all of its liabilities. Asset purchases are the dominant structure for small and mid-market business acquisitions because they allow buyers to select the assets they want, negotiate which liabilities they will assume, and start with a clean balance sheet rather than inheriting the seller's historic obligations. For sellers, asset sales involve more complex tax treatment than stock sales but may be required when the business is not organized as a separate legal entity or when the buyer insists on the cleaner liability profile that an asset structure provides.",
      "The asset schedule—the list of specific assets being transferred—is the most practically important exhibit to any asset purchase agreement. It must be comprehensive enough to capture all assets the buyer expects to receive while being specific enough to establish that certain assets (personal property of the seller, excluded contracts, retained cash) are not being transferred. Physical assets should be identified by description, serial number, and condition; intellectual property should be identified by registration number, jurisdiction, and ownership status; customer contracts should be identified by customer name, contract date, and remaining term. An asset schedule that is vague or incomplete generates disputes at closing about what was and was not sold.",
      "Liability assumption is the other side of the asset purchase coin. Unlike a stock purchase where the buyer inherits the entity and all its obligations, an asset buyer generally does not assume the seller's pre-existing liabilities. However, certain liabilities follow the assets regardless of the purchase agreement's language: tax liens and security interests that are perfected against specific assets, successor liability for environmental contamination associated with transferred property, and employment law claims under the WARN Act for mass layoffs in connection with asset transfers. The asset purchase agreement should explicitly identify which liabilities the buyer is assuming and which the seller is retaining, with appropriate representations from the seller about the completeness and accuracy of disclosed liabilities.",
      "Regulatory and consent requirements for asset transfers frequently create friction in the transaction timeline. Assignment of customer contracts requires counterparty consent if the contracts prohibit assignment. Transfer of professional licenses, government permits, or regulatory approvals may require advance application and approval that cannot be contractually short-circuited. Intellectual property assignments require recorded filings with the USPTO or Copyright Office to be effective against subsequent transferees. Lien releases from secured lenders must be coordinated with the payoff of any debt secured by the transferred assets. A well-structured asset purchase agreement identifies these requirements early, assigns responsibility for obtaining them, and includes closing conditions ensuring they are satisfied before the transaction closes.",
    ],
    howItWorks: [
      { step: "Define the Purchased Assets and Excluded Assets", description: "Attach a comprehensive schedule of all assets being transferred, organized by category (equipment, IP, contracts, inventory, customer lists, etc.). Separately list all excluded assets that the seller is retaining. Be specific: a vague description of 'all business assets' is insufficient because it creates disputes about what is included. Review the seller's financial statements and tax returns to identify all assets appearing on the balance sheet." },
      { step: "Specify the Purchase Price and Allocation", description: "State the total purchase price and break it down by asset category for tax purposes as required by IRS Section 1060 and Form 8594. The allocation affects both parties' tax treatment of the transaction—buyers typically prefer higher allocation to depreciable assets for immediate deduction; sellers may prefer capital gains treatment. Negotiate the allocation as part of the deal terms and document it as a binding agreement." },
      { step: "Identify Assumed and Excluded Liabilities", description: "List specifically which liabilities the buyer is assuming—specific customer contracts with their obligations, equipment leases, and any other defined obligations. Explicitly state that all other liabilities remain with the seller. Include seller representations about the completeness of disclosed liabilities and an indemnification obligation for liabilities that the seller failed to disclose or that arise from pre-closing activities." },
      { step: "Address Contract Assignment and Consent Requirements", description: "List all customer and vendor contracts being transferred and confirm whether each requires counterparty consent for assignment. Specify which party is responsible for obtaining consent, the deadline for obtaining consent, and the consequences if consent cannot be obtained before closing. Identify any contracts that will be operated under a transition arrangement pending consent." },
      { step: "Define Closing Conditions and Closing Mechanics", description: "List the conditions that must be satisfied before closing: seller representations remain true, no material adverse change has occurred, required consents have been obtained, liens on assets have been released, and regulatory approvals have been received. Describe the closing process, the documents to be delivered at closing (bill of sale, IP assignments, contract assignments, lien releases, seller closing certificate), and the payment mechanics." },
    ],
    legalConsiderations: [
      { title: "Bulk Sales Law Compliance", body: "Some states have bulk sales laws that require notice to the seller's creditors before a bulk transfer of business assets, giving creditors an opportunity to object. While many states have repealed bulk sales laws, some retain them for specific transaction types. Research whether your jurisdiction's bulk sales law applies to the transaction and comply with applicable notice requirements to protect the buyer against pre-existing creditor claims." },
      { title: "Successor Liability for Employment Claims", body: "Courts in some jurisdictions apply successor liability doctrine to hold asset purchasers responsible for the seller's pre-existing employment claims—wage and hour violations, discrimination claims, WARN Act obligations—particularly when the buyer continues the same business with the same workforce. The asset purchase agreement's liability allocation does not eliminate successor liability under applicable law; the buyer must conduct employment law due diligence and price the risk accordingly." },
      { title: "UCC Lien Search and Release", body: "Assets transferred in a business sale may be subject to security interests perfected by the seller's lenders. Conduct a UCC search against the seller in all jurisdictions where the seller is organized and where assets are located, and require the seller to obtain lien releases from all secured creditors before or at closing. An asset purchase agreement that closes without releasing existing security interests leaves the buyer with encumbered assets." },
      { title: "IP Assignment Recording Requirements", body: "Transfer of registered intellectual property—patents, trademarks, copyrights—is not legally effective against subsequent transferees until recorded with the applicable IP office. The USPTO requires trademark and patent assignments to be recorded within three months of execution for the assignment to be effective against subsequent purchasers. Include a post-closing covenant requiring the seller to cooperate with recording all IP assignments and to execute any additional documents needed to perfect the transfer." },
    ],
    commonMistakes: [
      { mistake: "Omitting Key Assets from the Asset Schedule", fix: "An incomplete asset schedule creates disputes at closing when the buyer discovers that assets expected to be included—domain names, social media accounts, pending customer orders, prepaid contracts—are not on the list. Review the seller's balance sheet, off-balance-sheet assets, and operational dependencies carefully and enumerate all assets the buyer expects to receive in the schedule." },
      { mistake: "Not Addressing Customer Contract Assignability Before Signing", fix: "Discovering after signing that key customer contracts require counterparty consent for assignment—and that consent will not be obtained—can derail a transaction or force a price reduction. Research contract assignability during due diligence and include appropriate closing conditions and walkaway rights if critical contracts cannot be assigned." },
      { mistake: "Ignoring the Tax Allocation Negotiation", fix: "The IRS requires buyers and sellers in business asset sales to file consistent purchase price allocations. A purchase agreement that does not document the agreed allocation invites inconsistent filings, IRS scrutiny, and potential penalties. Negotiate the allocation as part of the deal and include it in the purchase agreement as a binding commitment." },
      { mistake: "Accepting Vague Seller Representations About Liabilities", fix: "Seller representations about the completeness of disclosed liabilities are only as good as the seller's actual knowledge and the specificity of the representation. Require the seller to represent specifically that there are no claims, judgments, liens, or undisclosed obligations affecting the transferred assets, and back this with a meaningful indemnification obligation with an adequate retention period." },
      { mistake: "Not Including a Transition Services Agreement for Complex Businesses", fix: "Business asset acquisitions often require a transition period during which the seller provides certain services to the buyer—IT system access, employee support, customer relationship introductions. Without a transition services agreement, the buyer may lose access to critical support immediately at closing. Include a transition services agreement as a closing deliverable for any business with complex operational dependencies." },
    ],
    extendedFaq: [
      { question: "What is the difference between an asset purchase and a stock purchase?", answer: "In a stock purchase, the buyer acquires the seller's entire company by purchasing its equity interests—inheriting all assets, liabilities, contracts, and obligations regardless of what the parties may agree between themselves. In an asset purchase, the buyer selects specific assets to acquire and specifically identifies which liabilities to assume, leaving the rest with the seller. Asset purchases are preferred by buyers seeking a clean liability start and by transactions where the seller is not a separate legal entity. Stock purchases are simpler mechanically but require the buyer to assume all historic liabilities." },
      { question: "What assets can be transferred in an asset purchase?", answer: "Almost any business asset can be transferred: tangible assets (equipment, inventory, furniture, vehicles), real property (or real property leases), intellectual property (trademarks, patents, copyrights, trade secrets, domain names), customer contracts and relationships, vendor contracts, government permits and licenses (where transferable), website and social media accounts, telephone numbers, and goodwill. The key is identifying each asset specifically in the asset schedule rather than relying on general descriptions that generate closing disputes." },
      { question: "How does purchase price allocation work in an asset sale?", answer: "The IRS requires that the purchase price in a business asset acquisition be allocated among the acquired assets according to specified categories (Class I through Class VII) under Section 1060 of the Internal Revenue Code. Both buyer and seller must file Form 8594 (Asset Acquisition Statement) and use consistent allocations. Different asset categories have different tax treatment—ordinary income versus capital gains for the seller, and different depreciable lives and immediate expense treatment for the buyer. The allocation negotiation is as economically significant as the total purchase price itself." },
      { question: "What is a transition services agreement and when do I need one?", answer: "A transition services agreement (TSA) is a contract under which the seller provides the buyer with defined services for a defined period after closing—typically IT systems access, accounting support, human resources administration, and operational knowledge transfer. TSAs are appropriate when the buyer needs time to establish its own systems and capabilities before fully separating from the seller's infrastructure. The TSA specifies the services provided, the service period (commonly three to twelve months), pricing (cost-plus or fixed fee), and the standards to which services will be provided." },
    ],
  },

  purchase_agreement_vehicle_purchase: {
    overview: [
      "A vehicle purchase agreement documents the sale and purchase of a motor vehicle between a buyer and seller, establishing the agreed price, vehicle identification, payment terms, and the condition of the vehicle at the time of sale. Whether the transaction involves a private individual seller, a dealer, a business fleet sale, or an estate sale of a vehicle, a written purchase agreement protects both parties by creating an unambiguous record of the transaction terms and the vehicle's represented condition. Verbal vehicle sale agreements are enforceable in most states but routinely lead to disputes about price, included accessories, disclosed mechanical issues, and the completeness of the transfer documentation.",
      "The 'as is' versus warranted condition question is the central substantive issue in most vehicle purchase agreements. A private seller typically sells a used vehicle 'as is'—without warranty of merchantability or fitness for a particular purpose—meaning the buyer accepts the vehicle in its current condition and cannot return it for defects discovered after the sale. An 'as is' sale is effective only when clearly disclosed to the buyer before the transaction; a seller who conceals known material defects may face fraud liability regardless of 'as is' language. Dealer sales in most states are subject to the implied warranty of merchantability under the Uniform Commercial Code unless effectively disclaimed, and federal Magnuson-Moss Warranty Act requirements impose additional disclosure obligations for dealers selling vehicles with express written warranties.",
      "Title transfer is the legal mechanism by which vehicle ownership changes hands, and the purchase agreement must contemplate a clean title transfer to protect the buyer. The seller must deliver a title in their name, unencumbered by any lien (or with simultaneous lien release as part of the transaction), with the odometer disclosure properly completed and signed. The buyer's ability to register the vehicle and obtain insurance depends on receiving a clear title. Private sellers who do not hold clear title—because a lien from a prior auto loan has not been released—cannot legally transfer title and must resolve the lien before or as part of the sale. The purchase agreement should make clear title transfer a condition of the buyer's payment obligation.",
      "The odometer disclosure requirement is a federal legal obligation imposed on vehicle sellers by the Truth in Mileage Act—requiring an accurate written statement of the vehicle's odometer reading at the time of sale. Intentional falsification of the odometer reading is a federal crime subject to civil damages. The odometer disclosure must be in writing and must be signed by both the seller (certifying accuracy) and the buyer (acknowledging receipt). Most state vehicle titles include a built-in odometer disclosure section; for vehicles ten years old or older, the federal odometer disclosure requirement does not apply, though many states still require disclosure for all vehicle sales.",
    ],
    howItWorks: [
      { step: "Identify the Vehicle Precisely", description: "List the vehicle's year, make, model, trim level, color, VIN (seventeen characters), current license plate number, odometer reading at the time of agreement, and any distinguishing features or modifications. The VIN is the definitive identifier—include it on the agreement and verify it matches the vehicle, the title, and the registration before completing the transaction." },
      { step: "Document the Purchase Price and Payment Terms", description: "State the agreed total purchase price in dollars. Specify the payment method (cash, certified check, bank wire, financing through a named lender) and the timing—whether payment is made at signing, at delivery, or in installments if seller financing is provided. If a deposit was made to hold the vehicle, document the deposit amount, whether it is refundable if the transaction does not close, and how it applies to the purchase price." },
      { step: "Describe the Vehicle's Condition and Included Items", description: "State whether the vehicle is sold 'as is' without warranty or with any specific representations about condition. List any known defects that the seller is disclosing. Enumerate included items—keys, owner's manual, floor mats, spare tire, charging equipment for EVs, recent service records, or any personal property specifically included or excluded from the sale." },
      { step: "Complete the Odometer Disclosure", description: "Include a written odometer disclosure section in which the seller certifies the odometer reading is accurate and represents the actual mileage, and the buyer acknowledges receipt. If the odometer is known to be inaccurate, the seller must disclose that the reading does not reflect actual mileage and the seller's best estimate if the true mileage is known. Both parties sign the odometer disclosure." },
      { step: "Address Title Transfer and Delivery", description: "Confirm that the seller will deliver a clear title—in the seller's name, free of liens—upon receipt of the purchase price. If the vehicle has a lien, specify the arrangement for lien release (payoff from sale proceeds simultaneously with closing, lender coordination, etc.). Specify the date, location, and method of vehicle delivery and key transfer." },
    ],
    legalConsiderations: [
      { title: "Lemon Laws and Dealer Sales", body: "State lemon laws provide remedies for buyers of defective new vehicles—or in some states, used vehicles under warranty—who experience repeated failures of the same problem during the warranty period. Dealer sales of used vehicles may trigger lemon law protections if the vehicle is sold with an express warranty. Private sales of used vehicles without warranty are generally not subject to lemon law protections, but sellers who actively conceal known defects may face fraud claims regardless of lemon law applicability." },
      { title: "Implied Warranty Disclaimer Requirements", body: "Under the UCC, every sale of goods by a merchant carries an implied warranty of merchantability unless effectively disclaimed. A dealer who sells a vehicle 'as is' must use conspicuous disclaimer language—typically in all capital letters or a different font—that complies with UCC Section 2-316 requirements. Inadequate disclaimer language may leave the implied warranty intact, exposing the dealer to merchantability claims for vehicles that do not meet ordinary standards of quality." },
      { title: "Sales Tax and Registration Obligations", body: "Vehicle sales trigger state and local sales tax obligations. The buyer is typically responsible for paying sales tax when registering the vehicle in their state. The purchase agreement's stated price is the basis for tax calculation. Understating the purchase price in the agreement to reduce the buyer's tax obligation while making a separate cash payment is tax fraud. Both buyer and seller should accurately reflect the actual transaction price." },
      { title: "Dealer Disclosure Requirements", body: "Federal and state laws impose specific disclosure requirements on vehicle dealers: the FTC Used Car Rule requires dealers to display a Buyers Guide disclosing the warranty status of every used vehicle; federal law requires disclosure of material defects; state laws may require additional disclosures about prior rental use, frame damage, flood damage, or salvage title history. Private sellers typically have fewer mandatory disclosure requirements, though affirmative fraud is prohibited regardless of the seller's identity." },
    ],
    commonMistakes: [
      { mistake: "Paying Before Receiving Clear Title", fix: "Paying the full purchase price before confirming clear title transfer leaves the buyer exposed if the seller cannot deliver a lien-free title—the money is paid, the vehicle cannot be registered, and recovering the payment may require litigation. Structure payment simultaneously with title delivery, or use an escrow arrangement where the title is verified before funds are released." },
      { mistake: "Not Checking the Vehicle History Report", fix: "A VIN-based vehicle history report (Carfax, AutoCheck) reveals accident history, odometer discrepancy, prior salvage or flood title designation, and ownership history. Buyers who skip this step sometimes purchase vehicles with undisclosed significant damage or fraudulent odometer readings. Review the history report before signing any purchase agreement." },
      { mistake: "Overlooking the 'As Is' Disclosure", fix: "A seller who wants to sell a vehicle as is must ensure the buyer understands this before the transaction—a clear 'AS IS' designation in the purchase agreement, acknowledged by the buyer's signature, is essential. A buyer who later claims they did not understand 'as is' language can challenge the effectiveness of the disclaimer if it was not clearly communicated before the sale." },
      { mistake: "Not Completing the Title Properly at the Time of Sale", fix: "Vehicle titles must be properly endorsed at the time of sale—seller signs the appropriate seller's signature line, odometer disclosure is completed, and buyer's information is filled in. Titles that are signed later or left blank ('open titles') create chain of title problems and can be misused by intermediaries in curbstoner operations. Complete the title properly at the moment of sale." },
      { mistake: "Forgetting to Cancel Insurance and Return License Plates", fix: "After selling a vehicle, the seller should cancel their insurance and, in states that require it, return the license plates to the DMV before canceling registration. A seller who fails to notify the DMV of the sale and cancel insurance may receive traffic violations or liability claims incurred by the buyer after the sale date. File the DMV release-of-liability form on the sale date to limit this exposure." },
    ],
    extendedFaq: [
      { question: "Do I need a written purchase agreement for a private vehicle sale?", answer: "While verbal vehicle sale agreements are enforceable in most states, a written agreement is strongly recommended because it creates an unambiguous record of the price, vehicle identification, 'as is' status, and odometer disclosure. Without a written agreement, disputes about what was promised—what condition the seller represented, what accessories were included, whether the buyer accepted the vehicle as is—have no documentary foundation and often become credibility contests." },
      { question: "What is an 'as is' vehicle sale and does it protect the seller from all claims?", answer: "An 'as is' sale means the buyer accepts the vehicle in its current condition without any warranty from the seller about fitness, merchantability, or freedom from defects. The 'as is' designation effectively transfers the risk of discovered defects from seller to buyer. However, 'as is' does not protect a seller who actively conceals known material defects or makes affirmatively false statements about the vehicle's condition—fraud claims survive 'as is' disclaimers in virtually all states." },
      { question: "What should I do if the seller cannot provide a clear title?", answer: "Do not complete the purchase until the seller resolves the title issue. A vehicle without clear title cannot be registered in the buyer's name. If the seller has an outstanding loan on the vehicle, the lender must release the lien as part of the transaction. The safest approach is to use an escrow or closing service that holds the buyer's funds while the lender releases the title, ensuring neither party is at risk during the lien payoff process." },
      { question: "How is an odometer disclosure completed for a vehicle sale?", answer: "The odometer disclosure is typically completed on the vehicle's title document itself. The seller certifies the current odometer reading and affirms it accurately reflects the vehicle's actual mileage (or discloses any known inaccuracy). Both seller and buyer sign the odometer disclosure. For vehicles that changed hands multiple times or for which the title's odometer section is full, a separate federal odometer disclosure statement may be required. Federal disclosure requirements do not apply to vehicles ten model years old or older." },
    ],
  },

  purchase_agreement_business_assets: {
    overview: [
      "A business assets purchase agreement is the legal instrument through which all or substantially all of the operating assets of a business—its equipment, inventory, intellectual property, goodwill, customer relationships, and ongoing contracts—are transferred from a seller to a buyer as part of an ongoing business acquisition. Unlike a partial asset purchase targeting specific equipment or IP, a business assets purchase agreement contemplates the comprehensive transfer of a functioning enterprise's underlying property in a way that allows the buyer to continue operating the business without interruption. This type of agreement is the primary legal instrument for main street business acquisitions—small restaurants, retail stores, service businesses, and professional practices—where the buyer is purchasing the operating business rather than just discrete assets.",
      "Business goodwill is often the most economically significant asset in a business acquisition and the most difficult to define and value. Goodwill encompasses the business's reputation, customer loyalty, established market position, trained workforce, proprietary processes, and competitive advantages that generate earnings above a normal return on tangible assets. The purchase agreement must address how goodwill is transferred—through non-compete obligations that prevent the seller from immediately re-establishing competing customer relationships, through transition assistance that introduces the buyer to key customers, and through the seller's assistance in maintaining continuity during the handover period. A seller who receives a premium for goodwill and then immediately competes destroys the value that premium represented.",
      "Employee matters in a business assets purchase are particularly complex because asset sales do not automatically transfer employment relationships. Unlike a stock purchase where the workforce remains employed by the same entity, an asset buyer must affirmatively hire the seller's employees—often a subset of them—and do so in compliance with applicable labor laws. If the buyer plans to hire fewer than all of the seller's employees, the seller may have WARN Act obligations if the workforce reduction meets the threshold for notice requirements. The purchase agreement must address which employees the buyer intends to hire, the compensation and benefits offered, and the seller's responsibility for employment-related liabilities up to the closing date.",
      "Financing a business assets purchase frequently involves a Small Business Administration (SBA) loan, seller financing, or a combination. SBA 7(a) loans are the dominant financing tool for small business acquisitions and impose specific requirements on the purchase agreement structure, the assets being acquired, the purchase price allocation, and the terms of any seller financing. SBA lending programs require the seller to finance a portion of the purchase price on full standby for a defined period (typically two years) and impose restrictions on the buyer's use of proceeds. Understanding SBA requirements before structuring the purchase agreement prevents costly document revisions after a lender has been identified.",
    ],
    howItWorks: [
      { step: "Conduct Pre-Agreement Due Diligence", description: "Before drafting the purchase agreement, review the seller's financial statements for three to five years, tax returns, customer contracts, vendor relationships, equipment condition reports, lease agreements, employee records, and any litigation or regulatory history. Identify key value drivers, confirm that major customer relationships are transferable, and assess the adequacy of the purchase price relative to the business's actual performance." },
      { step: "Structure the Purchase Price and Consideration", description: "Determine the total purchase price based on due diligence findings. Specify how it will be paid: all cash at closing, cash plus seller financing (note payable), cash plus an earnout tied to post-closing performance, or SBA-financed. Allocate the purchase price across asset categories for IRS Section 1060 compliance. Include any working capital adjustment mechanism that normalizes the price for fluctuations in inventory or receivables between signing and closing." },
      { step: "Define All Transferred Assets Comprehensively", description: "Attach an asset schedule covering every asset category: equipment and fixtures (by description and serial number), inventory (valued at cost or as determined by physical count at closing), intellectual property (trademarks, domain names, recipes, formulas, software), lease rights (landlord consent requirement addressed), customer and vendor contracts (assignability confirmed), goodwill, business name, telephone numbers, and website." },
      { step: "Address Non-Compete and Transition Obligations", description: "Require the seller to execute a non-compete agreement restricting competition for a defined period and geography, and a non-solicitation agreement restricting approach to transferred customers and employees. Include a transition services obligation requiring the seller to introduce the buyer to key customers and vendors, train the buyer in operational processes, and remain available for a defined consultation period after closing." },
      { step: "Document Employee and License Transfer Plans", description: "Identify which employees the buyer will offer employment to, the terms of the offer, and the effective date of the new employment. Address which business licenses, permits, and registrations must be transferred or re-obtained by the buyer. Include a closing condition requiring all material licenses necessary for ongoing operations to be in place before the transaction closes." },
    ],
    legalConsiderations: [
      { title: "WARN Act Obligations in Asset Sales", body: "The federal WARN Act requires employers with one hundred or more employees to provide sixty days advance notice of plant closings or mass layoffs affecting fifty or more employees. Asset acquisitions that involve closing the seller's business or significantly reducing the workforce may trigger WARN Act notice obligations. The purchase agreement should allocate WARN Act compliance responsibility between seller and buyer based on which party is causing the workforce change." },
      { title: "Lease Assignment and Landlord Consent", body: "A business's physical location lease is often its most important and most difficult-to-assign asset. Most commercial leases prohibit assignment without landlord consent. A buyer who assumes operations in the seller's location without obtaining the landlord's written consent to the lease assignment—or a new lease from the landlord—occupies the space as an unauthorized subtenant, potentially subject to eviction. Make landlord consent to lease assignment a closing condition and begin that conversation early." },
      { title: "Liquor License and Regulated Business Transfers", body: "Businesses that operate under regulated licenses—liquor licenses, medical licenses, financial services licenses, childcare licenses—face specific regulatory approval requirements for ownership transfers. Many liquor license jurisdictions require the new owner to apply for and receive a new license before operating; the seller's license cannot simply be transferred. Build regulatory approval timelines into the purchase agreement's closing schedule and include appropriate closing conditions." },
      { title: "Accounts Receivable Collection and Risk", body: "Businesses with significant outstanding receivables must address whether those receivables are included in the purchase (with the buyer collecting them) or retained by the seller (who collects pre-closing accounts). Including receivables creates a risk of uncollectable accounts that reduce the effective purchase price. Many business acquisitions exclude receivables and allow the seller to collect them post-closing, with an arrangement for the buyer to forward payments received in error." },
    ],
    commonMistakes: [
      { mistake: "Closing Before Landlord Consent Is Obtained", fix: "Closing a business acquisition without the landlord's written consent to lease assignment—or a replacement lease—leaves the buyer operating in the location without a valid lease. The landlord can terminate the tenancy as soon as the unauthorized occupancy is discovered. Make landlord consent a closing condition that must be satisfied before any funds are released." },
      { mistake: "Using a Rule-of-Thumb Valuation Without Earnings Analysis", fix: "Many small business acquisitions are priced based on industry multiples of revenue or 'seller's discretionary earnings' without verifying the underlying financial performance. Engage a business valuation professional or CPA to verify the earnings presented by the seller before agreeing to a purchase price. Buyer overpayment based on inflated or unverified financial representations is the most common source of post-acquisition regret." },
      { mistake: "Not Including a Working Capital Adjustment", fix: "Inventory levels, receivables, and current liabilities fluctuate between signing and closing. Without a working capital adjustment mechanism, a seller who depletes inventory or allows receivables to age between signing and closing transfers a business worth less than what the buyer agreed to pay. Include a target working capital amount and a post-closing adjustment mechanism to normalize the purchase price for actual working capital at closing." },
      { mistake: "Failing to Address Training and Knowledge Transfer", fix: "The seller's proprietary knowledge—recipes, operational processes, supplier relationships, customer preferences—may not be documented anywhere and exists only in the seller's head. Without a contractual training obligation, the buyer may acquire the assets but not the knowledge needed to operate the business. Require a defined number of post-closing training days from the seller as part of the transaction." },
      { mistake: "Not Verifying Equipment Condition Before Closing", fix: "Equipment listed in the asset schedule may be in different condition at closing than at due diligence, particularly if the seller has reduced maintenance knowing the business is being sold. Conduct a final physical inspection of all equipment shortly before closing and include a representation that equipment will be in the same material condition at closing as at the due diligence date, with appropriate remedies if it is not." },
    ],
    extendedFaq: [
      { question: "What is the difference between buying a business's assets versus buying the business itself?", answer: "Buying a business's assets means purchasing the operating property—equipment, inventory, contracts, IP, goodwill—while leaving the seller's legal entity intact with its historic liabilities. Buying the business itself (a stock purchase or membership interest purchase) means acquiring the entire entity, including all its historic assets and liabilities. Asset purchases allow buyers to select what they want and negotiate which liabilities to assume; stock purchases transfer everything regardless of what the parties agree, though the seller remains liable for pre-closing obligations under the entity's own law." },
      { question: "Do I need to re-hire the seller's employees in a business asset purchase?", answer: "Yes. Employees are not automatically transferred in an asset purchase—you must make new offers of employment to the employees you want to retain. You can hire all, some, or none of the seller's employees, and you can offer different compensation and benefits than the seller provided. However, employment law—including potential discrimination claims if you hire selectively based on protected characteristics—applies to your hiring decisions. If a significant number of employees are not offered positions, the seller may have WARN Act notice obligations." },
      { question: "Can I use an SBA loan to purchase a small business's assets?", answer: "Yes. The SBA 7(a) loan program is the most common financing vehicle for small business acquisitions, including asset purchases. SBA loans can finance goodwill, equipment, inventory, and other business assets. The SBA program has specific requirements: the seller must be a US citizen or permanent resident, the business must meet SBA size standards, the purchase price and terms must be reasonable, and any seller financing must typically be on standby for a defined period. Work with an SBA-approved lender early in the transaction process to understand program requirements." },
      { question: "What is an earnout and when should it be included in a business acquisition?", answer: "An earnout is a contingent purchase price provision that pays the seller additional compensation if the business achieves defined performance milestones—revenue targets, EBITDA thresholds, customer retention metrics—in the periods following closing. Earnouts are used when buyer and seller disagree about the business's future earnings potential: the buyer's lower valuation is satisfied upfront, and the seller receives additional compensation if their optimistic projection proves correct. Earnouts are complex and frequently litigated; they require precise metric definition, buyer obligation to operate the business in ways that allow earnout achievement, and clear audit rights." },
    ],
  },

  last_will_testament_simple: {
    overview: [
      "A simple will is a straightforward testamentary document through which an individual—the testator—expresses their wishes for the distribution of their estate after death, names a personal representative to administer the estate, and, if applicable, designates guardians for minor children. The 'simple' designation reflects the uncomplicated nature of the estate plan rather than the legal significance of the document—a simple will is just as legally binding as a complex will with multiple trusts. Simple wills are appropriate for testators with uncomplicated asset structures, no minor children (or clear guardian preferences), no complex tax planning needs, and straightforward distribution intentions—typically leaving everything to a spouse, then to children, or to a defined list of beneficiaries.",
      "The minimum legal requirements for a valid will vary by state but generally include: the testator must be of legal age (typically eighteen, with some states permitting younger married persons or military members to make wills); the testator must have testamentary capacity—understanding the nature of the act, the extent of their estate, and the natural objects of their bounty; the will must be in writing (oral wills are recognized only in extremely limited circumstances in a few states); the testator must sign the will; and the will must be witnessed by the required number of disinterested witnesses (typically two in most states, three in some jurisdictions). A will that fails to meet these formal requirements may be denied probate, leaving the estate to pass under the state's intestacy laws regardless of the testator's expressed wishes.",
      "Residuary estate planning is the backbone of a simple will. The residuary estate is everything the testator owns that is not specifically bequeathed to a named recipient—typically the largest component of the estate. A well-drafted simple will names the primary residuary beneficiary (commonly a spouse or significant other), the contingent residuary beneficiary (commonly children or other family members) if the primary beneficiary predeceases the testator, and the default distribution if all named beneficiaries predecease the testator. Without a clear residuary clause covering every contingency, the residue may pass under the state's intestacy statute—potentially to parties the testator would not have chosen.",
      "A simple will takes effect through the probate process—a court-supervised procedure for validating the will, appointing the personal representative, inventorying and valuing assets, paying debts and taxes, and distributing the estate to beneficiaries. Probate is a public process, a delay (typically six months to a year or more), and an expense that varies by state. Assets that pass outside of probate—jointly held property with right of survivorship, accounts with beneficiary designations (retirement accounts, life insurance, POD bank accounts), and assets held in a revocable trust—are not governed by the will and are not subject to the probate process. Understanding which assets pass through the will versus outside of it is essential for ensuring the will accomplishes the testator's overall distribution objectives.",
    ],
    howItWorks: [
      { step: "Identify Personal Information and Family Structure", description: "State the testator's full legal name, current address, and marital status. Identify all children, including minors and adult children from all relationships, by full name and date of birth. Confirm whether any prior wills or codicils exist and that this will revokes all prior testamentary instruments. This foundational information establishes the testator's family context and the individuals who have an interest in the estate distribution." },
      { step: "Name the Personal Representative", description: "Designate the executor (personal representative) who will administer the estate—collecting assets, paying debts, filing tax returns, and distributing the estate to beneficiaries. Name a successor executor in case the primary cannot serve. Specify whether the executor is required to post a surety bond (most spouses and adult children waive bond requirements) and whether the executor has full power to sell or manage estate assets without court approval." },
      { step: "Make Specific Bequests", description: "List any specific bequests—particular items of property or defined dollar amounts going to specific beneficiaries. Common specific bequests include jewelry, heirlooms, family collections, charitable gifts, and defined dollar amounts to specific individuals. Specific bequests are satisfied before the residuary estate is distributed; if the estate cannot satisfy all specific bequests, they are reduced proportionally (ademption by extinction)." },
      { step: "Define the Residuary Estate Distribution", description: "State who receives everything not otherwise specifically bequeathed. The most common structure: 'All the rest, residue, and remainder of my estate to [spouse], if they survive me; if not, to my children in equal shares, per stirpes.' 'Per stirpes' means a deceased child's share passes to that child's children rather than lapsing. Define all contingencies through at least two levels of beneficiary succession." },
      { step: "Execute with Required Formalities", description: "Sign the will in the presence of two (or three) disinterested witnesses who each sign the will in the testator's presence and in each other's presence, confirming that the testator appeared to be of sound mind and signed voluntarily. Add a self-proving affidavit—a notarized statement by the testator and witnesses affirming the will's validity—to simplify probate by eliminating the need to locate witnesses after death." },
    ],
    legalConsiderations: [
      { title: "Holographic Wills and Witnessed Wills", body: "Approximately thirty states recognize holographic wills—wills entirely handwritten and signed by the testator, without witnesses. While holographic wills are valid in those states, they carry significant risks: handwriting authentication at probate, absence of counsel review, and frequent failure to address contingencies. A formally witnessed and notarized will is more reliable and is accepted in all states regardless of whether holographic wills are recognized locally." },
      { title: "Pretermitted Heir Statutes", body: "Most states have pretermitted heir statutes providing that children born or adopted after a will is executed—and not otherwise provided for in the will—receive a share of the estate as if the testator died without a will. Including language in the simple will that specifically addresses after-born children—either providing for them or intentionally disinheriting them—prevents unintended consequences from pretermitted heir statutes." },
      { title: "Per Stirpes vs. Per Capita Distribution", body: "The distribution method for beneficiary shares when a beneficiary predeceases the testator affects which family members ultimately receive the estate. Per stirpes (by representation) passes a deceased beneficiary's share to that person's descendants. Per capita divides the estate equally among surviving beneficiaries at the same generational level. Specify the intended distribution method explicitly rather than relying on default rules that vary by state." },
      { title: "No-Contest Clauses", body: "A no-contest (in terrorem) clause disinherits any beneficiary who challenges the will's validity in court. These clauses are enforceable in most states but are ineffective if the challenging party had probable cause for the challenge. Including a no-contest clause may discourage minor disputes but will not deter challenges supported by legitimate evidence of incapacity or undue influence." },
    ],
    commonMistakes: [
      { mistake: "Not Updating the Will After Major Life Changes", fix: "Marriage, divorce, birth of children, death of named beneficiaries, significant asset acquisition, and relocating to a new state are all events that warrant will review and potential revision. A will executed before marriage that does not address the new spouse may not provide for them as intended, and some states provide that marriage automatically revokes a prior will. Review the will every three to five years and after any major life change." },
      { mistake: "Leaving Assets Outright to Minors", fix: "Minor children cannot legally own significant assets outright. Assets left directly to a minor child will typically be managed by a court-appointed guardian of the property until the child reaches majority—usually eighteen—at which point the full inheritance is distributed regardless of the child's maturity. Use a custodial arrangement under the Uniform Transfers to Minors Act or a testamentary trust to delay distribution to an age when the beneficiary is more likely to manage the inheritance responsibly." },
      { mistake: "Relying on the Will for All Asset Distribution", fix: "Assets with beneficiary designations (retirement accounts, life insurance, POD bank accounts) and jointly titled property pass outside the will regardless of what the will says. A will that says 'I leave everything to my spouse' does not override a 401(k) beneficiary designation naming a prior spouse. Review all beneficiary designations to ensure they align with the overall estate plan intent." },
      { mistake: "Having the Will Witnessed by a Beneficiary", fix: "Many states prohibit interested witnesses—beneficiaries named in the will—from serving as witnesses, and may void or reduce the bequest to a witness-beneficiary even if the rest of the will is valid. Always use disinterested witnesses who receive nothing under the will and have no conflict of interest in the estate distribution." },
      { mistake: "Not Adding a Self-Proving Affidavit", fix: "A self-proving affidavit—a notarized statement by the testator and witnesses appended to the will—simplifies probate by substituting for witness testimony at the probate proceeding. Without a self-proving affidavit, the probate court may require the witnesses to appear and testify, creating delays when witnesses cannot be located years or decades after the will was executed. Add the affidavit at the time of execution when the witnesses and notary are all present." },
    ],
    extendedFaq: [
      { question: "Does a simple will avoid probate?", answer: "No. A will is a probate instrument—it takes effect through the probate process, which requires court supervision to validate the will and authorize distribution of estate assets. Probate can be time-consuming (six months to two years in many states), public (wills become public record when filed for probate), and expensive (probate fees and costs reduce the estate). Assets that pass outside the will—beneficiary-designated accounts, jointly titled property, and assets in a revocable trust—avoid probate. A simple will governs assets in the probate estate; other planning tools are needed to minimize the probate estate." },
      { question: "What happens if I die without a will?", answer: "Dying without a valid will—called dying intestate—means your estate passes under your state's intestacy laws, which prescribe a fixed distribution formula regardless of your wishes. Intestate distribution typically favors spouses and children according to defined shares, but may result in outcomes the decedent would not have chosen: sharing assets with parents when the decedent wanted everything to go to a spouse, unequal treatment of blended family children, or assets going to estranged relatives rather than close friends or charities the decedent cared about." },
      { question: "Can I change my will after I sign it?", answer: "Yes. A will can be revoked and replaced at any time while the testator has testamentary capacity. To make changes to an existing will, you can execute a codicil—a formal amendment to the will that must be executed with the same formalities as the original—or revoke the existing will entirely and execute a new one. Making handwritten changes to a signed will without following proper amendment procedures typically does not create a valid modification and may create ambiguity that complicates probate." },
      { question: "Who should I choose as my executor?", answer: "Your executor (personal representative) should be trustworthy, organized, available, and willing to serve. The executor handles the practical and legal work of administering your estate: locating and inventorying assets, notifying creditors, paying valid debts, filing estate and final income tax returns, and distributing the estate to beneficiaries. For most people, a trusted spouse, adult child, or close friend with good organizational skills is appropriate. For complex estates, a professional executor (bank or trust company) may be preferred. Always name a backup executor in case the primary cannot serve." },
    ],
  },

  last_will_testament_guardian: {
    overview: [
      "A guardian designation will is a testamentary document whose primary purpose—from the testator's practical perspective—is to nominate a guardian for their minor children in the event both parents die or become legally incapacitated before the children reach adulthood. While a complete will also distributes property and names an executor, parents with young children often rank guardian nomination as their most urgent estate planning concern, because the alternative—a court choosing a guardian without the parents' expressed guidance—may result in the children being raised by someone the parents would never have selected. Courts are not required to follow a will's guardian nomination, but they give significant weight to it as evidence of parental intent.",
      "The selection of a guardian requires careful consideration of a complex set of factors that go well beyond who loves the children most. The nominee's parenting philosophy, religious and cultural values, educational approach, financial stability, relationship with the children, geographic location, age and health, family situation (whether they have children of their own and how the children would integrate into that family), and willingness to serve are all relevant considerations. The financial capacity to raise additional children is addressed separately through life insurance and testamentary trusts, so it need not be a disqualifying factor if the guardian is otherwise the best choice. Critically, the guardian should be asked and should confirm their willingness to accept the responsibility before being named.",
      "Separating the role of guardian from the role of financial trustee is often the most sophisticated decision in a guardian designation will. The guardian provides daily care for the children—housing, emotional support, education, and parenting—while the trustee manages the financial assets held in trust for the children's benefit. These roles can be held by the same person, but separating them provides a system of checks and balances: the guardian can focus on parenting without the distraction of investment management, and the trustee can make objective financial decisions without the emotional dynamics of daily caregiving. Many estate planning attorneys recommend this separation, particularly when the most appropriate guardian is not the most financially sophisticated person in the family.",
      "A guardian designation in a will must be accompanied by adequate financial provision for the children's care. The guardian nominee must actually be able to support the children financially, either through the estate's assets or through life insurance proceeds channeled through a testamentary trust. The will should establish a testamentary trust that holds all assets for the children's benefit, names a trustee to manage the funds, specifies distribution standards (health, education, maintenance, and support—the HEMS standard), and provides for distribution of the remaining trust assets when the children reach a defined age of maturity. Parents who name a guardian without funding the guardianship create an unfunded caregiving obligation that may be declined by the nominee.",
    ],
    howItWorks: [
      { step: "Nominate a Primary Guardian and Successor", description: "Name the person you want to serve as guardian of your children's persons—the individual who will have day-to-day custody and caregiving responsibility. Provide the nominee's full legal name, address, and relationship to the testator. Name a successor guardian who will serve if the primary nominee predeceases the testator, is unwilling to serve, or is found by the court to be unsuitable." },
      { step: "State Guidance for the Guardian and the Court", description: "Include a section providing the court and guardian with guidance about your values, parenting intentions, educational preferences, religious upbringing, and any specific circumstances affecting specific children. While courts are not legally bound by these preferences, providing context gives the guardian a roadmap for raising the children consistent with the parents' intentions and gives the court insight into the parents' genuine wishes." },
      { step: "Establish a Testamentary Trust for Minor Children", description: "Create a testamentary trust within the will to hold assets for the benefit of the minor children. Name a trustee—who may or may not be the same as the guardian—to manage and invest the trust assets. Define the trustee's distribution authority (HEMS standard or broader discretion), investment powers, and administrative provisions. Specify the age at which the trust terminates and assets are distributed outright to the children." },
      { step: "Fund the Trust Through the Residuary Estate and Life Insurance", description: "Direct all residuary estate assets to the testamentary trust. Separately, review and update life insurance policies and retirement account beneficiary designations to name the testamentary trust (or a pour-over trust) as beneficiary. Coordinate the will with the overall estate plan to ensure that assets flow into the trust rather than passing to minor children outright or through other channels that bypass the trust protection." },
      { step: "Address Separate Property for Each Child", description: "If children have different needs—a child with special needs requiring a supplemental needs trust structure, older children approaching majority, children from different relationships—address each child's situation specifically. Include provisions maintaining the children as a unit while they are young, with provisions for splitting assets as children reach adulthood or separate life milestones." },
    ],
    legalConsiderations: [
      { title: "Court Discretion in Guardian Appointments", body: "A will's guardian nomination is strong evidence of parental preference but not binding on the court. The court's overriding standard is the child's best interests—a court can override the parents' nomination if it finds that the nominated guardian is unfit, that another arrangement better serves the child, or that the child (of sufficient age) strongly objects to the nomination. Parents who are concerned about the risk of judicial override should nominate the most clearly appropriate person and document their reasoning." },
      { title: "Guardians for Children with Special Needs", body: "Children with physical, intellectual, or developmental disabilities may require guardians who have specific experience, resources, and commitment to special needs caregiving. A testamentary trust for a child with special needs must be structured as a supplemental needs trust (SNT) to preserve the child's eligibility for government benefit programs like Medicaid and SSI. A standard support trust that provides housing, food, and basic needs will disqualify the child from these programs, significantly reducing the resources available for their lifetime care." },
      { title: "International Guardian Considerations", body: "Nominating a guardian who lives in a different country raises complex practical and legal issues: which country's court has jurisdiction over guardianship proceedings, what documentation establishes the international guardian's authority, and what immigration status is required for the children to live with the guardian abroad. International guardian nominations should be reviewed by an attorney familiar with both the testator's jurisdiction and the proposed guardian's country." },
      { title: "Divorce and Guardian Nominations", body: "When parents divorce, the surviving parent typically assumes full custody upon the other parent's death—the guardian nomination in a will does not override the surviving parent's custodial rights. A guardian nomination becomes operative primarily when both parents have died or are legally incapacitated. Parents who have concerns about the other parent's fitness or parenting capabilities cannot use a will to prevent the surviving parent from having custody; that requires family court proceedings during the parents' lifetimes." },
    ],
    commonMistakes: [
      { mistake: "Nominating a Guardian Without Asking Them First", fix: "Discovering that a nominated guardian is unwilling or unable to serve at the moment the children need a guardian—after the parent's death—creates an immediate legal and practical crisis. Have a direct conversation with your nominee, explain the responsibility, confirm their willingness, and revisit the conversation periodically as circumstances change. Name a successor nominee in case the primary's circumstances change." },
      { mistake: "Naming the Same Person as Guardian and Trustee Without Considering the Conflict", fix: "When the guardian and trustee are the same person, the children have no advocate separate from the person managing their money. The guardian-trustee can make financial decisions that benefit themselves (lower distributions, retaining assets longer) without independent oversight. Consider naming a different, financially sophisticated person as trustee to provide a check on the guardian's financial decisions." },
      { mistake: "Not Funding the Guardianship Through Life Insurance", fix: "A guardian nomination without financial resources to support the children creates a caregiving obligation that the guardian may be unable or unwilling to fulfill. Purchase adequate term life insurance covering the period until the youngest child reaches adulthood and designate the testamentary trust as the beneficiary. The trust provides the trustee with resources to compensate the guardian for caregiving expenses." },
      { mistake: "Leaving Assets Outright to Children at Age Eighteen", fix: "Leaving significant assets outright to an eighteen-year-old is often not in the child's best interests. A testamentary trust can delay full distribution to age twenty-five, thirty, or a defined milestone like college graduation. Include intermediate distribution provisions—a portion at twenty-one, another portion at twenty-five—to provide access to funds while limiting the risk of a single large inheritance being mismanaged at too young an age." },
      { mistake: "Not Updating the Guardian Nomination as Family Circumstances Change", fix: "The person best suited to serve as guardian when children are infants may not be the best choice ten years later as circumstances—health, marital status, financial situation, geographic location, relationship with the children—change. Review the guardian nomination every three to five years and update it when the nominated guardian's circumstances change significantly." },
    ],
    extendedFaq: [
      { question: "What happens to my children if both my spouse and I die without naming a guardian?", answer: "If both parents die without a valid will naming a guardian, a court will appoint one based on the best interests of the children. The court typically considers relatives—grandparents, aunts and uncles, adult siblings—based on their relationship to the children, financial stability, and fitness. The court may not choose the person you would have chosen, and the proceedings are often delayed, emotionally difficult for the children, and expensive. Naming a guardian in your will is the most direct way to express your preference and give that preference legal weight." },
      { question: "Can I name different guardians for different children?", answer: "Yes, though splitting siblings between different guardians is generally discouraged because it separates children from each other at an already difficult time. However, if children have significantly different needs—one child has special needs requiring specialized care—different guardian nominations may be appropriate. Explain your reasoning in the will so the court understands why splitting the children serves their individual best interests." },
      { question: "How much life insurance do I need to fund a guardianship?", answer: "A rough rule of thumb is enough to provide the children's annual living and education costs from the parents' death through each child's completion of college. Calculate the estimated annual cost of raising each child (including education, healthcare, activities, and housing cost contribution) multiplied by the number of years remaining until adulthood, then add a buffer for inflation and extraordinary needs. A fee-only financial planner can help model the appropriate coverage amount based on your specific family's costs and circumstances." },
      { question: "What is the difference between a guardian of the person and a guardian of the estate?", answer: "A guardian of the person is responsible for the child's daily care, housing, education, healthcare decisions, and upbringing. A guardian of the estate (or property guardian) manages financial assets belonging to the child. These roles are typically held by the same person in a guardian nomination, but they can be separated—and often should be, when the best caregiver is not the best financial manager. When a testamentary trust is established, the trustee replaces the guardian of the estate, holding and managing the trust assets for the children's benefit under the trust's terms rather than court supervision." },
    ],
  },

}
