import type { Metadata } from "next"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { Card, CardContent } from "@/components/ui/card"
import { FileText } from "lucide-react"

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Read the Terms of Service for LegalLawDocs.com. Understand the rules and conditions governing your use of our AI-powered legal document generation platform.",
  openGraph: {
    title: "Terms of Service | LegalLawDocs.com",
    description:
      "Understand the rules and conditions governing your use of LegalLawDocs.com.",
  },
  alternates: {
    canonical: "https://www.legallawdocs.com/terms-of-service",
  },
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen">
      <Header />
      <main>
        {/* Hero */}
        <section className="relative border-b border-border/40 bg-gradient-to-b from-primary/5 to-background">
          <div className="mx-auto max-w-4xl px-4 py-16 text-center lg:px-8 lg:py-24">
            <div className="mx-auto mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 border border-primary/20">
              <FileText className="h-7 w-7 text-primary" />
            </div>
            <h1 className="font-serif text-4xl font-bold text-foreground lg:text-5xl">
              Terms of Service
            </h1>
            <p className="mt-4 text-lg text-muted-foreground">
              Last updated: March 14, 2026
            </p>
          </div>
        </section>

        {/* Content */}
        <section className="mx-auto max-w-4xl px-4 py-12 lg:px-8 lg:py-20">
          <Card className="border-border/40">
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none p-8 lg:p-12">
              <p className="text-muted-foreground leading-relaxed">
                These Terms of Service (&quot;Terms&quot;) govern your access to and use of
                the LegalLawDocs.com platform and services (&quot;Service&quot;) operated by
                LegalLawDocs.com (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). By accessing or using our
                Service, you agree to be bound by these Terms. If you do not agree,
                please do not use our Service.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                1. Acceptance of Terms
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                By creating an account or using any part of our Service, you
                acknowledge that you have read, understood, and agree to be bound by
                these Terms and our{" "}
                <Link href="/privacy-policy" className="text-primary hover:underline">
                  Privacy Policy
                </Link>
                . If you are using the Service on behalf of an organization, you
                represent and warrant that you have the authority to bind that
                organization to these Terms.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                2. Description of Services
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                LegalLawDocs.com provides an AI-powered platform for generating legal
                documents. Our Service allows users to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Generate legal documents using customizable templates powered by artificial intelligence</li>
                <li>Access a library of document templates across multiple categories, including contracts, agreements, estate planning, and business formation documents</li>
                <li>Download, print, and share generated documents</li>
                <li>Store and manage documents within their account</li>
              </ul>

              <div className="mt-4 rounded-lg border border-destructive/20 bg-destructive/5 p-6">
                <p className="text-sm text-muted-foreground leading-relaxed">
                  <strong className="text-foreground">Important Notice:</strong> LegalLawDocs.com is NOT a
                  law firm and does NOT provide legal advice, legal representation,
                  or attorney-client relationships. Our Service provides self-help
                  document generation tools at your specific direction. The documents
                  generated by our platform are for informational purposes and should
                  be reviewed by a qualified attorney before use in any legal
                  proceeding or transaction. We do not guarantee that any document
                  generated will be suitable for your specific legal needs or
                  enforceable in your jurisdiction.
                </p>
              </div>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                3. User Accounts
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                To access certain features of our Service, you must create an
                account. You agree to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Provide accurate, current, and complete information during registration</li>
                <li>Maintain the security and confidentiality of your account credentials</li>
                <li>Promptly update your account information if it changes</li>
                <li>Accept responsibility for all activity that occurs under your account</li>
                <li>Notify us immediately of any unauthorized use of your account</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed mt-4">
                You must be at least 18 years of age to create an account and use our
                Service. We reserve the right to suspend or terminate accounts that
                violate these Terms.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                4. Payment Terms
              </h2>
              <h3 className="font-serif text-lg font-semibold text-foreground mt-6 mb-3">
                4.1 Subscription Plans
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                Our Service is offered through various subscription plans. By
                selecting a plan, you agree to pay the applicable fees as described at
                the time of purchase. Subscription fees are billed in advance on a
                recurring basis (monthly or annually, depending on the plan selected).
              </p>

              <h3 className="font-serif text-lg font-semibold text-foreground mt-6 mb-3">
                4.2 Billing and Renewals
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                Subscriptions automatically renew at the end of each billing cycle
                unless you cancel before the renewal date. You authorize us to charge
                your payment method on file for renewal fees. We will notify you of
                any price changes before your next billing cycle.
              </p>

              <h3 className="font-serif text-lg font-semibold text-foreground mt-6 mb-3">
                4.3 Refunds
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                Refunds are handled on a case-by-case basis. If you are dissatisfied
                with our Service, please contact our support team within 14 days of
                your purchase for a refund review. Refunds are not available for
                documents that have already been generated and downloaded.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                5. Intellectual Property
              </h2>
              <h3 className="font-serif text-lg font-semibold text-foreground mt-6 mb-3">
                5.1 Our Intellectual Property
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                The Service, including its original content, features, functionality,
                software, design, trademarks, and branding, is owned by
                LegalLawDocs.com and is protected by copyright, trademark, and other
                intellectual property laws. You may not copy, modify, distribute, or
                create derivative works based on our platform without express written
                permission.
              </p>

              <h3 className="font-serif text-lg font-semibold text-foreground mt-6 mb-3">
                5.2 Your Content
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                You retain ownership of the information you input into our platform
                and the documents generated from that information. By using our
                Service, you grant us a limited, non-exclusive license to process
                your data solely for the purpose of providing and improving the
                Service. We do not claim ownership over documents generated using
                your data.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                6. Acceptable Use
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                You agree not to use our Service to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Generate documents for fraudulent, illegal, or deceptive purposes</li>
                <li>Impersonate any person or entity, or misrepresent your identity</li>
                <li>Interfere with or disrupt the Service or its infrastructure</li>
                <li>Attempt to gain unauthorized access to our systems or other user accounts</li>
                <li>Use automated tools (bots, scrapers) to access the Service without permission</li>
                <li>Violate any applicable local, state, national, or international law</li>
                <li>Resell, redistribute, or sublicense the Service or generated documents for commercial template purposes</li>
              </ul>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                7. Disclaimers
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS
                WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING
                BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
                PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ACCURACY.
              </p>
              <p className="text-muted-foreground leading-relaxed mt-4">
                We do not warrant that:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Documents generated by the Service will meet specific legal requirements in your jurisdiction</li>
                <li>The Service will be uninterrupted, timely, secure, or error-free</li>
                <li>AI-generated content will be free of errors or omissions</li>
                <li>Documents will be enforceable or legally binding without review by a qualified attorney</li>
              </ul>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                8. Limitation of Liability
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL
                LEGALLAWDOCS.COM, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, OR
                AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
                CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS
                OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES,
                RESULTING FROM:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Your use of or inability to use the Service</li>
                <li>Any legal consequences arising from documents generated through the Service</li>
                <li>Unauthorized access to or alteration of your data</li>
                <li>Any third-party conduct on the Service</li>
                <li>Any other matter relating to the Service</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed mt-4">
                Our total aggregate liability to you for all claims arising out of or
                relating to these Terms or the Service shall not exceed the amount you
                paid to us in the twelve (12) months preceding the claim.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                9. Indemnification
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                You agree to indemnify, defend, and hold harmless LegalLawDocs.com
                and its officers, directors, employees, and agents from any claims,
                damages, losses, liabilities, costs, and expenses (including
                reasonable attorney fees) arising out of your use of the Service,
                your violation of these Terms, or your violation of any rights of a
                third party.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                10. Termination
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                We may terminate or suspend your account and access to the Service
                immediately, without prior notice or liability, for any reason,
                including if you breach these Terms. Upon termination:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Your right to use the Service will cease immediately</li>
                <li>You may request a copy of your data within 30 days of termination</li>
                <li>We may delete your account data after the 30-day retention period</li>
                <li>Any outstanding payment obligations will remain in effect</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed mt-4">
                You may terminate your account at any time by contacting our support
                team or through your account settings.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                11. Governing Law and Dispute Resolution
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                These Terms shall be governed by and construed in accordance with the
                laws of the State of Delaware, United States, without regard to its
                conflict of law provisions. Any disputes arising from these Terms or
                the Service shall be resolved through binding arbitration administered
                by the American Arbitration Association (AAA) under its Commercial
                Arbitration Rules. The arbitration shall take place in Wilmington,
                Delaware. Each party shall bear its own costs of arbitration.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                12. Changes to These Terms
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to modify these Terms at any time. We will
                provide notice of material changes by posting the updated Terms on
                this page and updating the &quot;Last updated&quot; date. Your continued use
                of the Service after changes take effect constitutes acceptance of the
                revised Terms. If you do not agree with any changes, you must stop
                using the Service.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                13. Severability
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                If any provision of these Terms is found to be unenforceable or
                invalid, that provision will be limited or eliminated to the minimum
                extent necessary so that the remaining Terms remain in full force and
                effect.
              </p>

              <h2 className="font-serif text-2xl font-semibold text-foreground mt-10 mb-4">
                14. Contact Information
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                If you have questions about these Terms, please contact us:
              </p>
              <div className="mt-4 rounded-lg border border-border/40 bg-secondary/30 p-6">
                <p className="text-foreground font-medium">LegalLawDocs.com</p>
                <p className="text-muted-foreground mt-1">
                  Email:{" "}
                  <Link href="mailto:legal@legallawdocs.com" className="text-primary hover:underline">
                    legal@legallawdocs.com
                  </Link>
                </p>
                <p className="text-muted-foreground mt-1">
                  Contact Page:{" "}
                  <Link href="/contact" className="text-primary hover:underline">
                    legallawdocs.com/contact
                  </Link>
                </p>
              </div>

              {/* Disclaimer */}
              <div className="mt-10 rounded-lg border border-primary/20 bg-primary/5 p-6">
                <p className="text-sm text-muted-foreground leading-relaxed">
                  <strong className="text-foreground">Disclaimer:</strong> LegalLawDocs.com is not a law
                  firm and does not provide legal advice. Our platform provides
                  self-help document generation services at your specific direction.
                  We are not a substitute for an attorney. If you require legal
                  counsel, please consult a qualified attorney licensed in your
                  jurisdiction.
                </p>
              </div>
            </CardContent>
          </Card>
        </section>
      </main>
      <Footer />
    </div>
  )
}
